// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/articletagstag"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/predicate"
)

// ArticleTagsTagQuery is the builder for querying ArticleTagsTag entities.
type ArticleTagsTagQuery struct {
	config
	ctx        *QueryContext
	order      []articletagstag.OrderOption
	inters     []Interceptor
	predicates []predicate.ArticleTagsTag
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ArticleTagsTagQuery builder.
func (attq *ArticleTagsTagQuery) Where(ps ...predicate.ArticleTagsTag) *ArticleTagsTagQuery {
	attq.predicates = append(attq.predicates, ps...)
	return attq
}

// Limit the number of records to be returned by this query.
func (attq *ArticleTagsTagQuery) Limit(limit int) *ArticleTagsTagQuery {
	attq.ctx.Limit = &limit
	return attq
}

// Offset to start from.
func (attq *ArticleTagsTagQuery) Offset(offset int) *ArticleTagsTagQuery {
	attq.ctx.Offset = &offset
	return attq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (attq *ArticleTagsTagQuery) Unique(unique bool) *ArticleTagsTagQuery {
	attq.ctx.Unique = &unique
	return attq
}

// Order specifies how the records should be ordered.
func (attq *ArticleTagsTagQuery) Order(o ...articletagstag.OrderOption) *ArticleTagsTagQuery {
	attq.order = append(attq.order, o...)
	return attq
}

// First returns the first ArticleTagsTag entity from the query.
// Returns a *NotFoundError when no ArticleTagsTag was found.
func (attq *ArticleTagsTagQuery) First(ctx context.Context) (*ArticleTagsTag, error) {
	nodes, err := attq.Limit(1).All(setContextOp(ctx, attq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{articletagstag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) FirstX(ctx context.Context) *ArticleTagsTag {
	node, err := attq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ArticleTagsTag ID from the query.
// Returns a *NotFoundError when no ArticleTagsTag ID was found.
func (attq *ArticleTagsTagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = attq.Limit(1).IDs(setContextOp(ctx, attq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{articletagstag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) FirstIDX(ctx context.Context) int {
	id, err := attq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ArticleTagsTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ArticleTagsTag entity is found.
// Returns a *NotFoundError when no ArticleTagsTag entities are found.
func (attq *ArticleTagsTagQuery) Only(ctx context.Context) (*ArticleTagsTag, error) {
	nodes, err := attq.Limit(2).All(setContextOp(ctx, attq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{articletagstag.Label}
	default:
		return nil, &NotSingularError{articletagstag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) OnlyX(ctx context.Context) *ArticleTagsTag {
	node, err := attq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ArticleTagsTag ID in the query.
// Returns a *NotSingularError when more than one ArticleTagsTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (attq *ArticleTagsTagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = attq.Limit(2).IDs(setContextOp(ctx, attq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{articletagstag.Label}
	default:
		err = &NotSingularError{articletagstag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) OnlyIDX(ctx context.Context) int {
	id, err := attq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ArticleTagsTags.
func (attq *ArticleTagsTagQuery) All(ctx context.Context) ([]*ArticleTagsTag, error) {
	ctx = setContextOp(ctx, attq.ctx, ent.OpQueryAll)
	if err := attq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ArticleTagsTag, *ArticleTagsTagQuery]()
	return withInterceptors[[]*ArticleTagsTag](ctx, attq, qr, attq.inters)
}

// AllX is like All, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) AllX(ctx context.Context) []*ArticleTagsTag {
	nodes, err := attq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ArticleTagsTag IDs.
func (attq *ArticleTagsTagQuery) IDs(ctx context.Context) (ids []int, err error) {
	if attq.ctx.Unique == nil && attq.path != nil {
		attq.Unique(true)
	}
	ctx = setContextOp(ctx, attq.ctx, ent.OpQueryIDs)
	if err = attq.Select(articletagstag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) IDsX(ctx context.Context) []int {
	ids, err := attq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (attq *ArticleTagsTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, attq.ctx, ent.OpQueryCount)
	if err := attq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, attq, querierCount[*ArticleTagsTagQuery](), attq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) CountX(ctx context.Context) int {
	count, err := attq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (attq *ArticleTagsTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, attq.ctx, ent.OpQueryExist)
	switch _, err := attq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (attq *ArticleTagsTagQuery) ExistX(ctx context.Context) bool {
	exist, err := attq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ArticleTagsTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (attq *ArticleTagsTagQuery) Clone() *ArticleTagsTagQuery {
	if attq == nil {
		return nil
	}
	return &ArticleTagsTagQuery{
		config:     attq.config,
		ctx:        attq.ctx.Clone(),
		order:      append([]articletagstag.OrderOption{}, attq.order...),
		inters:     append([]Interceptor{}, attq.inters...),
		predicates: append([]predicate.ArticleTagsTag{}, attq.predicates...),
		// clone intermediate query.
		sql:  attq.sql.Clone(),
		path: attq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ArticleId int `json:"articleId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ArticleTagsTag.Query().
//		GroupBy(articletagstag.FieldArticleId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (attq *ArticleTagsTagQuery) GroupBy(field string, fields ...string) *ArticleTagsTagGroupBy {
	attq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ArticleTagsTagGroupBy{build: attq}
	grbuild.flds = &attq.ctx.Fields
	grbuild.label = articletagstag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ArticleId int `json:"articleId,omitempty"`
//	}
//
//	client.ArticleTagsTag.Query().
//		Select(articletagstag.FieldArticleId).
//		Scan(ctx, &v)
func (attq *ArticleTagsTagQuery) Select(fields ...string) *ArticleTagsTagSelect {
	attq.ctx.Fields = append(attq.ctx.Fields, fields...)
	sbuild := &ArticleTagsTagSelect{ArticleTagsTagQuery: attq}
	sbuild.label = articletagstag.Label
	sbuild.flds, sbuild.scan = &attq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ArticleTagsTagSelect configured with the given aggregations.
func (attq *ArticleTagsTagQuery) Aggregate(fns ...AggregateFunc) *ArticleTagsTagSelect {
	return attq.Select().Aggregate(fns...)
}

func (attq *ArticleTagsTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range attq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, attq); err != nil {
				return err
			}
		}
	}
	for _, f := range attq.ctx.Fields {
		if !articletagstag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if attq.path != nil {
		prev, err := attq.path(ctx)
		if err != nil {
			return err
		}
		attq.sql = prev
	}
	return nil
}

func (attq *ArticleTagsTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ArticleTagsTag, error) {
	var (
		nodes = []*ArticleTagsTag{}
		_spec = attq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ArticleTagsTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ArticleTagsTag{config: attq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, attq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (attq *ArticleTagsTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := attq.querySpec()
	_spec.Node.Columns = attq.ctx.Fields
	if len(attq.ctx.Fields) > 0 {
		_spec.Unique = attq.ctx.Unique != nil && *attq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, attq.driver, _spec)
}

func (attq *ArticleTagsTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(articletagstag.Table, articletagstag.Columns, sqlgraph.NewFieldSpec(articletagstag.FieldID, field.TypeInt))
	_spec.From = attq.sql
	if unique := attq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if attq.path != nil {
		_spec.Unique = true
	}
	if fields := attq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articletagstag.FieldID)
		for i := range fields {
			if fields[i] != articletagstag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := attq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := attq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := attq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := attq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (attq *ArticleTagsTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(attq.driver.Dialect())
	t1 := builder.Table(articletagstag.Table)
	columns := attq.ctx.Fields
	if len(columns) == 0 {
		columns = articletagstag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if attq.sql != nil {
		selector = attq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if attq.ctx.Unique != nil && *attq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range attq.predicates {
		p(selector)
	}
	for _, p := range attq.order {
		p(selector)
	}
	if offset := attq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := attq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ArticleTagsTagGroupBy is the group-by builder for ArticleTagsTag entities.
type ArticleTagsTagGroupBy struct {
	selector
	build *ArticleTagsTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (attgb *ArticleTagsTagGroupBy) Aggregate(fns ...AggregateFunc) *ArticleTagsTagGroupBy {
	attgb.fns = append(attgb.fns, fns...)
	return attgb
}

// Scan applies the selector query and scans the result into the given value.
func (attgb *ArticleTagsTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, attgb.build.ctx, ent.OpQueryGroupBy)
	if err := attgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArticleTagsTagQuery, *ArticleTagsTagGroupBy](ctx, attgb.build, attgb, attgb.build.inters, v)
}

func (attgb *ArticleTagsTagGroupBy) sqlScan(ctx context.Context, root *ArticleTagsTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(attgb.fns))
	for _, fn := range attgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*attgb.flds)+len(attgb.fns))
		for _, f := range *attgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*attgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := attgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ArticleTagsTagSelect is the builder for selecting fields of ArticleTagsTag entities.
type ArticleTagsTagSelect struct {
	*ArticleTagsTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (atts *ArticleTagsTagSelect) Aggregate(fns ...AggregateFunc) *ArticleTagsTagSelect {
	atts.fns = append(atts.fns, fns...)
	return atts
}

// Scan applies the selector query and scans the result into the given value.
func (atts *ArticleTagsTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, atts.ctx, ent.OpQuerySelect)
	if err := atts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ArticleTagsTagQuery, *ArticleTagsTagSelect](ctx, atts.ArticleTagsTagQuery, atts, atts.inters, v)
}

func (atts *ArticleTagsTagSelect) sqlScan(ctx context.Context, root *ArticleTagsTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(atts.fns))
	for _, fn := range atts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*atts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := atts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
