// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/collect"
)

// Collect is the model entity for the Collect schema.
type Collect struct {
	config `json:"-"`
	// ID of the ent.
	// 主键 ID
	ID string `json:"id,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"createTime,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"updateTime,omitempty"`
	// 收藏用户id
	UID int `json:"uid,omitempty"`
	// 收藏文章id
	ArticleId    int `json:"articleId,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Collect) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collect.FieldUID, collect.FieldArticleId:
			values[i] = new(sql.NullInt64)
		case collect.FieldID:
			values[i] = new(sql.NullString)
		case collect.FieldCreateTime, collect.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Collect fields.
func (c *Collect) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collect.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				c.ID = value.String
			}
		case collect.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createTime", values[i])
			} else if value.Valid {
				c.CreateTime = value.Time
			}
		case collect.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updateTime", values[i])
			} else if value.Valid {
				c.UpdateTime = value.Time
			}
		case collect.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				c.UID = int(value.Int64)
			}
		case collect.FieldArticleId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field articleId", values[i])
			} else if value.Valid {
				c.ArticleId = int(value.Int64)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Collect.
// This includes values selected through modifiers, order, etc.
func (c *Collect) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Collect.
// Note that you need to call Collect.Unwrap() before calling this method if this Collect
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Collect) Update() *CollectUpdateOne {
	return NewCollectClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Collect entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Collect) Unwrap() *Collect {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Collect is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Collect) String() string {
	var builder strings.Builder
	builder.WriteString("Collect(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("createTime=")
	builder.WriteString(c.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updateTime=")
	builder.WriteString(c.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", c.UID))
	builder.WriteString(", ")
	builder.WriteString("articleId=")
	builder.WriteString(fmt.Sprintf("%v", c.ArticleId))
	builder.WriteByte(')')
	return builder.String()
}

// Collects is a parsable slice of Collect.
type Collects []*Collect
