// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/like"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/predicate"
)

// LikeUpdate is the builder for updating Like entities.
type LikeUpdate struct {
	config
	hooks    []Hook
	mutation *LikeMutation
}

// Where appends a list predicates to the LikeUpdate builder.
func (lu *LikeUpdate) Where(ps ...predicate.Like) *LikeUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetArticleId sets the "articleId" field.
func (lu *LikeUpdate) SetArticleId(i int) *LikeUpdate {
	lu.mutation.ResetArticleId()
	lu.mutation.SetArticleId(i)
	return lu
}

// SetNillableArticleId sets the "articleId" field if the given value is not nil.
func (lu *LikeUpdate) SetNillableArticleId(i *int) *LikeUpdate {
	if i != nil {
		lu.SetArticleId(*i)
	}
	return lu
}

// AddArticleId adds i to the "articleId" field.
func (lu *LikeUpdate) AddArticleId(i int) *LikeUpdate {
	lu.mutation.AddArticleId(i)
	return lu
}

// SetUID sets the "uid" field.
func (lu *LikeUpdate) SetUID(i int) *LikeUpdate {
	lu.mutation.ResetUID()
	lu.mutation.SetUID(i)
	return lu
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (lu *LikeUpdate) SetNillableUID(i *int) *LikeUpdate {
	if i != nil {
		lu.SetUID(*i)
	}
	return lu
}

// AddUID adds i to the "uid" field.
func (lu *LikeUpdate) AddUID(i int) *LikeUpdate {
	lu.mutation.AddUID(i)
	return lu
}

// SetIP sets the "ip" field.
func (lu *LikeUpdate) SetIP(s string) *LikeUpdate {
	lu.mutation.SetIP(s)
	return lu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (lu *LikeUpdate) SetNillableIP(s *string) *LikeUpdate {
	if s != nil {
		lu.SetIP(*s)
	}
	return lu
}

// SetStatus sets the "status" field.
func (lu *LikeUpdate) SetStatus(s string) *LikeUpdate {
	lu.mutation.SetStatus(s)
	return lu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (lu *LikeUpdate) SetNillableStatus(s *string) *LikeUpdate {
	if s != nil {
		lu.SetStatus(*s)
	}
	return lu
}

// Mutation returns the LikeMutation object of the builder.
func (lu *LikeUpdate) Mutation() *LikeMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LikeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LikeUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LikeUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LikeUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lu *LikeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeString))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.ArticleId(); ok {
		_spec.SetField(like.FieldArticleId, field.TypeInt, value)
	}
	if value, ok := lu.mutation.AddedArticleId(); ok {
		_spec.AddField(like.FieldArticleId, field.TypeInt, value)
	}
	if value, ok := lu.mutation.UID(); ok {
		_spec.SetField(like.FieldUID, field.TypeInt, value)
	}
	if value, ok := lu.mutation.AddedUID(); ok {
		_spec.AddField(like.FieldUID, field.TypeInt, value)
	}
	if value, ok := lu.mutation.IP(); ok {
		_spec.SetField(like.FieldIP, field.TypeString, value)
	}
	if value, ok := lu.mutation.Status(); ok {
		_spec.SetField(like.FieldStatus, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LikeUpdateOne is the builder for updating a single Like entity.
type LikeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LikeMutation
}

// SetArticleId sets the "articleId" field.
func (luo *LikeUpdateOne) SetArticleId(i int) *LikeUpdateOne {
	luo.mutation.ResetArticleId()
	luo.mutation.SetArticleId(i)
	return luo
}

// SetNillableArticleId sets the "articleId" field if the given value is not nil.
func (luo *LikeUpdateOne) SetNillableArticleId(i *int) *LikeUpdateOne {
	if i != nil {
		luo.SetArticleId(*i)
	}
	return luo
}

// AddArticleId adds i to the "articleId" field.
func (luo *LikeUpdateOne) AddArticleId(i int) *LikeUpdateOne {
	luo.mutation.AddArticleId(i)
	return luo
}

// SetUID sets the "uid" field.
func (luo *LikeUpdateOne) SetUID(i int) *LikeUpdateOne {
	luo.mutation.ResetUID()
	luo.mutation.SetUID(i)
	return luo
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (luo *LikeUpdateOne) SetNillableUID(i *int) *LikeUpdateOne {
	if i != nil {
		luo.SetUID(*i)
	}
	return luo
}

// AddUID adds i to the "uid" field.
func (luo *LikeUpdateOne) AddUID(i int) *LikeUpdateOne {
	luo.mutation.AddUID(i)
	return luo
}

// SetIP sets the "ip" field.
func (luo *LikeUpdateOne) SetIP(s string) *LikeUpdateOne {
	luo.mutation.SetIP(s)
	return luo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (luo *LikeUpdateOne) SetNillableIP(s *string) *LikeUpdateOne {
	if s != nil {
		luo.SetIP(*s)
	}
	return luo
}

// SetStatus sets the "status" field.
func (luo *LikeUpdateOne) SetStatus(s string) *LikeUpdateOne {
	luo.mutation.SetStatus(s)
	return luo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (luo *LikeUpdateOne) SetNillableStatus(s *string) *LikeUpdateOne {
	if s != nil {
		luo.SetStatus(*s)
	}
	return luo
}

// Mutation returns the LikeMutation object of the builder.
func (luo *LikeUpdateOne) Mutation() *LikeMutation {
	return luo.mutation
}

// Where appends a list predicates to the LikeUpdate builder.
func (luo *LikeUpdateOne) Where(ps ...predicate.Like) *LikeUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LikeUpdateOne) Select(field string, fields ...string) *LikeUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Like entity.
func (luo *LikeUpdateOne) Save(ctx context.Context) (*Like, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LikeUpdateOne) SaveX(ctx context.Context) *Like {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LikeUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LikeUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luo *LikeUpdateOne) sqlSave(ctx context.Context) (_node *Like, err error) {
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeString))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Like.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, like.FieldID)
		for _, f := range fields {
			if !like.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != like.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.ArticleId(); ok {
		_spec.SetField(like.FieldArticleId, field.TypeInt, value)
	}
	if value, ok := luo.mutation.AddedArticleId(); ok {
		_spec.AddField(like.FieldArticleId, field.TypeInt, value)
	}
	if value, ok := luo.mutation.UID(); ok {
		_spec.SetField(like.FieldUID, field.TypeInt, value)
	}
	if value, ok := luo.mutation.AddedUID(); ok {
		_spec.AddField(like.FieldUID, field.TypeInt, value)
	}
	if value, ok := luo.mutation.IP(); ok {
		_spec.SetField(like.FieldIP, field.TypeString, value)
	}
	if value, ok := luo.mutation.Status(); ok {
		_spec.SetField(like.FieldStatus, field.TypeString, value)
	}
	_node = &Like{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
