// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/blog/ent/ragquerylog"
)

// RagQueryLogQuery is the builder for querying RagQueryLog entities.
type RagQueryLogQuery struct {
	config
	ctx        *QueryContext
	order      []ragquerylog.OrderOption
	inters     []Interceptor
	predicates []predicate.RagQueryLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RagQueryLogQuery builder.
func (rqlq *RagQueryLogQuery) Where(ps ...predicate.RagQueryLog) *RagQueryLogQuery {
	rqlq.predicates = append(rqlq.predicates, ps...)
	return rqlq
}

// Limit the number of records to be returned by this query.
func (rqlq *RagQueryLogQuery) Limit(limit int) *RagQueryLogQuery {
	rqlq.ctx.Limit = &limit
	return rqlq
}

// Offset to start from.
func (rqlq *RagQueryLogQuery) Offset(offset int) *RagQueryLogQuery {
	rqlq.ctx.Offset = &offset
	return rqlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rqlq *RagQueryLogQuery) Unique(unique bool) *RagQueryLogQuery {
	rqlq.ctx.Unique = &unique
	return rqlq
}

// Order specifies how the records should be ordered.
func (rqlq *RagQueryLogQuery) Order(o ...ragquerylog.OrderOption) *RagQueryLogQuery {
	rqlq.order = append(rqlq.order, o...)
	return rqlq
}

// First returns the first RagQueryLog entity from the query.
// Returns a *NotFoundError when no RagQueryLog was found.
func (rqlq *RagQueryLogQuery) First(ctx context.Context) (*RagQueryLog, error) {
	nodes, err := rqlq.Limit(1).All(setContextOp(ctx, rqlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ragquerylog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) FirstX(ctx context.Context) *RagQueryLog {
	node, err := rqlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RagQueryLog ID from the query.
// Returns a *NotFoundError when no RagQueryLog ID was found.
func (rqlq *RagQueryLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rqlq.Limit(1).IDs(setContextOp(ctx, rqlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ragquerylog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) FirstIDX(ctx context.Context) int {
	id, err := rqlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RagQueryLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RagQueryLog entity is found.
// Returns a *NotFoundError when no RagQueryLog entities are found.
func (rqlq *RagQueryLogQuery) Only(ctx context.Context) (*RagQueryLog, error) {
	nodes, err := rqlq.Limit(2).All(setContextOp(ctx, rqlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ragquerylog.Label}
	default:
		return nil, &NotSingularError{ragquerylog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) OnlyX(ctx context.Context) *RagQueryLog {
	node, err := rqlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RagQueryLog ID in the query.
// Returns a *NotSingularError when more than one RagQueryLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (rqlq *RagQueryLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rqlq.Limit(2).IDs(setContextOp(ctx, rqlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ragquerylog.Label}
	default:
		err = &NotSingularError{ragquerylog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := rqlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RagQueryLogs.
func (rqlq *RagQueryLogQuery) All(ctx context.Context) ([]*RagQueryLog, error) {
	ctx = setContextOp(ctx, rqlq.ctx, ent.OpQueryAll)
	if err := rqlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RagQueryLog, *RagQueryLogQuery]()
	return withInterceptors[[]*RagQueryLog](ctx, rqlq, qr, rqlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) AllX(ctx context.Context) []*RagQueryLog {
	nodes, err := rqlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RagQueryLog IDs.
func (rqlq *RagQueryLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rqlq.ctx.Unique == nil && rqlq.path != nil {
		rqlq.Unique(true)
	}
	ctx = setContextOp(ctx, rqlq.ctx, ent.OpQueryIDs)
	if err = rqlq.Select(ragquerylog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) IDsX(ctx context.Context) []int {
	ids, err := rqlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rqlq *RagQueryLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rqlq.ctx, ent.OpQueryCount)
	if err := rqlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rqlq, querierCount[*RagQueryLogQuery](), rqlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) CountX(ctx context.Context) int {
	count, err := rqlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rqlq *RagQueryLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rqlq.ctx, ent.OpQueryExist)
	switch _, err := rqlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rqlq *RagQueryLogQuery) ExistX(ctx context.Context) bool {
	exist, err := rqlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RagQueryLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rqlq *RagQueryLogQuery) Clone() *RagQueryLogQuery {
	if rqlq == nil {
		return nil
	}
	return &RagQueryLogQuery{
		config:     rqlq.config,
		ctx:        rqlq.ctx.Clone(),
		order:      append([]ragquerylog.OrderOption{}, rqlq.order...),
		inters:     append([]Interceptor{}, rqlq.inters...),
		predicates: append([]predicate.RagQueryLog{}, rqlq.predicates...),
		// clone intermediate query.
		sql:  rqlq.sql.Clone(),
		path: rqlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UID int `json:"uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RagQueryLog.Query().
//		GroupBy(ragquerylog.FieldUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rqlq *RagQueryLogQuery) GroupBy(field string, fields ...string) *RagQueryLogGroupBy {
	rqlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RagQueryLogGroupBy{build: rqlq}
	grbuild.flds = &rqlq.ctx.Fields
	grbuild.label = ragquerylog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UID int `json:"uid,omitempty"`
//	}
//
//	client.RagQueryLog.Query().
//		Select(ragquerylog.FieldUID).
//		Scan(ctx, &v)
func (rqlq *RagQueryLogQuery) Select(fields ...string) *RagQueryLogSelect {
	rqlq.ctx.Fields = append(rqlq.ctx.Fields, fields...)
	sbuild := &RagQueryLogSelect{RagQueryLogQuery: rqlq}
	sbuild.label = ragquerylog.Label
	sbuild.flds, sbuild.scan = &rqlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RagQueryLogSelect configured with the given aggregations.
func (rqlq *RagQueryLogQuery) Aggregate(fns ...AggregateFunc) *RagQueryLogSelect {
	return rqlq.Select().Aggregate(fns...)
}

func (rqlq *RagQueryLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rqlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rqlq); err != nil {
				return err
			}
		}
	}
	for _, f := range rqlq.ctx.Fields {
		if !ragquerylog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rqlq.path != nil {
		prev, err := rqlq.path(ctx)
		if err != nil {
			return err
		}
		rqlq.sql = prev
	}
	return nil
}

func (rqlq *RagQueryLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RagQueryLog, error) {
	var (
		nodes = []*RagQueryLog{}
		_spec = rqlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RagQueryLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RagQueryLog{config: rqlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rqlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rqlq *RagQueryLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rqlq.querySpec()
	_spec.Node.Columns = rqlq.ctx.Fields
	if len(rqlq.ctx.Fields) > 0 {
		_spec.Unique = rqlq.ctx.Unique != nil && *rqlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rqlq.driver, _spec)
}

func (rqlq *RagQueryLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ragquerylog.Table, ragquerylog.Columns, sqlgraph.NewFieldSpec(ragquerylog.FieldID, field.TypeInt))
	_spec.From = rqlq.sql
	if unique := rqlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rqlq.path != nil {
		_spec.Unique = true
	}
	if fields := rqlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ragquerylog.FieldID)
		for i := range fields {
			if fields[i] != ragquerylog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rqlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rqlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rqlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rqlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rqlq *RagQueryLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rqlq.driver.Dialect())
	t1 := builder.Table(ragquerylog.Table)
	columns := rqlq.ctx.Fields
	if len(columns) == 0 {
		columns = ragquerylog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rqlq.sql != nil {
		selector = rqlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rqlq.ctx.Unique != nil && *rqlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rqlq.predicates {
		p(selector)
	}
	for _, p := range rqlq.order {
		p(selector)
	}
	if offset := rqlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rqlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RagQueryLogGroupBy is the group-by builder for RagQueryLog entities.
type RagQueryLogGroupBy struct {
	selector
	build *RagQueryLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rqlgb *RagQueryLogGroupBy) Aggregate(fns ...AggregateFunc) *RagQueryLogGroupBy {
	rqlgb.fns = append(rqlgb.fns, fns...)
	return rqlgb
}

// Scan applies the selector query and scans the result into the given value.
func (rqlgb *RagQueryLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rqlgb.build.ctx, ent.OpQueryGroupBy)
	if err := rqlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RagQueryLogQuery, *RagQueryLogGroupBy](ctx, rqlgb.build, rqlgb, rqlgb.build.inters, v)
}

func (rqlgb *RagQueryLogGroupBy) sqlScan(ctx context.Context, root *RagQueryLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rqlgb.fns))
	for _, fn := range rqlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rqlgb.flds)+len(rqlgb.fns))
		for _, f := range *rqlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rqlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rqlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RagQueryLogSelect is the builder for selecting fields of RagQueryLog entities.
type RagQueryLogSelect struct {
	*RagQueryLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rqls *RagQueryLogSelect) Aggregate(fns ...AggregateFunc) *RagQueryLogSelect {
	rqls.fns = append(rqls.fns, fns...)
	return rqls
}

// Scan applies the selector query and scans the result into the given value.
func (rqls *RagQueryLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rqls.ctx, ent.OpQuerySelect)
	if err := rqls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RagQueryLogQuery, *RagQueryLogSelect](ctx, rqls.RagQueryLogQuery, rqls, rqls.inters, v)
}

func (rqls *RagQueryLogSelect) sqlScan(ctx context.Context, root *RagQueryLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rqls.fns))
	for _, fn := range rqls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rqls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rqls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
