// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/user/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/user/ent/rolemenusmenu"
)

// RoleMenusMenuQuery is the builder for querying RoleMenusMenu entities.
type RoleMenusMenuQuery struct {
	config
	ctx        *QueryContext
	order      []rolemenusmenu.OrderOption
	inters     []Interceptor
	predicates []predicate.RoleMenusMenu
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoleMenusMenuQuery builder.
func (rmmq *RoleMenusMenuQuery) Where(ps ...predicate.RoleMenusMenu) *RoleMenusMenuQuery {
	rmmq.predicates = append(rmmq.predicates, ps...)
	return rmmq
}

// Limit the number of records to be returned by this query.
func (rmmq *RoleMenusMenuQuery) Limit(limit int) *RoleMenusMenuQuery {
	rmmq.ctx.Limit = &limit
	return rmmq
}

// Offset to start from.
func (rmmq *RoleMenusMenuQuery) Offset(offset int) *RoleMenusMenuQuery {
	rmmq.ctx.Offset = &offset
	return rmmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rmmq *RoleMenusMenuQuery) Unique(unique bool) *RoleMenusMenuQuery {
	rmmq.ctx.Unique = &unique
	return rmmq
}

// Order specifies how the records should be ordered.
func (rmmq *RoleMenusMenuQuery) Order(o ...rolemenusmenu.OrderOption) *RoleMenusMenuQuery {
	rmmq.order = append(rmmq.order, o...)
	return rmmq
}

// First returns the first RoleMenusMenu entity from the query.
// Returns a *NotFoundError when no RoleMenusMenu was found.
func (rmmq *RoleMenusMenuQuery) First(ctx context.Context) (*RoleMenusMenu, error) {
	nodes, err := rmmq.Limit(1).All(setContextOp(ctx, rmmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rolemenusmenu.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) FirstX(ctx context.Context) *RoleMenusMenu {
	node, err := rmmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoleMenusMenu ID from the query.
// Returns a *NotFoundError when no RoleMenusMenu ID was found.
func (rmmq *RoleMenusMenuQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmmq.Limit(1).IDs(setContextOp(ctx, rmmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rolemenusmenu.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) FirstIDX(ctx context.Context) int {
	id, err := rmmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoleMenusMenu entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoleMenusMenu entity is found.
// Returns a *NotFoundError when no RoleMenusMenu entities are found.
func (rmmq *RoleMenusMenuQuery) Only(ctx context.Context) (*RoleMenusMenu, error) {
	nodes, err := rmmq.Limit(2).All(setContextOp(ctx, rmmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rolemenusmenu.Label}
	default:
		return nil, &NotSingularError{rolemenusmenu.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) OnlyX(ctx context.Context) *RoleMenusMenu {
	node, err := rmmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoleMenusMenu ID in the query.
// Returns a *NotSingularError when more than one RoleMenusMenu ID is found.
// Returns a *NotFoundError when no entities are found.
func (rmmq *RoleMenusMenuQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rmmq.Limit(2).IDs(setContextOp(ctx, rmmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rolemenusmenu.Label}
	default:
		err = &NotSingularError{rolemenusmenu.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) OnlyIDX(ctx context.Context) int {
	id, err := rmmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoleMenusMenus.
func (rmmq *RoleMenusMenuQuery) All(ctx context.Context) ([]*RoleMenusMenu, error) {
	ctx = setContextOp(ctx, rmmq.ctx, ent.OpQueryAll)
	if err := rmmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoleMenusMenu, *RoleMenusMenuQuery]()
	return withInterceptors[[]*RoleMenusMenu](ctx, rmmq, qr, rmmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) AllX(ctx context.Context) []*RoleMenusMenu {
	nodes, err := rmmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoleMenusMenu IDs.
func (rmmq *RoleMenusMenuQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rmmq.ctx.Unique == nil && rmmq.path != nil {
		rmmq.Unique(true)
	}
	ctx = setContextOp(ctx, rmmq.ctx, ent.OpQueryIDs)
	if err = rmmq.Select(rolemenusmenu.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) IDsX(ctx context.Context) []int {
	ids, err := rmmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rmmq *RoleMenusMenuQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rmmq.ctx, ent.OpQueryCount)
	if err := rmmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rmmq, querierCount[*RoleMenusMenuQuery](), rmmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) CountX(ctx context.Context) int {
	count, err := rmmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rmmq *RoleMenusMenuQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rmmq.ctx, ent.OpQueryExist)
	switch _, err := rmmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rmmq *RoleMenusMenuQuery) ExistX(ctx context.Context) bool {
	exist, err := rmmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoleMenusMenuQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rmmq *RoleMenusMenuQuery) Clone() *RoleMenusMenuQuery {
	if rmmq == nil {
		return nil
	}
	return &RoleMenusMenuQuery{
		config:     rmmq.config,
		ctx:        rmmq.ctx.Clone(),
		order:      append([]rolemenusmenu.OrderOption{}, rmmq.order...),
		inters:     append([]Interceptor{}, rmmq.inters...),
		predicates: append([]predicate.RoleMenusMenu{}, rmmq.predicates...),
		// clone intermediate query.
		sql:  rmmq.sql.Clone(),
		path: rmmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoleId int `json:"roleId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoleMenusMenu.Query().
//		GroupBy(rolemenusmenu.FieldRoleId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rmmq *RoleMenusMenuQuery) GroupBy(field string, fields ...string) *RoleMenusMenuGroupBy {
	rmmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoleMenusMenuGroupBy{build: rmmq}
	grbuild.flds = &rmmq.ctx.Fields
	grbuild.label = rolemenusmenu.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoleId int `json:"roleId,omitempty"`
//	}
//
//	client.RoleMenusMenu.Query().
//		Select(rolemenusmenu.FieldRoleId).
//		Scan(ctx, &v)
func (rmmq *RoleMenusMenuQuery) Select(fields ...string) *RoleMenusMenuSelect {
	rmmq.ctx.Fields = append(rmmq.ctx.Fields, fields...)
	sbuild := &RoleMenusMenuSelect{RoleMenusMenuQuery: rmmq}
	sbuild.label = rolemenusmenu.Label
	sbuild.flds, sbuild.scan = &rmmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoleMenusMenuSelect configured with the given aggregations.
func (rmmq *RoleMenusMenuQuery) Aggregate(fns ...AggregateFunc) *RoleMenusMenuSelect {
	return rmmq.Select().Aggregate(fns...)
}

func (rmmq *RoleMenusMenuQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rmmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rmmq); err != nil {
				return err
			}
		}
	}
	for _, f := range rmmq.ctx.Fields {
		if !rolemenusmenu.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rmmq.path != nil {
		prev, err := rmmq.path(ctx)
		if err != nil {
			return err
		}
		rmmq.sql = prev
	}
	return nil
}

func (rmmq *RoleMenusMenuQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoleMenusMenu, error) {
	var (
		nodes = []*RoleMenusMenu{}
		_spec = rmmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoleMenusMenu).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoleMenusMenu{config: rmmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rmmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rmmq *RoleMenusMenuQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rmmq.querySpec()
	_spec.Node.Columns = rmmq.ctx.Fields
	if len(rmmq.ctx.Fields) > 0 {
		_spec.Unique = rmmq.ctx.Unique != nil && *rmmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rmmq.driver, _spec)
}

func (rmmq *RoleMenusMenuQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rolemenusmenu.Table, rolemenusmenu.Columns, sqlgraph.NewFieldSpec(rolemenusmenu.FieldID, field.TypeInt))
	_spec.From = rmmq.sql
	if unique := rmmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rmmq.path != nil {
		_spec.Unique = true
	}
	if fields := rmmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolemenusmenu.FieldID)
		for i := range fields {
			if fields[i] != rolemenusmenu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rmmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rmmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rmmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rmmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rmmq *RoleMenusMenuQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rmmq.driver.Dialect())
	t1 := builder.Table(rolemenusmenu.Table)
	columns := rmmq.ctx.Fields
	if len(columns) == 0 {
		columns = rolemenusmenu.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rmmq.sql != nil {
		selector = rmmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rmmq.ctx.Unique != nil && *rmmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rmmq.predicates {
		p(selector)
	}
	for _, p := range rmmq.order {
		p(selector)
	}
	if offset := rmmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rmmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoleMenusMenuGroupBy is the group-by builder for RoleMenusMenu entities.
type RoleMenusMenuGroupBy struct {
	selector
	build *RoleMenusMenuQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rmmgb *RoleMenusMenuGroupBy) Aggregate(fns ...AggregateFunc) *RoleMenusMenuGroupBy {
	rmmgb.fns = append(rmmgb.fns, fns...)
	return rmmgb
}

// Scan applies the selector query and scans the result into the given value.
func (rmmgb *RoleMenusMenuGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmmgb.build.ctx, ent.OpQueryGroupBy)
	if err := rmmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleMenusMenuQuery, *RoleMenusMenuGroupBy](ctx, rmmgb.build, rmmgb, rmmgb.build.inters, v)
}

func (rmmgb *RoleMenusMenuGroupBy) sqlScan(ctx context.Context, root *RoleMenusMenuQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rmmgb.fns))
	for _, fn := range rmmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rmmgb.flds)+len(rmmgb.fns))
		for _, f := range *rmmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rmmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoleMenusMenuSelect is the builder for selecting fields of RoleMenusMenu entities.
type RoleMenusMenuSelect struct {
	*RoleMenusMenuQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rmms *RoleMenusMenuSelect) Aggregate(fns ...AggregateFunc) *RoleMenusMenuSelect {
	rmms.fns = append(rmms.fns, fns...)
	return rmms
}

// Scan applies the selector query and scans the result into the given value.
func (rmms *RoleMenusMenuSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rmms.ctx, ent.OpQuerySelect)
	if err := rmms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoleMenusMenuQuery, *RoleMenusMenuSelect](ctx, rmms.RoleMenusMenuQuery, rmms, rmms.inters, v)
}

func (rmms *RoleMenusMenuSelect) sqlScan(ctx context.Context, root *RoleMenusMenuQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rmms.fns))
	for _, fn := range rmms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rmms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rmms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
