// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/user/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/user/ent/sensitivewordhit"
)

// SensitiveWordHitQuery is the builder for querying SensitiveWordHit entities.
type SensitiveWordHitQuery struct {
	config
	ctx        *QueryContext
	order      []sensitivewordhit.OrderOption
	inters     []Interceptor
	predicates []predicate.SensitiveWordHit
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SensitiveWordHitQuery builder.
func (swhq *SensitiveWordHitQuery) Where(ps ...predicate.SensitiveWordHit) *SensitiveWordHitQuery {
	swhq.predicates = append(swhq.predicates, ps...)
	return swhq
}

// Limit the number of records to be returned by this query.
func (swhq *SensitiveWordHitQuery) Limit(limit int) *SensitiveWordHitQuery {
	swhq.ctx.Limit = &limit
	return swhq
}

// Offset to start from.
func (swhq *SensitiveWordHitQuery) Offset(offset int) *SensitiveWordHitQuery {
	swhq.ctx.Offset = &offset
	return swhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (swhq *SensitiveWordHitQuery) Unique(unique bool) *SensitiveWordHitQuery {
	swhq.ctx.Unique = &unique
	return swhq
}

// Order specifies how the records should be ordered.
func (swhq *SensitiveWordHitQuery) Order(o ...sensitivewordhit.OrderOption) *SensitiveWordHitQuery {
	swhq.order = append(swhq.order, o...)
	return swhq
}

// First returns the first SensitiveWordHit entity from the query.
// Returns a *NotFoundError when no SensitiveWordHit was found.
func (swhq *SensitiveWordHitQuery) First(ctx context.Context) (*SensitiveWordHit, error) {
	nodes, err := swhq.Limit(1).All(setContextOp(ctx, swhq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sensitivewordhit.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) FirstX(ctx context.Context) *SensitiveWordHit {
	node, err := swhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SensitiveWordHit ID from the query.
// Returns a *NotFoundError when no SensitiveWordHit ID was found.
func (swhq *SensitiveWordHitQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = swhq.Limit(1).IDs(setContextOp(ctx, swhq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sensitivewordhit.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) FirstIDX(ctx context.Context) int {
	id, err := swhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SensitiveWordHit entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SensitiveWordHit entity is found.
// Returns a *NotFoundError when no SensitiveWordHit entities are found.
func (swhq *SensitiveWordHitQuery) Only(ctx context.Context) (*SensitiveWordHit, error) {
	nodes, err := swhq.Limit(2).All(setContextOp(ctx, swhq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sensitivewordhit.Label}
	default:
		return nil, &NotSingularError{sensitivewordhit.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) OnlyX(ctx context.Context) *SensitiveWordHit {
	node, err := swhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SensitiveWordHit ID in the query.
// Returns a *NotSingularError when more than one SensitiveWordHit ID is found.
// Returns a *NotFoundError when no entities are found.
func (swhq *SensitiveWordHitQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = swhq.Limit(2).IDs(setContextOp(ctx, swhq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sensitivewordhit.Label}
	default:
		err = &NotSingularError{sensitivewordhit.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) OnlyIDX(ctx context.Context) int {
	id, err := swhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SensitiveWordHits.
func (swhq *SensitiveWordHitQuery) All(ctx context.Context) ([]*SensitiveWordHit, error) {
	ctx = setContextOp(ctx, swhq.ctx, ent.OpQueryAll)
	if err := swhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SensitiveWordHit, *SensitiveWordHitQuery]()
	return withInterceptors[[]*SensitiveWordHit](ctx, swhq, qr, swhq.inters)
}

// AllX is like All, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) AllX(ctx context.Context) []*SensitiveWordHit {
	nodes, err := swhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SensitiveWordHit IDs.
func (swhq *SensitiveWordHitQuery) IDs(ctx context.Context) (ids []int, err error) {
	if swhq.ctx.Unique == nil && swhq.path != nil {
		swhq.Unique(true)
	}
	ctx = setContextOp(ctx, swhq.ctx, ent.OpQueryIDs)
	if err = swhq.Select(sensitivewordhit.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) IDsX(ctx context.Context) []int {
	ids, err := swhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (swhq *SensitiveWordHitQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, swhq.ctx, ent.OpQueryCount)
	if err := swhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, swhq, querierCount[*SensitiveWordHitQuery](), swhq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) CountX(ctx context.Context) int {
	count, err := swhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (swhq *SensitiveWordHitQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, swhq.ctx, ent.OpQueryExist)
	switch _, err := swhq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (swhq *SensitiveWordHitQuery) ExistX(ctx context.Context) bool {
	exist, err := swhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SensitiveWordHitQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (swhq *SensitiveWordHitQuery) Clone() *SensitiveWordHitQuery {
	if swhq == nil {
		return nil
	}
	return &SensitiveWordHitQuery{
		config:     swhq.config,
		ctx:        swhq.ctx.Clone(),
		order:      append([]sensitivewordhit.OrderOption{}, swhq.order...),
		inters:     append([]Interceptor{}, swhq.inters...),
		predicates: append([]predicate.SensitiveWordHit{}, swhq.predicates...),
		// clone intermediate query.
		sql:  swhq.sql.Clone(),
		path: swhq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SourceType string `json:"sourceType,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SensitiveWordHit.Query().
//		GroupBy(sensitivewordhit.FieldSourceType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (swhq *SensitiveWordHitQuery) GroupBy(field string, fields ...string) *SensitiveWordHitGroupBy {
	swhq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SensitiveWordHitGroupBy{build: swhq}
	grbuild.flds = &swhq.ctx.Fields
	grbuild.label = sensitivewordhit.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SourceType string `json:"sourceType,omitempty"`
//	}
//
//	client.SensitiveWordHit.Query().
//		Select(sensitivewordhit.FieldSourceType).
//		Scan(ctx, &v)
func (swhq *SensitiveWordHitQuery) Select(fields ...string) *SensitiveWordHitSelect {
	swhq.ctx.Fields = append(swhq.ctx.Fields, fields...)
	sbuild := &SensitiveWordHitSelect{SensitiveWordHitQuery: swhq}
	sbuild.label = sensitivewordhit.Label
	sbuild.flds, sbuild.scan = &swhq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SensitiveWordHitSelect configured with the given aggregations.
func (swhq *SensitiveWordHitQuery) Aggregate(fns ...AggregateFunc) *SensitiveWordHitSelect {
	return swhq.Select().Aggregate(fns...)
}

func (swhq *SensitiveWordHitQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range swhq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, swhq); err != nil {
				return err
			}
		}
	}
	for _, f := range swhq.ctx.Fields {
		if !sensitivewordhit.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if swhq.path != nil {
		prev, err := swhq.path(ctx)
		if err != nil {
			return err
		}
		swhq.sql = prev
	}
	return nil
}

func (swhq *SensitiveWordHitQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SensitiveWordHit, error) {
	var (
		nodes = []*SensitiveWordHit{}
		_spec = swhq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SensitiveWordHit).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SensitiveWordHit{config: swhq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, swhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (swhq *SensitiveWordHitQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := swhq.querySpec()
	_spec.Node.Columns = swhq.ctx.Fields
	if len(swhq.ctx.Fields) > 0 {
		_spec.Unique = swhq.ctx.Unique != nil && *swhq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, swhq.driver, _spec)
}

func (swhq *SensitiveWordHitQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sensitivewordhit.Table, sensitivewordhit.Columns, sqlgraph.NewFieldSpec(sensitivewordhit.FieldID, field.TypeInt))
	_spec.From = swhq.sql
	if unique := swhq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if swhq.path != nil {
		_spec.Unique = true
	}
	if fields := swhq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sensitivewordhit.FieldID)
		for i := range fields {
			if fields[i] != sensitivewordhit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := swhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := swhq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := swhq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := swhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (swhq *SensitiveWordHitQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(swhq.driver.Dialect())
	t1 := builder.Table(sensitivewordhit.Table)
	columns := swhq.ctx.Fields
	if len(columns) == 0 {
		columns = sensitivewordhit.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if swhq.sql != nil {
		selector = swhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if swhq.ctx.Unique != nil && *swhq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range swhq.predicates {
		p(selector)
	}
	for _, p := range swhq.order {
		p(selector)
	}
	if offset := swhq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := swhq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SensitiveWordHitGroupBy is the group-by builder for SensitiveWordHit entities.
type SensitiveWordHitGroupBy struct {
	selector
	build *SensitiveWordHitQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (swhgb *SensitiveWordHitGroupBy) Aggregate(fns ...AggregateFunc) *SensitiveWordHitGroupBy {
	swhgb.fns = append(swhgb.fns, fns...)
	return swhgb
}

// Scan applies the selector query and scans the result into the given value.
func (swhgb *SensitiveWordHitGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, swhgb.build.ctx, ent.OpQueryGroupBy)
	if err := swhgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensitiveWordHitQuery, *SensitiveWordHitGroupBy](ctx, swhgb.build, swhgb, swhgb.build.inters, v)
}

func (swhgb *SensitiveWordHitGroupBy) sqlScan(ctx context.Context, root *SensitiveWordHitQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(swhgb.fns))
	for _, fn := range swhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*swhgb.flds)+len(swhgb.fns))
		for _, f := range *swhgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*swhgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := swhgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SensitiveWordHitSelect is the builder for selecting fields of SensitiveWordHit entities.
type SensitiveWordHitSelect struct {
	*SensitiveWordHitQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (swhs *SensitiveWordHitSelect) Aggregate(fns ...AggregateFunc) *SensitiveWordHitSelect {
	swhs.fns = append(swhs.fns, fns...)
	return swhs
}

// Scan applies the selector query and scans the result into the given value.
func (swhs *SensitiveWordHitSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, swhs.ctx, ent.OpQuerySelect)
	if err := swhs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SensitiveWordHitQuery, *SensitiveWordHitSelect](ctx, swhs.SensitiveWordHitQuery, swhs, swhs.inters, v)
}

func (swhs *SensitiveWordHitSelect) sqlScan(ctx context.Context, root *SensitiveWordHitQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(swhs.fns))
	for _, fn := range swhs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*swhs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := swhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
