// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/article"
)

// Article is the model entity for the Article schema.
type Article struct {
	config `json:"-"`
	// ID of the ent.
	// 主键id
	ID int `json:"id,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"createTime,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"updateTime,omitempty"`
	// 软删除标记
	IsDelete bool `json:"isDelete,omitempty"`
	// 乐观锁版本号
	Version int `json:"version,omitempty"`
	// 文章的更新时间
	UTime string `json:"uTime,omitempty"`
	// 用户id
	UID int `json:"uid,omitempty"`
	// 所属机构ID
	DeptId *int `json:"deptId,omitempty"`
	// Topping holds the value of the "topping" field.
	Topping int `json:"topping,omitempty"`
	// 文章标题
	Title string `json:"title,omitempty"`
	// 封面图
	Cover string `json:"cover,omitempty"`
	// 喜欢/点赞数
	Likes int `json:"likes,omitempty"`
	// 阅读量
	Views int `json:"views,omitempty"`
	// 文章经验
	ArticleExp int `json:"articleExp,omitempty"`
	// 文章等级
	ArticleLevel int `json:"articleLevel,omitempty"`
	// 该文贡献作者声望
	ReputationGained int `json:"reputationGained,omitempty"`
	// 神作标记
	IsMasterpiece int `json:"isMasterpiece,omitempty"`
	// 累计被打赏碎片
	TipTotal int `json:"tipTotal,omitempty"`
	// 文章状态: draft-草稿, publish-已发布, scheduled-定时发布
	Status string `json:"status,omitempty"`
	// 文章描述
	Description string `json:"description,omitempty"`
	// 文章html
	ContentHtml string `json:"contentHtml,omitempty"`
	// UseArticles holds the value of the "useArticles" field.
	UseArticles *int `json:"useArticles,omitempty"`
	// Articles holds the value of the "articles" field.
	Articles *string `json:"articles,omitempty"`
	// 文章内容
	Content string `json:"content,omitempty"`
	// 定时发布时间
	ScheduledPublishAt *time.Time `json:"scheduledPublishAt,omitempty"`
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Article) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case article.FieldIsDelete:
			values[i] = new(sql.NullBool)
		case article.FieldID, article.FieldVersion, article.FieldUID, article.FieldDeptId, article.FieldTopping, article.FieldLikes, article.FieldViews, article.FieldArticleExp, article.FieldArticleLevel, article.FieldReputationGained, article.FieldIsMasterpiece, article.FieldTipTotal, article.FieldUseArticles:
			values[i] = new(sql.NullInt64)
		case article.FieldUTime, article.FieldTitle, article.FieldCover, article.FieldStatus, article.FieldDescription, article.FieldContentHtml, article.FieldArticles, article.FieldContent:
			values[i] = new(sql.NullString)
		case article.FieldCreateTime, article.FieldUpdateTime, article.FieldScheduledPublishAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Article fields.
func (a *Article) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case article.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			a.ID = int(value.Int64)
		case article.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createTime", values[i])
			} else if value.Valid {
				a.CreateTime = value.Time
			}
		case article.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updateTime", values[i])
			} else if value.Valid {
				a.UpdateTime = value.Time
			}
		case article.FieldIsDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isDelete", values[i])
			} else if value.Valid {
				a.IsDelete = value.Bool
			}
		case article.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				a.Version = int(value.Int64)
			}
		case article.FieldUTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uTime", values[i])
			} else if value.Valid {
				a.UTime = value.String
			}
		case article.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				a.UID = int(value.Int64)
			}
		case article.FieldDeptId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deptId", values[i])
			} else if value.Valid {
				a.DeptId = new(int)
				*a.DeptId = int(value.Int64)
			}
		case article.FieldTopping:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topping", values[i])
			} else if value.Valid {
				a.Topping = int(value.Int64)
			}
		case article.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				a.Title = value.String
			}
		case article.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				a.Cover = value.String
			}
		case article.FieldLikes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field likes", values[i])
			} else if value.Valid {
				a.Likes = int(value.Int64)
			}
		case article.FieldViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field views", values[i])
			} else if value.Valid {
				a.Views = int(value.Int64)
			}
		case article.FieldArticleExp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field articleExp", values[i])
			} else if value.Valid {
				a.ArticleExp = int(value.Int64)
			}
		case article.FieldArticleLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field articleLevel", values[i])
			} else if value.Valid {
				a.ArticleLevel = int(value.Int64)
			}
		case article.FieldReputationGained:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reputationGained", values[i])
			} else if value.Valid {
				a.ReputationGained = int(value.Int64)
			}
		case article.FieldIsMasterpiece:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field isMasterpiece", values[i])
			} else if value.Valid {
				a.IsMasterpiece = int(value.Int64)
			}
		case article.FieldTipTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tipTotal", values[i])
			} else if value.Valid {
				a.TipTotal = int(value.Int64)
			}
		case article.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				a.Status = value.String
			}
		case article.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				a.Description = value.String
			}
		case article.FieldContentHtml:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contentHtml", values[i])
			} else if value.Valid {
				a.ContentHtml = value.String
			}
		case article.FieldUseArticles:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field useArticles", values[i])
			} else if value.Valid {
				a.UseArticles = new(int)
				*a.UseArticles = int(value.Int64)
			}
		case article.FieldArticles:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field articles", values[i])
			} else if value.Valid {
				a.Articles = new(string)
				*a.Articles = value.String
			}
		case article.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				a.Content = value.String
			}
		case article.FieldScheduledPublishAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduledPublishAt", values[i])
			} else if value.Valid {
				a.ScheduledPublishAt = new(time.Time)
				*a.ScheduledPublishAt = value.Time
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Article.
// This includes values selected through modifiers, order, etc.
func (a *Article) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Article.
// Note that you need to call Article.Unwrap() before calling this method if this Article
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Article) Update() *ArticleUpdateOne {
	return NewArticleClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Article entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Article) Unwrap() *Article {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Article is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Article) String() string {
	var builder strings.Builder
	builder.WriteString("Article(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("createTime=")
	builder.WriteString(a.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updateTime=")
	builder.WriteString(a.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("isDelete=")
	builder.WriteString(fmt.Sprintf("%v", a.IsDelete))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", a.Version))
	builder.WriteString(", ")
	builder.WriteString("uTime=")
	builder.WriteString(a.UTime)
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", a.UID))
	builder.WriteString(", ")
	if v := a.DeptId; v != nil {
		builder.WriteString("deptId=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("topping=")
	builder.WriteString(fmt.Sprintf("%v", a.Topping))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(a.Title)
	builder.WriteString(", ")
	builder.WriteString("cover=")
	builder.WriteString(a.Cover)
	builder.WriteString(", ")
	builder.WriteString("likes=")
	builder.WriteString(fmt.Sprintf("%v", a.Likes))
	builder.WriteString(", ")
	builder.WriteString("views=")
	builder.WriteString(fmt.Sprintf("%v", a.Views))
	builder.WriteString(", ")
	builder.WriteString("articleExp=")
	builder.WriteString(fmt.Sprintf("%v", a.ArticleExp))
	builder.WriteString(", ")
	builder.WriteString("articleLevel=")
	builder.WriteString(fmt.Sprintf("%v", a.ArticleLevel))
	builder.WriteString(", ")
	builder.WriteString("reputationGained=")
	builder.WriteString(fmt.Sprintf("%v", a.ReputationGained))
	builder.WriteString(", ")
	builder.WriteString("isMasterpiece=")
	builder.WriteString(fmt.Sprintf("%v", a.IsMasterpiece))
	builder.WriteString(", ")
	builder.WriteString("tipTotal=")
	builder.WriteString(fmt.Sprintf("%v", a.TipTotal))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(a.Status)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(a.Description)
	builder.WriteString(", ")
	builder.WriteString("contentHtml=")
	builder.WriteString(a.ContentHtml)
	builder.WriteString(", ")
	if v := a.UseArticles; v != nil {
		builder.WriteString("useArticles=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := a.Articles; v != nil {
		builder.WriteString("articles=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(a.Content)
	builder.WriteString(", ")
	if v := a.ScheduledPublishAt; v != nil {
		builder.WriteString("scheduledPublishAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Articles is a parsable slice of Article.
type Articles []*Article
