// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/link"
)

// LinkCreate is the builder for creating a Link entity.
type LinkCreate struct {
	config
	mutation *LinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "createTime" field.
func (_c *LinkCreate) SetCreateTime(v time.Time) *LinkCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (_c *LinkCreate) SetNillableCreateTime(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "updateTime" field.
func (_c *LinkCreate) SetUpdateTime(v time.Time) *LinkCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (_c *LinkCreate) SetNillableUpdateTime(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "isDelete" field.
func (_c *LinkCreate) SetIsDelete(v bool) *LinkCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_c *LinkCreate) SetNillableIsDelete(v *bool) *LinkCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *LinkCreate) SetVersion(v int) *LinkCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *LinkCreate) SetNillableVersion(v *int) *LinkCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *LinkCreate) SetIcon(v string) *LinkCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *LinkCreate) SetURL(v string) *LinkCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *LinkCreate) SetTitle(v string) *LinkCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDesp sets the "desp" field.
func (_c *LinkCreate) SetDesp(v string) *LinkCreate {
	_c.mutation.SetDesp(v)
	return _c
}

// SetAgreed sets the "agreed" field.
func (_c *LinkCreate) SetAgreed(v int) *LinkCreate {
	_c.mutation.SetAgreed(v)
	return _c
}

// SetNillableAgreed sets the "agreed" field if the given value is not nil.
func (_c *LinkCreate) SetNillableAgreed(v *int) *LinkCreate {
	if v != nil {
		_c.SetAgreed(*v)
	}
	return _c
}

// SetLastCheckStatus sets the "lastCheckStatus" field.
func (_c *LinkCreate) SetLastCheckStatus(v string) *LinkCreate {
	_c.mutation.SetLastCheckStatus(v)
	return _c
}

// SetNillableLastCheckStatus sets the "lastCheckStatus" field if the given value is not nil.
func (_c *LinkCreate) SetNillableLastCheckStatus(v *string) *LinkCreate {
	if v != nil {
		_c.SetLastCheckStatus(*v)
	}
	return _c
}

// SetLastCheckTime sets the "lastCheckTime" field.
func (_c *LinkCreate) SetLastCheckTime(v time.Time) *LinkCreate {
	_c.mutation.SetLastCheckTime(v)
	return _c
}

// SetNillableLastCheckTime sets the "lastCheckTime" field if the given value is not nil.
func (_c *LinkCreate) SetNillableLastCheckTime(v *time.Time) *LinkCreate {
	if v != nil {
		_c.SetLastCheckTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LinkCreate) SetID(v int) *LinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the LinkMutation object of the builder.
func (_c *LinkCreate) Mutation() *LinkMutation {
	return _c.mutation
}

// Save creates the Link in the database.
func (_c *LinkCreate) Save(ctx context.Context) (*Link, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCreate) SaveX(ctx context.Context) *Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := link.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := link.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := link.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := link.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Agreed(); !ok {
		v := link.DefaultAgreed
		_c.mutation.SetAgreed(v)
	}
	if _, ok := _c.mutation.LastCheckStatus(); !ok {
		v := link.DefaultLastCheckStatus
		_c.mutation.SetLastCheckStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "Link.createTime"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "Link.updateTime"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "isDelete", err: errors.New(`ent: missing required field "Link.isDelete"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Link.version"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Link.icon"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Link.url"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Link.title"`)}
	}
	if _, ok := _c.mutation.Desp(); !ok {
		return &ValidationError{Name: "desp", err: errors.New(`ent: missing required field "Link.desp"`)}
	}
	if _, ok := _c.mutation.Agreed(); !ok {
		return &ValidationError{Name: "agreed", err: errors.New(`ent: missing required field "Link.agreed"`)}
	}
	if _, ok := _c.mutation.LastCheckStatus(); !ok {
		return &ValidationError{Name: "lastCheckStatus", err: errors.New(`ent: missing required field "Link.lastCheckStatus"`)}
	}
	return nil
}

func (_c *LinkCreate) sqlSave(ctx context.Context) (*Link, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCreate) createSpec() (*Link, *sqlgraph.CreateSpec) {
	var (
		_node = &Link{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(link.Table, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(link.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(link.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(link.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(link.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(link.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(link.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Desp(); ok {
		_spec.SetField(link.FieldDesp, field.TypeString, value)
		_node.Desp = value
	}
	if value, ok := _c.mutation.Agreed(); ok {
		_spec.SetField(link.FieldAgreed, field.TypeInt, value)
		_node.Agreed = value
	}
	if value, ok := _c.mutation.LastCheckStatus(); ok {
		_spec.SetField(link.FieldLastCheckStatus, field.TypeString, value)
		_node.LastCheckStatus = value
	}
	if value, ok := _c.mutation.LastCheckTime(); ok {
		_spec.SetField(link.FieldLastCheckTime, field.TypeTime, value)
		_node.LastCheckTime = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Link.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCreate) OnConflict(opts ...sql.ConflictOption) *LinkUpsertOne {
	_c.conflict = opts
	return &LinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCreate) OnConflictColumns(columns ...string) *LinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkUpsertOne{
		create: _c,
	}
}

type (
	// LinkUpsertOne is the builder for "upsert"-ing
	//  one Link node.
	LinkUpsertOne struct {
		create *LinkCreate
	}

	// LinkUpsert is the "OnConflict" setter.
	LinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "updateTime" field.
func (u *LinkUpsert) SetUpdateTime(v time.Time) *LinkUpsert {
	u.Set(link.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *LinkUpsert) UpdateUpdateTime() *LinkUpsert {
	u.SetExcluded(link.FieldUpdateTime)
	return u
}

// SetIsDelete sets the "isDelete" field.
func (u *LinkUpsert) SetIsDelete(v bool) *LinkUpsert {
	u.Set(link.FieldIsDelete, v)
	return u
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *LinkUpsert) UpdateIsDelete() *LinkUpsert {
	u.SetExcluded(link.FieldIsDelete)
	return u
}

// SetVersion sets the "version" field.
func (u *LinkUpsert) SetVersion(v int) *LinkUpsert {
	u.Set(link.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *LinkUpsert) UpdateVersion() *LinkUpsert {
	u.SetExcluded(link.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *LinkUpsert) AddVersion(v int) *LinkUpsert {
	u.Add(link.FieldVersion, v)
	return u
}

// SetIcon sets the "icon" field.
func (u *LinkUpsert) SetIcon(v string) *LinkUpsert {
	u.Set(link.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *LinkUpsert) UpdateIcon() *LinkUpsert {
	u.SetExcluded(link.FieldIcon)
	return u
}

// SetURL sets the "url" field.
func (u *LinkUpsert) SetURL(v string) *LinkUpsert {
	u.Set(link.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsert) UpdateURL() *LinkUpsert {
	u.SetExcluded(link.FieldURL)
	return u
}

// SetTitle sets the "title" field.
func (u *LinkUpsert) SetTitle(v string) *LinkUpsert {
	u.Set(link.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LinkUpsert) UpdateTitle() *LinkUpsert {
	u.SetExcluded(link.FieldTitle)
	return u
}

// SetDesp sets the "desp" field.
func (u *LinkUpsert) SetDesp(v string) *LinkUpsert {
	u.Set(link.FieldDesp, v)
	return u
}

// UpdateDesp sets the "desp" field to the value that was provided on create.
func (u *LinkUpsert) UpdateDesp() *LinkUpsert {
	u.SetExcluded(link.FieldDesp)
	return u
}

// SetAgreed sets the "agreed" field.
func (u *LinkUpsert) SetAgreed(v int) *LinkUpsert {
	u.Set(link.FieldAgreed, v)
	return u
}

// UpdateAgreed sets the "agreed" field to the value that was provided on create.
func (u *LinkUpsert) UpdateAgreed() *LinkUpsert {
	u.SetExcluded(link.FieldAgreed)
	return u
}

// AddAgreed adds v to the "agreed" field.
func (u *LinkUpsert) AddAgreed(v int) *LinkUpsert {
	u.Add(link.FieldAgreed, v)
	return u
}

// SetLastCheckStatus sets the "lastCheckStatus" field.
func (u *LinkUpsert) SetLastCheckStatus(v string) *LinkUpsert {
	u.Set(link.FieldLastCheckStatus, v)
	return u
}

// UpdateLastCheckStatus sets the "lastCheckStatus" field to the value that was provided on create.
func (u *LinkUpsert) UpdateLastCheckStatus() *LinkUpsert {
	u.SetExcluded(link.FieldLastCheckStatus)
	return u
}

// SetLastCheckTime sets the "lastCheckTime" field.
func (u *LinkUpsert) SetLastCheckTime(v time.Time) *LinkUpsert {
	u.Set(link.FieldLastCheckTime, v)
	return u
}

// UpdateLastCheckTime sets the "lastCheckTime" field to the value that was provided on create.
func (u *LinkUpsert) UpdateLastCheckTime() *LinkUpsert {
	u.SetExcluded(link.FieldLastCheckTime)
	return u
}

// ClearLastCheckTime clears the value of the "lastCheckTime" field.
func (u *LinkUpsert) ClearLastCheckTime() *LinkUpsert {
	u.SetNull(link.FieldLastCheckTime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(link.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkUpsertOne) UpdateNewValues() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(link.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(link.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkUpsertOne) Ignore() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkUpsertOne) DoNothing() *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCreate.OnConflict
// documentation for more info.
func (u *LinkUpsertOne) Update(set func(*LinkUpsert)) *LinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *LinkUpsertOne) SetUpdateTime(v time.Time) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateUpdateTime() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *LinkUpsertOne) SetIsDelete(v bool) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateIsDelete() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *LinkUpsertOne) SetVersion(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *LinkUpsertOne) AddVersion(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateVersion() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateVersion()
	})
}

// SetIcon sets the "icon" field.
func (u *LinkUpsertOne) SetIcon(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateIcon() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateIcon()
	})
}

// SetURL sets the "url" field.
func (u *LinkUpsertOne) SetURL(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateURL() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *LinkUpsertOne) SetTitle(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateTitle() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateTitle()
	})
}

// SetDesp sets the "desp" field.
func (u *LinkUpsertOne) SetDesp(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetDesp(v)
	})
}

// UpdateDesp sets the "desp" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateDesp() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDesp()
	})
}

// SetAgreed sets the "agreed" field.
func (u *LinkUpsertOne) SetAgreed(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetAgreed(v)
	})
}

// AddAgreed adds v to the "agreed" field.
func (u *LinkUpsertOne) AddAgreed(v int) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.AddAgreed(v)
	})
}

// UpdateAgreed sets the "agreed" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateAgreed() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateAgreed()
	})
}

// SetLastCheckStatus sets the "lastCheckStatus" field.
func (u *LinkUpsertOne) SetLastCheckStatus(v string) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetLastCheckStatus(v)
	})
}

// UpdateLastCheckStatus sets the "lastCheckStatus" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateLastCheckStatus() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateLastCheckStatus()
	})
}

// SetLastCheckTime sets the "lastCheckTime" field.
func (u *LinkUpsertOne) SetLastCheckTime(v time.Time) *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.SetLastCheckTime(v)
	})
}

// UpdateLastCheckTime sets the "lastCheckTime" field to the value that was provided on create.
func (u *LinkUpsertOne) UpdateLastCheckTime() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateLastCheckTime()
	})
}

// ClearLastCheckTime clears the value of the "lastCheckTime" field.
func (u *LinkUpsertOne) ClearLastCheckTime() *LinkUpsertOne {
	return u.Update(func(s *LinkUpsert) {
		s.ClearLastCheckTime()
	})
}

// Exec executes the query.
func (u *LinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCreateBulk is the builder for creating many Link entities in bulk.
type LinkCreateBulk struct {
	config
	err      error
	builders []*LinkCreate
	conflict []sql.ConflictOption
}

// Save creates the Link entities in the database.
func (_c *LinkCreateBulk) Save(ctx context.Context) ([]*Link, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Link, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCreateBulk) SaveX(ctx context.Context) []*Link {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Link.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkUpsertBulk {
	_c.conflict = opts
	return &LinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCreateBulk) OnConflictColumns(columns ...string) *LinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkUpsertBulk{
		create: _c,
	}
}

// LinkUpsertBulk is the builder for "upsert"-ing
// a bulk of Link nodes.
type LinkUpsertBulk struct {
	create *LinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(link.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LinkUpsertBulk) UpdateNewValues() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(link.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(link.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Link.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkUpsertBulk) Ignore() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkUpsertBulk) DoNothing() *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCreateBulk.OnConflict
// documentation for more info.
func (u *LinkUpsertBulk) Update(set func(*LinkUpsert)) *LinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *LinkUpsertBulk) SetUpdateTime(v time.Time) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateUpdateTime() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *LinkUpsertBulk) SetIsDelete(v bool) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateIsDelete() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *LinkUpsertBulk) SetVersion(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *LinkUpsertBulk) AddVersion(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateVersion() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateVersion()
	})
}

// SetIcon sets the "icon" field.
func (u *LinkUpsertBulk) SetIcon(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateIcon() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateIcon()
	})
}

// SetURL sets the "url" field.
func (u *LinkUpsertBulk) SetURL(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateURL() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateURL()
	})
}

// SetTitle sets the "title" field.
func (u *LinkUpsertBulk) SetTitle(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateTitle() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateTitle()
	})
}

// SetDesp sets the "desp" field.
func (u *LinkUpsertBulk) SetDesp(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetDesp(v)
	})
}

// UpdateDesp sets the "desp" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateDesp() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateDesp()
	})
}

// SetAgreed sets the "agreed" field.
func (u *LinkUpsertBulk) SetAgreed(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetAgreed(v)
	})
}

// AddAgreed adds v to the "agreed" field.
func (u *LinkUpsertBulk) AddAgreed(v int) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.AddAgreed(v)
	})
}

// UpdateAgreed sets the "agreed" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateAgreed() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateAgreed()
	})
}

// SetLastCheckStatus sets the "lastCheckStatus" field.
func (u *LinkUpsertBulk) SetLastCheckStatus(v string) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetLastCheckStatus(v)
	})
}

// UpdateLastCheckStatus sets the "lastCheckStatus" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateLastCheckStatus() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateLastCheckStatus()
	})
}

// SetLastCheckTime sets the "lastCheckTime" field.
func (u *LinkUpsertBulk) SetLastCheckTime(v time.Time) *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.SetLastCheckTime(v)
	})
}

// UpdateLastCheckTime sets the "lastCheckTime" field to the value that was provided on create.
func (u *LinkUpsertBulk) UpdateLastCheckTime() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.UpdateLastCheckTime()
	})
}

// ClearLastCheckTime clears the value of the "lastCheckTime" field.
func (u *LinkUpsertBulk) ClearLastCheckTime() *LinkUpsertBulk {
	return u.Update(func(s *LinkUpsert) {
		s.ClearLastCheckTime()
	})
}

// Exec executes the query.
func (u *LinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
