// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/ragquerylog"
)

// RagQueryLog is the model entity for the RagQueryLog schema.
type RagQueryLog struct {
	config `json:"-"`
	// ID of the ent.
	// 主键 ID
	ID int `json:"id,omitempty"`
	// UID holds the value of the "uid" field.
	UID int `json:"uid,omitempty"`
	// Question holds the value of the "question" field.
	Question string `json:"question,omitempty"`
	// AnswerPreview holds the value of the "answer_preview" field.
	AnswerPreview *string `json:"answer_preview,omitempty"`
	// CitationsJSON holds the value of the "citations_json" field.
	CitationsJSON map[string]interface{} `json:"citations_json,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs int `json:"latency_ms,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt     time.Time `json:"create_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RagQueryLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ragquerylog.FieldCitationsJSON:
			values[i] = new([]byte)
		case ragquerylog.FieldID, ragquerylog.FieldUID, ragquerylog.FieldLatencyMs:
			values[i] = new(sql.NullInt64)
		case ragquerylog.FieldQuestion, ragquerylog.FieldAnswerPreview, ragquerylog.FieldStatus:
			values[i] = new(sql.NullString)
		case ragquerylog.FieldCreateAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RagQueryLog fields.
func (_m *RagQueryLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ragquerylog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ragquerylog.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = int(value.Int64)
			}
		case ragquerylog.FieldQuestion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field question", values[i])
			} else if value.Valid {
				_m.Question = value.String
			}
		case ragquerylog.FieldAnswerPreview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field answer_preview", values[i])
			} else if value.Valid {
				_m.AnswerPreview = new(string)
				*_m.AnswerPreview = value.String
			}
		case ragquerylog.FieldCitationsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field citations_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CitationsJSON); err != nil {
					return fmt.Errorf("unmarshal field citations_json: %w", err)
				}
			}
		case ragquerylog.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = int(value.Int64)
			}
		case ragquerylog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case ragquerylog.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				_m.CreateAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RagQueryLog.
// This includes values selected through modifiers, order, etc.
func (_m *RagQueryLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RagQueryLog.
// Note that you need to call RagQueryLog.Unwrap() before calling this method if this RagQueryLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RagQueryLog) Update() *RagQueryLogUpdateOne {
	return NewRagQueryLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RagQueryLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RagQueryLog) Unwrap() *RagQueryLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RagQueryLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RagQueryLog) String() string {
	var builder strings.Builder
	builder.WriteString("RagQueryLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.UID))
	builder.WriteString(", ")
	builder.WriteString("question=")
	builder.WriteString(_m.Question)
	builder.WriteString(", ")
	if v := _m.AnswerPreview; v != nil {
		builder.WriteString("answer_preview=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("citations_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.CitationsJSON))
	builder.WriteString(", ")
	builder.WriteString("latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatencyMs))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("create_at=")
	builder.WriteString(_m.CreateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RagQueryLogs is a parsable slice of RagQueryLog.
type RagQueryLogs []*RagQueryLog
