// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rolemenusmenu"
)

// RoleMenusMenuCreate is the builder for creating a RoleMenusMenu entity.
type RoleMenusMenuCreate struct {
	config
	mutation *RoleMenusMenuMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRoleId sets the "roleId" field.
func (rmmc *RoleMenusMenuCreate) SetRoleId(i int) *RoleMenusMenuCreate {
	rmmc.mutation.SetRoleId(i)
	return rmmc
}

// SetMenuId sets the "menuId" field.
func (rmmc *RoleMenusMenuCreate) SetMenuId(s string) *RoleMenusMenuCreate {
	rmmc.mutation.SetMenuId(s)
	return rmmc
}

// Mutation returns the RoleMenusMenuMutation object of the builder.
func (rmmc *RoleMenusMenuCreate) Mutation() *RoleMenusMenuMutation {
	return rmmc.mutation
}

// Save creates the RoleMenusMenu in the database.
func (rmmc *RoleMenusMenuCreate) Save(ctx context.Context) (*RoleMenusMenu, error) {
	return withHooks(ctx, rmmc.sqlSave, rmmc.mutation, rmmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rmmc *RoleMenusMenuCreate) SaveX(ctx context.Context) *RoleMenusMenu {
	v, err := rmmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmmc *RoleMenusMenuCreate) Exec(ctx context.Context) error {
	_, err := rmmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmmc *RoleMenusMenuCreate) ExecX(ctx context.Context) {
	if err := rmmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rmmc *RoleMenusMenuCreate) check() error {
	if _, ok := rmmc.mutation.RoleId(); !ok {
		return &ValidationError{Name: "roleId", err: errors.New(`ent: missing required field "RoleMenusMenu.roleId"`)}
	}
	if _, ok := rmmc.mutation.MenuId(); !ok {
		return &ValidationError{Name: "menuId", err: errors.New(`ent: missing required field "RoleMenusMenu.menuId"`)}
	}
	return nil
}

func (rmmc *RoleMenusMenuCreate) sqlSave(ctx context.Context) (*RoleMenusMenu, error) {
	if err := rmmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rmmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rmmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rmmc.mutation.id = &_node.ID
	rmmc.mutation.done = true
	return _node, nil
}

func (rmmc *RoleMenusMenuCreate) createSpec() (*RoleMenusMenu, *sqlgraph.CreateSpec) {
	var (
		_node = &RoleMenusMenu{config: rmmc.config}
		_spec = sqlgraph.NewCreateSpec(rolemenusmenu.Table, sqlgraph.NewFieldSpec(rolemenusmenu.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rmmc.conflict
	if value, ok := rmmc.mutation.RoleId(); ok {
		_spec.SetField(rolemenusmenu.FieldRoleId, field.TypeInt, value)
		_node.RoleId = value
	}
	if value, ok := rmmc.mutation.MenuId(); ok {
		_spec.SetField(rolemenusmenu.FieldMenuId, field.TypeString, value)
		_node.MenuId = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoleMenusMenu.Create().
//		SetRoleId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoleMenusMenuUpsert) {
//			SetRoleId(v+v).
//		}).
//		Exec(ctx)
func (rmmc *RoleMenusMenuCreate) OnConflict(opts ...sql.ConflictOption) *RoleMenusMenuUpsertOne {
	rmmc.conflict = opts
	return &RoleMenusMenuUpsertOne{
		create: rmmc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rmmc *RoleMenusMenuCreate) OnConflictColumns(columns ...string) *RoleMenusMenuUpsertOne {
	rmmc.conflict = append(rmmc.conflict, sql.ConflictColumns(columns...))
	return &RoleMenusMenuUpsertOne{
		create: rmmc,
	}
}

type (
	// RoleMenusMenuUpsertOne is the builder for "upsert"-ing
	//  one RoleMenusMenu node.
	RoleMenusMenuUpsertOne struct {
		create *RoleMenusMenuCreate
	}

	// RoleMenusMenuUpsert is the "OnConflict" setter.
	RoleMenusMenuUpsert struct {
		*sql.UpdateSet
	}
)

// SetRoleId sets the "roleId" field.
func (u *RoleMenusMenuUpsert) SetRoleId(v int) *RoleMenusMenuUpsert {
	u.Set(rolemenusmenu.FieldRoleId, v)
	return u
}

// UpdateRoleId sets the "roleId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsert) UpdateRoleId() *RoleMenusMenuUpsert {
	u.SetExcluded(rolemenusmenu.FieldRoleId)
	return u
}

// AddRoleId adds v to the "roleId" field.
func (u *RoleMenusMenuUpsert) AddRoleId(v int) *RoleMenusMenuUpsert {
	u.Add(rolemenusmenu.FieldRoleId, v)
	return u
}

// SetMenuId sets the "menuId" field.
func (u *RoleMenusMenuUpsert) SetMenuId(v string) *RoleMenusMenuUpsert {
	u.Set(rolemenusmenu.FieldMenuId, v)
	return u
}

// UpdateMenuId sets the "menuId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsert) UpdateMenuId() *RoleMenusMenuUpsert {
	u.SetExcluded(rolemenusmenu.FieldMenuId)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoleMenusMenuUpsertOne) UpdateNewValues() *RoleMenusMenuUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RoleMenusMenuUpsertOne) Ignore() *RoleMenusMenuUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoleMenusMenuUpsertOne) DoNothing() *RoleMenusMenuUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoleMenusMenuCreate.OnConflict
// documentation for more info.
func (u *RoleMenusMenuUpsertOne) Update(set func(*RoleMenusMenuUpsert)) *RoleMenusMenuUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoleMenusMenuUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleId sets the "roleId" field.
func (u *RoleMenusMenuUpsertOne) SetRoleId(v int) *RoleMenusMenuUpsertOne {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.SetRoleId(v)
	})
}

// AddRoleId adds v to the "roleId" field.
func (u *RoleMenusMenuUpsertOne) AddRoleId(v int) *RoleMenusMenuUpsertOne {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.AddRoleId(v)
	})
}

// UpdateRoleId sets the "roleId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsertOne) UpdateRoleId() *RoleMenusMenuUpsertOne {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.UpdateRoleId()
	})
}

// SetMenuId sets the "menuId" field.
func (u *RoleMenusMenuUpsertOne) SetMenuId(v string) *RoleMenusMenuUpsertOne {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.SetMenuId(v)
	})
}

// UpdateMenuId sets the "menuId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsertOne) UpdateMenuId() *RoleMenusMenuUpsertOne {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.UpdateMenuId()
	})
}

// Exec executes the query.
func (u *RoleMenusMenuUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoleMenusMenuCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoleMenusMenuUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RoleMenusMenuUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RoleMenusMenuUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RoleMenusMenuCreateBulk is the builder for creating many RoleMenusMenu entities in bulk.
type RoleMenusMenuCreateBulk struct {
	config
	err      error
	builders []*RoleMenusMenuCreate
	conflict []sql.ConflictOption
}

// Save creates the RoleMenusMenu entities in the database.
func (rmmcb *RoleMenusMenuCreateBulk) Save(ctx context.Context) ([]*RoleMenusMenu, error) {
	if rmmcb.err != nil {
		return nil, rmmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rmmcb.builders))
	nodes := make([]*RoleMenusMenu, len(rmmcb.builders))
	mutators := make([]Mutator, len(rmmcb.builders))
	for i := range rmmcb.builders {
		func(i int, root context.Context) {
			builder := rmmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleMenusMenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rmmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rmmcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rmmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rmmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rmmcb *RoleMenusMenuCreateBulk) SaveX(ctx context.Context) []*RoleMenusMenu {
	v, err := rmmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rmmcb *RoleMenusMenuCreateBulk) Exec(ctx context.Context) error {
	_, err := rmmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rmmcb *RoleMenusMenuCreateBulk) ExecX(ctx context.Context) {
	if err := rmmcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoleMenusMenu.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoleMenusMenuUpsert) {
//			SetRoleId(v+v).
//		}).
//		Exec(ctx)
func (rmmcb *RoleMenusMenuCreateBulk) OnConflict(opts ...sql.ConflictOption) *RoleMenusMenuUpsertBulk {
	rmmcb.conflict = opts
	return &RoleMenusMenuUpsertBulk{
		create: rmmcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rmmcb *RoleMenusMenuCreateBulk) OnConflictColumns(columns ...string) *RoleMenusMenuUpsertBulk {
	rmmcb.conflict = append(rmmcb.conflict, sql.ConflictColumns(columns...))
	return &RoleMenusMenuUpsertBulk{
		create: rmmcb,
	}
}

// RoleMenusMenuUpsertBulk is the builder for "upsert"-ing
// a bulk of RoleMenusMenu nodes.
type RoleMenusMenuUpsertBulk struct {
	create *RoleMenusMenuCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RoleMenusMenuUpsertBulk) UpdateNewValues() *RoleMenusMenuUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoleMenusMenu.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RoleMenusMenuUpsertBulk) Ignore() *RoleMenusMenuUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoleMenusMenuUpsertBulk) DoNothing() *RoleMenusMenuUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoleMenusMenuCreateBulk.OnConflict
// documentation for more info.
func (u *RoleMenusMenuUpsertBulk) Update(set func(*RoleMenusMenuUpsert)) *RoleMenusMenuUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoleMenusMenuUpsert{UpdateSet: update})
	}))
	return u
}

// SetRoleId sets the "roleId" field.
func (u *RoleMenusMenuUpsertBulk) SetRoleId(v int) *RoleMenusMenuUpsertBulk {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.SetRoleId(v)
	})
}

// AddRoleId adds v to the "roleId" field.
func (u *RoleMenusMenuUpsertBulk) AddRoleId(v int) *RoleMenusMenuUpsertBulk {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.AddRoleId(v)
	})
}

// UpdateRoleId sets the "roleId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsertBulk) UpdateRoleId() *RoleMenusMenuUpsertBulk {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.UpdateRoleId()
	})
}

// SetMenuId sets the "menuId" field.
func (u *RoleMenusMenuUpsertBulk) SetMenuId(v string) *RoleMenusMenuUpsertBulk {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.SetMenuId(v)
	})
}

// UpdateMenuId sets the "menuId" field to the value that was provided on create.
func (u *RoleMenusMenuUpsertBulk) UpdateMenuId() *RoleMenusMenuUpsertBulk {
	return u.Update(func(s *RoleMenusMenuUpsert) {
		s.UpdateMenuId()
	})
}

// Exec executes the query.
func (u *RoleMenusMenuUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RoleMenusMenuCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoleMenusMenuCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoleMenusMenuUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
