// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpgactivity"
)

// RpgActivityCreate is the builder for creating a RpgActivity entity.
type RpgActivityCreate struct {
	config
	mutation *RpgActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "createTime" field.
func (_c *RpgActivityCreate) SetCreateTime(v time.Time) *RpgActivityCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableCreateTime(v *time.Time) *RpgActivityCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "updateTime" field.
func (_c *RpgActivityCreate) SetUpdateTime(v time.Time) *RpgActivityCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableUpdateTime(v *time.Time) *RpgActivityCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "isDelete" field.
func (_c *RpgActivityCreate) SetIsDelete(v bool) *RpgActivityCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableIsDelete(v *bool) *RpgActivityCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *RpgActivityCreate) SetVersion(v int) *RpgActivityCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableVersion(v *int) *RpgActivityCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *RpgActivityCreate) SetCode(v string) *RpgActivityCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RpgActivityCreate) SetName(v string) *RpgActivityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStartTime sets the "startTime" field.
func (_c *RpgActivityCreate) SetStartTime(v time.Time) *RpgActivityCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "endTime" field.
func (_c *RpgActivityCreate) SetEndTime(v time.Time) *RpgActivityCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetExpBuffRate sets the "expBuffRate" field.
func (_c *RpgActivityCreate) SetExpBuffRate(v float64) *RpgActivityCreate {
	_c.mutation.SetExpBuffRate(v)
	return _c
}

// SetNillableExpBuffRate sets the "expBuffRate" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableExpBuffRate(v *float64) *RpgActivityCreate {
	if v != nil {
		_c.SetExpBuffRate(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *RpgActivityCreate) SetActive(v int) *RpgActivityCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableActive(v *int) *RpgActivityCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetEffectJson sets the "effectJson" field.
func (_c *RpgActivityCreate) SetEffectJson(v string) *RpgActivityCreate {
	_c.mutation.SetEffectJson(v)
	return _c
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableEffectJson(v *string) *RpgActivityCreate {
	if v != nil {
		_c.SetEffectJson(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RpgActivityCreate) SetDescription(v string) *RpgActivityCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableDescription(v *string) *RpgActivityCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetActivityType sets the "activityType" field.
func (_c *RpgActivityCreate) SetActivityType(v string) *RpgActivityCreate {
	_c.mutation.SetActivityType(v)
	return _c
}

// SetNillableActivityType sets the "activityType" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillableActivityType(v *string) *RpgActivityCreate {
	if v != nil {
		_c.SetActivityType(*v)
	}
	return _c
}

// SetPosterUrl sets the "posterUrl" field.
func (_c *RpgActivityCreate) SetPosterUrl(v string) *RpgActivityCreate {
	_c.mutation.SetPosterUrl(v)
	return _c
}

// SetNillablePosterUrl sets the "posterUrl" field if the given value is not nil.
func (_c *RpgActivityCreate) SetNillablePosterUrl(v *string) *RpgActivityCreate {
	if v != nil {
		_c.SetPosterUrl(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RpgActivityCreate) SetID(v int) *RpgActivityCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RpgActivityMutation object of the builder.
func (_c *RpgActivityCreate) Mutation() *RpgActivityMutation {
	return _c.mutation
}

// Save creates the RpgActivity in the database.
func (_c *RpgActivityCreate) Save(ctx context.Context) (*RpgActivity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RpgActivityCreate) SaveX(ctx context.Context) *RpgActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpgActivityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpgActivityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RpgActivityCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := rpgactivity.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := rpgactivity.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := rpgactivity.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := rpgactivity.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ExpBuffRate(); !ok {
		v := rpgactivity.DefaultExpBuffRate
		_c.mutation.SetExpBuffRate(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := rpgactivity.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := rpgactivity.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.ActivityType(); !ok {
		v := rpgactivity.DefaultActivityType
		_c.mutation.SetActivityType(v)
	}
	if _, ok := _c.mutation.PosterUrl(); !ok {
		v := rpgactivity.DefaultPosterUrl
		_c.mutation.SetPosterUrl(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RpgActivityCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "RpgActivity.createTime"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "RpgActivity.updateTime"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "isDelete", err: errors.New(`ent: missing required field "RpgActivity.isDelete"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RpgActivity.version"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "RpgActivity.code"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RpgActivity.name"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "startTime", err: errors.New(`ent: missing required field "RpgActivity.startTime"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "endTime", err: errors.New(`ent: missing required field "RpgActivity.endTime"`)}
	}
	if _, ok := _c.mutation.ExpBuffRate(); !ok {
		return &ValidationError{Name: "expBuffRate", err: errors.New(`ent: missing required field "RpgActivity.expBuffRate"`)}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "RpgActivity.active"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "RpgActivity.description"`)}
	}
	if _, ok := _c.mutation.ActivityType(); !ok {
		return &ValidationError{Name: "activityType", err: errors.New(`ent: missing required field "RpgActivity.activityType"`)}
	}
	if _, ok := _c.mutation.PosterUrl(); !ok {
		return &ValidationError{Name: "posterUrl", err: errors.New(`ent: missing required field "RpgActivity.posterUrl"`)}
	}
	return nil
}

func (_c *RpgActivityCreate) sqlSave(ctx context.Context) (*RpgActivity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RpgActivityCreate) createSpec() (*RpgActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &RpgActivity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rpgactivity.Table, sqlgraph.NewFieldSpec(rpgactivity.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(rpgactivity.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(rpgactivity.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(rpgactivity.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(rpgactivity.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(rpgactivity.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rpgactivity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(rpgactivity.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(rpgactivity.FieldEndTime, field.TypeTime, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.ExpBuffRate(); ok {
		_spec.SetField(rpgactivity.FieldExpBuffRate, field.TypeFloat64, value)
		_node.ExpBuffRate = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(rpgactivity.FieldActive, field.TypeInt, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.EffectJson(); ok {
		_spec.SetField(rpgactivity.FieldEffectJson, field.TypeString, value)
		_node.EffectJson = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rpgactivity.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ActivityType(); ok {
		_spec.SetField(rpgactivity.FieldActivityType, field.TypeString, value)
		_node.ActivityType = value
	}
	if value, ok := _c.mutation.PosterUrl(); ok {
		_spec.SetField(rpgactivity.FieldPosterUrl, field.TypeString, value)
		_node.PosterUrl = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgActivity.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgActivityUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RpgActivityCreate) OnConflict(opts ...sql.ConflictOption) *RpgActivityUpsertOne {
	_c.conflict = opts
	return &RpgActivityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RpgActivityCreate) OnConflictColumns(columns ...string) *RpgActivityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RpgActivityUpsertOne{
		create: _c,
	}
}

type (
	// RpgActivityUpsertOne is the builder for "upsert"-ing
	//  one RpgActivity node.
	RpgActivityUpsertOne struct {
		create *RpgActivityCreate
	}

	// RpgActivityUpsert is the "OnConflict" setter.
	RpgActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "updateTime" field.
func (u *RpgActivityUpsert) SetUpdateTime(v time.Time) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateUpdateTime() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldUpdateTime)
	return u
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgActivityUpsert) SetIsDelete(v bool) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldIsDelete, v)
	return u
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateIsDelete() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldIsDelete)
	return u
}

// SetVersion sets the "version" field.
func (u *RpgActivityUpsert) SetVersion(v int) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateVersion() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *RpgActivityUpsert) AddVersion(v int) *RpgActivityUpsert {
	u.Add(rpgactivity.FieldVersion, v)
	return u
}

// SetCode sets the "code" field.
func (u *RpgActivityUpsert) SetCode(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateCode() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *RpgActivityUpsert) SetName(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateName() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldName)
	return u
}

// SetStartTime sets the "startTime" field.
func (u *RpgActivityUpsert) SetStartTime(v time.Time) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateStartTime() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldStartTime)
	return u
}

// SetEndTime sets the "endTime" field.
func (u *RpgActivityUpsert) SetEndTime(v time.Time) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateEndTime() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldEndTime)
	return u
}

// SetExpBuffRate sets the "expBuffRate" field.
func (u *RpgActivityUpsert) SetExpBuffRate(v float64) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldExpBuffRate, v)
	return u
}

// UpdateExpBuffRate sets the "expBuffRate" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateExpBuffRate() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldExpBuffRate)
	return u
}

// AddExpBuffRate adds v to the "expBuffRate" field.
func (u *RpgActivityUpsert) AddExpBuffRate(v float64) *RpgActivityUpsert {
	u.Add(rpgactivity.FieldExpBuffRate, v)
	return u
}

// SetActive sets the "active" field.
func (u *RpgActivityUpsert) SetActive(v int) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldActive, v)
	return u
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateActive() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldActive)
	return u
}

// AddActive adds v to the "active" field.
func (u *RpgActivityUpsert) AddActive(v int) *RpgActivityUpsert {
	u.Add(rpgactivity.FieldActive, v)
	return u
}

// SetEffectJson sets the "effectJson" field.
func (u *RpgActivityUpsert) SetEffectJson(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldEffectJson, v)
	return u
}

// UpdateEffectJson sets the "effectJson" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateEffectJson() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldEffectJson)
	return u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (u *RpgActivityUpsert) ClearEffectJson() *RpgActivityUpsert {
	u.SetNull(rpgactivity.FieldEffectJson)
	return u
}

// SetDescription sets the "description" field.
func (u *RpgActivityUpsert) SetDescription(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateDescription() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldDescription)
	return u
}

// SetActivityType sets the "activityType" field.
func (u *RpgActivityUpsert) SetActivityType(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldActivityType, v)
	return u
}

// UpdateActivityType sets the "activityType" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdateActivityType() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldActivityType)
	return u
}

// SetPosterUrl sets the "posterUrl" field.
func (u *RpgActivityUpsert) SetPosterUrl(v string) *RpgActivityUpsert {
	u.Set(rpgactivity.FieldPosterUrl, v)
	return u
}

// UpdatePosterUrl sets the "posterUrl" field to the value that was provided on create.
func (u *RpgActivityUpsert) UpdatePosterUrl() *RpgActivityUpsert {
	u.SetExcluded(rpgactivity.FieldPosterUrl)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgActivityUpsertOne) UpdateNewValues() *RpgActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rpgactivity.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(rpgactivity.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RpgActivityUpsertOne) Ignore() *RpgActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgActivityUpsertOne) DoNothing() *RpgActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgActivityCreate.OnConflict
// documentation for more info.
func (u *RpgActivityUpsertOne) Update(set func(*RpgActivityUpsert)) *RpgActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgActivityUpsertOne) SetUpdateTime(v time.Time) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateUpdateTime() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgActivityUpsertOne) SetIsDelete(v bool) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateIsDelete() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *RpgActivityUpsertOne) SetVersion(v int) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RpgActivityUpsertOne) AddVersion(v int) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateVersion() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateVersion()
	})
}

// SetCode sets the "code" field.
func (u *RpgActivityUpsertOne) SetCode(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateCode() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *RpgActivityUpsertOne) SetName(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateName() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateName()
	})
}

// SetStartTime sets the "startTime" field.
func (u *RpgActivityUpsertOne) SetStartTime(v time.Time) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateStartTime() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "endTime" field.
func (u *RpgActivityUpsertOne) SetEndTime(v time.Time) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateEndTime() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateEndTime()
	})
}

// SetExpBuffRate sets the "expBuffRate" field.
func (u *RpgActivityUpsertOne) SetExpBuffRate(v float64) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetExpBuffRate(v)
	})
}

// AddExpBuffRate adds v to the "expBuffRate" field.
func (u *RpgActivityUpsertOne) AddExpBuffRate(v float64) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddExpBuffRate(v)
	})
}

// UpdateExpBuffRate sets the "expBuffRate" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateExpBuffRate() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateExpBuffRate()
	})
}

// SetActive sets the "active" field.
func (u *RpgActivityUpsertOne) SetActive(v int) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetActive(v)
	})
}

// AddActive adds v to the "active" field.
func (u *RpgActivityUpsertOne) AddActive(v int) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateActive() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateActive()
	})
}

// SetEffectJson sets the "effectJson" field.
func (u *RpgActivityUpsertOne) SetEffectJson(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetEffectJson(v)
	})
}

// UpdateEffectJson sets the "effectJson" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateEffectJson() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateEffectJson()
	})
}

// ClearEffectJson clears the value of the "effectJson" field.
func (u *RpgActivityUpsertOne) ClearEffectJson() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.ClearEffectJson()
	})
}

// SetDescription sets the "description" field.
func (u *RpgActivityUpsertOne) SetDescription(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateDescription() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateDescription()
	})
}

// SetActivityType sets the "activityType" field.
func (u *RpgActivityUpsertOne) SetActivityType(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetActivityType(v)
	})
}

// UpdateActivityType sets the "activityType" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdateActivityType() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateActivityType()
	})
}

// SetPosterUrl sets the "posterUrl" field.
func (u *RpgActivityUpsertOne) SetPosterUrl(v string) *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetPosterUrl(v)
	})
}

// UpdatePosterUrl sets the "posterUrl" field to the value that was provided on create.
func (u *RpgActivityUpsertOne) UpdatePosterUrl() *RpgActivityUpsertOne {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdatePosterUrl()
	})
}

// Exec executes the query.
func (u *RpgActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RpgActivityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RpgActivityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RpgActivityCreateBulk is the builder for creating many RpgActivity entities in bulk.
type RpgActivityCreateBulk struct {
	config
	err      error
	builders []*RpgActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the RpgActivity entities in the database.
func (_c *RpgActivityCreateBulk) Save(ctx context.Context) ([]*RpgActivity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RpgActivity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RpgActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RpgActivityCreateBulk) SaveX(ctx context.Context) []*RpgActivity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpgActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpgActivityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgActivityUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RpgActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *RpgActivityUpsertBulk {
	_c.conflict = opts
	return &RpgActivityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RpgActivityCreateBulk) OnConflictColumns(columns ...string) *RpgActivityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RpgActivityUpsertBulk{
		create: _c,
	}
}

// RpgActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of RpgActivity nodes.
type RpgActivityUpsertBulk struct {
	create *RpgActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgActivityUpsertBulk) UpdateNewValues() *RpgActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rpgactivity.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(rpgactivity.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RpgActivityUpsertBulk) Ignore() *RpgActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgActivityUpsertBulk) DoNothing() *RpgActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgActivityCreateBulk.OnConflict
// documentation for more info.
func (u *RpgActivityUpsertBulk) Update(set func(*RpgActivityUpsert)) *RpgActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgActivityUpsertBulk) SetUpdateTime(v time.Time) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateUpdateTime() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgActivityUpsertBulk) SetIsDelete(v bool) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateIsDelete() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *RpgActivityUpsertBulk) SetVersion(v int) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RpgActivityUpsertBulk) AddVersion(v int) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateVersion() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateVersion()
	})
}

// SetCode sets the "code" field.
func (u *RpgActivityUpsertBulk) SetCode(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateCode() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *RpgActivityUpsertBulk) SetName(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateName() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateName()
	})
}

// SetStartTime sets the "startTime" field.
func (u *RpgActivityUpsertBulk) SetStartTime(v time.Time) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateStartTime() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "endTime" field.
func (u *RpgActivityUpsertBulk) SetEndTime(v time.Time) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateEndTime() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateEndTime()
	})
}

// SetExpBuffRate sets the "expBuffRate" field.
func (u *RpgActivityUpsertBulk) SetExpBuffRate(v float64) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetExpBuffRate(v)
	})
}

// AddExpBuffRate adds v to the "expBuffRate" field.
func (u *RpgActivityUpsertBulk) AddExpBuffRate(v float64) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddExpBuffRate(v)
	})
}

// UpdateExpBuffRate sets the "expBuffRate" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateExpBuffRate() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateExpBuffRate()
	})
}

// SetActive sets the "active" field.
func (u *RpgActivityUpsertBulk) SetActive(v int) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetActive(v)
	})
}

// AddActive adds v to the "active" field.
func (u *RpgActivityUpsertBulk) AddActive(v int) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.AddActive(v)
	})
}

// UpdateActive sets the "active" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateActive() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateActive()
	})
}

// SetEffectJson sets the "effectJson" field.
func (u *RpgActivityUpsertBulk) SetEffectJson(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetEffectJson(v)
	})
}

// UpdateEffectJson sets the "effectJson" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateEffectJson() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateEffectJson()
	})
}

// ClearEffectJson clears the value of the "effectJson" field.
func (u *RpgActivityUpsertBulk) ClearEffectJson() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.ClearEffectJson()
	})
}

// SetDescription sets the "description" field.
func (u *RpgActivityUpsertBulk) SetDescription(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateDescription() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateDescription()
	})
}

// SetActivityType sets the "activityType" field.
func (u *RpgActivityUpsertBulk) SetActivityType(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetActivityType(v)
	})
}

// UpdateActivityType sets the "activityType" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdateActivityType() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdateActivityType()
	})
}

// SetPosterUrl sets the "posterUrl" field.
func (u *RpgActivityUpsertBulk) SetPosterUrl(v string) *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.SetPosterUrl(v)
	})
}

// UpdatePosterUrl sets the "posterUrl" field to the value that was provided on create.
func (u *RpgActivityUpsertBulk) UpdatePosterUrl() *RpgActivityUpsertBulk {
	return u.Update(func(s *RpgActivityUpsert) {
		s.UpdatePosterUrl()
	})
}

// Exec executes the query.
func (u *RpgActivityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RpgActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
