// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpgarticletip"
)

// RpgArticleTipCreate is the builder for creating a RpgArticleTip entity.
type RpgArticleTipCreate struct {
	config
	mutation *RpgArticleTipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "createTime" field.
func (_c *RpgArticleTipCreate) SetCreateTime(v time.Time) *RpgArticleTipCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (_c *RpgArticleTipCreate) SetNillableCreateTime(v *time.Time) *RpgArticleTipCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "updateTime" field.
func (_c *RpgArticleTipCreate) SetUpdateTime(v time.Time) *RpgArticleTipCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (_c *RpgArticleTipCreate) SetNillableUpdateTime(v *time.Time) *RpgArticleTipCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "isDelete" field.
func (_c *RpgArticleTipCreate) SetIsDelete(v bool) *RpgArticleTipCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_c *RpgArticleTipCreate) SetNillableIsDelete(v *bool) *RpgArticleTipCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *RpgArticleTipCreate) SetVersion(v int) *RpgArticleTipCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *RpgArticleTipCreate) SetNillableVersion(v *int) *RpgArticleTipCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetUID sets the "uid" field.
func (_c *RpgArticleTipCreate) SetUID(v int) *RpgArticleTipCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetArticleId sets the "articleId" field.
func (_c *RpgArticleTipCreate) SetArticleId(v int) *RpgArticleTipCreate {
	_c.mutation.SetArticleId(v)
	return _c
}

// SetAuthorUid sets the "authorUid" field.
func (_c *RpgArticleTipCreate) SetAuthorUid(v int) *RpgArticleTipCreate {
	_c.mutation.SetAuthorUid(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RpgArticleTipCreate) SetAmount(v int) *RpgArticleTipCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RpgArticleTipCreate) SetID(v int) *RpgArticleTipCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RpgArticleTipMutation object of the builder.
func (_c *RpgArticleTipCreate) Mutation() *RpgArticleTipMutation {
	return _c.mutation
}

// Save creates the RpgArticleTip in the database.
func (_c *RpgArticleTipCreate) Save(ctx context.Context) (*RpgArticleTip, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RpgArticleTipCreate) SaveX(ctx context.Context) *RpgArticleTip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpgArticleTipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpgArticleTipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RpgArticleTipCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := rpgarticletip.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := rpgarticletip.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := rpgarticletip.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := rpgarticletip.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RpgArticleTipCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "RpgArticleTip.createTime"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "RpgArticleTip.updateTime"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "isDelete", err: errors.New(`ent: missing required field "RpgArticleTip.isDelete"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RpgArticleTip.version"`)}
	}
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "RpgArticleTip.uid"`)}
	}
	if _, ok := _c.mutation.ArticleId(); !ok {
		return &ValidationError{Name: "articleId", err: errors.New(`ent: missing required field "RpgArticleTip.articleId"`)}
	}
	if _, ok := _c.mutation.AuthorUid(); !ok {
		return &ValidationError{Name: "authorUid", err: errors.New(`ent: missing required field "RpgArticleTip.authorUid"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RpgArticleTip.amount"`)}
	}
	return nil
}

func (_c *RpgArticleTipCreate) sqlSave(ctx context.Context) (*RpgArticleTip, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RpgArticleTipCreate) createSpec() (*RpgArticleTip, *sqlgraph.CreateSpec) {
	var (
		_node = &RpgArticleTip{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rpgarticletip.Table, sqlgraph.NewFieldSpec(rpgarticletip.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(rpgarticletip.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(rpgarticletip.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(rpgarticletip.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(rpgarticletip.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(rpgarticletip.FieldUID, field.TypeInt, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.ArticleId(); ok {
		_spec.SetField(rpgarticletip.FieldArticleId, field.TypeInt, value)
		_node.ArticleId = value
	}
	if value, ok := _c.mutation.AuthorUid(); ok {
		_spec.SetField(rpgarticletip.FieldAuthorUid, field.TypeInt, value)
		_node.AuthorUid = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rpgarticletip.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgArticleTip.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgArticleTipUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RpgArticleTipCreate) OnConflict(opts ...sql.ConflictOption) *RpgArticleTipUpsertOne {
	_c.conflict = opts
	return &RpgArticleTipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RpgArticleTipCreate) OnConflictColumns(columns ...string) *RpgArticleTipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RpgArticleTipUpsertOne{
		create: _c,
	}
}

type (
	// RpgArticleTipUpsertOne is the builder for "upsert"-ing
	//  one RpgArticleTip node.
	RpgArticleTipUpsertOne struct {
		create *RpgArticleTipCreate
	}

	// RpgArticleTipUpsert is the "OnConflict" setter.
	RpgArticleTipUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "updateTime" field.
func (u *RpgArticleTipUpsert) SetUpdateTime(v time.Time) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateUpdateTime() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldUpdateTime)
	return u
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgArticleTipUpsert) SetIsDelete(v bool) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldIsDelete, v)
	return u
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateIsDelete() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldIsDelete)
	return u
}

// SetVersion sets the "version" field.
func (u *RpgArticleTipUpsert) SetVersion(v int) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateVersion() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *RpgArticleTipUpsert) AddVersion(v int) *RpgArticleTipUpsert {
	u.Add(rpgarticletip.FieldVersion, v)
	return u
}

// SetUID sets the "uid" field.
func (u *RpgArticleTipUpsert) SetUID(v int) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldUID, v)
	return u
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateUID() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldUID)
	return u
}

// AddUID adds v to the "uid" field.
func (u *RpgArticleTipUpsert) AddUID(v int) *RpgArticleTipUpsert {
	u.Add(rpgarticletip.FieldUID, v)
	return u
}

// SetArticleId sets the "articleId" field.
func (u *RpgArticleTipUpsert) SetArticleId(v int) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldArticleId, v)
	return u
}

// UpdateArticleId sets the "articleId" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateArticleId() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldArticleId)
	return u
}

// AddArticleId adds v to the "articleId" field.
func (u *RpgArticleTipUpsert) AddArticleId(v int) *RpgArticleTipUpsert {
	u.Add(rpgarticletip.FieldArticleId, v)
	return u
}

// SetAuthorUid sets the "authorUid" field.
func (u *RpgArticleTipUpsert) SetAuthorUid(v int) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldAuthorUid, v)
	return u
}

// UpdateAuthorUid sets the "authorUid" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateAuthorUid() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldAuthorUid)
	return u
}

// AddAuthorUid adds v to the "authorUid" field.
func (u *RpgArticleTipUpsert) AddAuthorUid(v int) *RpgArticleTipUpsert {
	u.Add(rpgarticletip.FieldAuthorUid, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *RpgArticleTipUpsert) SetAmount(v int) *RpgArticleTipUpsert {
	u.Set(rpgarticletip.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RpgArticleTipUpsert) UpdateAmount() *RpgArticleTipUpsert {
	u.SetExcluded(rpgarticletip.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RpgArticleTipUpsert) AddAmount(v int) *RpgArticleTipUpsert {
	u.Add(rpgarticletip.FieldAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgarticletip.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgArticleTipUpsertOne) UpdateNewValues() *RpgArticleTipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rpgarticletip.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(rpgarticletip.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RpgArticleTipUpsertOne) Ignore() *RpgArticleTipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgArticleTipUpsertOne) DoNothing() *RpgArticleTipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgArticleTipCreate.OnConflict
// documentation for more info.
func (u *RpgArticleTipUpsertOne) Update(set func(*RpgArticleTipUpsert)) *RpgArticleTipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgArticleTipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgArticleTipUpsertOne) SetUpdateTime(v time.Time) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateUpdateTime() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgArticleTipUpsertOne) SetIsDelete(v bool) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateIsDelete() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *RpgArticleTipUpsertOne) SetVersion(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RpgArticleTipUpsertOne) AddVersion(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateVersion() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateVersion()
	})
}

// SetUID sets the "uid" field.
func (u *RpgArticleTipUpsertOne) SetUID(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *RpgArticleTipUpsertOne) AddUID(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateUID() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateUID()
	})
}

// SetArticleId sets the "articleId" field.
func (u *RpgArticleTipUpsertOne) SetArticleId(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetArticleId(v)
	})
}

// AddArticleId adds v to the "articleId" field.
func (u *RpgArticleTipUpsertOne) AddArticleId(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddArticleId(v)
	})
}

// UpdateArticleId sets the "articleId" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateArticleId() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateArticleId()
	})
}

// SetAuthorUid sets the "authorUid" field.
func (u *RpgArticleTipUpsertOne) SetAuthorUid(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetAuthorUid(v)
	})
}

// AddAuthorUid adds v to the "authorUid" field.
func (u *RpgArticleTipUpsertOne) AddAuthorUid(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddAuthorUid(v)
	})
}

// UpdateAuthorUid sets the "authorUid" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateAuthorUid() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateAuthorUid()
	})
}

// SetAmount sets the "amount" field.
func (u *RpgArticleTipUpsertOne) SetAmount(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RpgArticleTipUpsertOne) AddAmount(v int) *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RpgArticleTipUpsertOne) UpdateAmount() *RpgArticleTipUpsertOne {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *RpgArticleTipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgArticleTipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgArticleTipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RpgArticleTipUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RpgArticleTipUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RpgArticleTipCreateBulk is the builder for creating many RpgArticleTip entities in bulk.
type RpgArticleTipCreateBulk struct {
	config
	err      error
	builders []*RpgArticleTipCreate
	conflict []sql.ConflictOption
}

// Save creates the RpgArticleTip entities in the database.
func (_c *RpgArticleTipCreateBulk) Save(ctx context.Context) ([]*RpgArticleTip, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RpgArticleTip, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RpgArticleTipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RpgArticleTipCreateBulk) SaveX(ctx context.Context) []*RpgArticleTip {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RpgArticleTipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RpgArticleTipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgArticleTip.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgArticleTipUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *RpgArticleTipCreateBulk) OnConflict(opts ...sql.ConflictOption) *RpgArticleTipUpsertBulk {
	_c.conflict = opts
	return &RpgArticleTipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RpgArticleTipCreateBulk) OnConflictColumns(columns ...string) *RpgArticleTipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RpgArticleTipUpsertBulk{
		create: _c,
	}
}

// RpgArticleTipUpsertBulk is the builder for "upsert"-ing
// a bulk of RpgArticleTip nodes.
type RpgArticleTipUpsertBulk struct {
	create *RpgArticleTipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgarticletip.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgArticleTipUpsertBulk) UpdateNewValues() *RpgArticleTipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rpgarticletip.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(rpgarticletip.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgArticleTip.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RpgArticleTipUpsertBulk) Ignore() *RpgArticleTipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgArticleTipUpsertBulk) DoNothing() *RpgArticleTipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgArticleTipCreateBulk.OnConflict
// documentation for more info.
func (u *RpgArticleTipUpsertBulk) Update(set func(*RpgArticleTipUpsert)) *RpgArticleTipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgArticleTipUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgArticleTipUpsertBulk) SetUpdateTime(v time.Time) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateUpdateTime() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *RpgArticleTipUpsertBulk) SetIsDelete(v bool) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateIsDelete() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *RpgArticleTipUpsertBulk) SetVersion(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RpgArticleTipUpsertBulk) AddVersion(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateVersion() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateVersion()
	})
}

// SetUID sets the "uid" field.
func (u *RpgArticleTipUpsertBulk) SetUID(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *RpgArticleTipUpsertBulk) AddUID(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateUID() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateUID()
	})
}

// SetArticleId sets the "articleId" field.
func (u *RpgArticleTipUpsertBulk) SetArticleId(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetArticleId(v)
	})
}

// AddArticleId adds v to the "articleId" field.
func (u *RpgArticleTipUpsertBulk) AddArticleId(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddArticleId(v)
	})
}

// UpdateArticleId sets the "articleId" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateArticleId() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateArticleId()
	})
}

// SetAuthorUid sets the "authorUid" field.
func (u *RpgArticleTipUpsertBulk) SetAuthorUid(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetAuthorUid(v)
	})
}

// AddAuthorUid adds v to the "authorUid" field.
func (u *RpgArticleTipUpsertBulk) AddAuthorUid(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddAuthorUid(v)
	})
}

// UpdateAuthorUid sets the "authorUid" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateAuthorUid() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateAuthorUid()
	})
}

// SetAmount sets the "amount" field.
func (u *RpgArticleTipUpsertBulk) SetAmount(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RpgArticleTipUpsertBulk) AddAmount(v int) *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RpgArticleTipUpsertBulk) UpdateAmount() *RpgArticleTipUpsertBulk {
	return u.Update(func(s *RpgArticleTipUpsert) {
		s.UpdateAmount()
	})
}

// Exec executes the query.
func (u *RpgArticleTipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RpgArticleTipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgArticleTipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgArticleTipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
