// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpgitemconfig"
)

// RpgItemConfigUpdate is the builder for updating RpgItemConfig entities.
type RpgItemConfigUpdate struct {
	config
	hooks    []Hook
	mutation *RpgItemConfigMutation
}

// Where appends a list predicates to the RpgItemConfigUpdate builder.
func (_u *RpgItemConfigUpdate) Where(ps ...predicate.RpgItemConfig) *RpgItemConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgItemConfigUpdate) SetUpdateTime(v time.Time) *RpgItemConfigUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgItemConfigUpdate) SetIsDelete(v bool) *RpgItemConfigUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableIsDelete(v *bool) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgItemConfigUpdate) SetVersion(v int) *RpgItemConfigUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableVersion(v *int) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgItemConfigUpdate) AddVersion(v int) *RpgItemConfigUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RpgItemConfigUpdate) SetCode(v string) *RpgItemConfigUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableCode(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RpgItemConfigUpdate) SetName(v string) *RpgItemConfigUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableName(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *RpgItemConfigUpdate) SetSort(v int) *RpgItemConfigUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableSort(v *int) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *RpgItemConfigUpdate) AddSort(v int) *RpgItemConfigUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *RpgItemConfigUpdate) SetActive(v int) *RpgItemConfigUpdate {
	_u.mutation.ResetActive()
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableActive(v *int) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddActive adds value to the "active" field.
func (_u *RpgItemConfigUpdate) AddActive(v int) *RpgItemConfigUpdate {
	_u.mutation.AddActive(v)
	return _u
}

// SetIsHidden sets the "isHidden" field.
func (_u *RpgItemConfigUpdate) SetIsHidden(v int) *RpgItemConfigUpdate {
	_u.mutation.ResetIsHidden()
	_u.mutation.SetIsHidden(v)
	return _u
}

// SetNillableIsHidden sets the "isHidden" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableIsHidden(v *int) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetIsHidden(*v)
	}
	return _u
}

// AddIsHidden adds value to the "isHidden" field.
func (_u *RpgItemConfigUpdate) AddIsHidden(v int) *RpgItemConfigUpdate {
	_u.mutation.AddIsHidden(v)
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgItemConfigUpdate) SetEffectJson(v string) *RpgItemConfigUpdate {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableEffectJson(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgItemConfigUpdate) ClearEffectJson() *RpgItemConfigUpdate {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetItemType sets the "itemType" field.
func (_u *RpgItemConfigUpdate) SetItemType(v string) *RpgItemConfigUpdate {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "itemType" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableItemType(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RpgItemConfigUpdate) SetDescription(v string) *RpgItemConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableDescription(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *RpgItemConfigUpdate) SetCategory(v string) *RpgItemConfigUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableCategory(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *RpgItemConfigUpdate) SetIcon(v string) *RpgItemConfigUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableIcon(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RpgItemConfigUpdate) SetRarity(v string) *RpgItemConfigUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RpgItemConfigUpdate) SetNillableRarity(v *string) *RpgItemConfigUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// Mutation returns the RpgItemConfigMutation object of the builder.
func (_u *RpgItemConfigUpdate) Mutation() *RpgItemConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RpgItemConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgItemConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RpgItemConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgItemConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgItemConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpgitemconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgItemConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpgitemconfig.Table, rpgitemconfig.Columns, sqlgraph.NewFieldSpec(rpgitemconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpgitemconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpgitemconfig.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpgitemconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpgitemconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rpgitemconfig.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rpgitemconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(rpgitemconfig.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(rpgitemconfig.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(rpgitemconfig.FieldActive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActive(); ok {
		_spec.AddField(rpgitemconfig.FieldActive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHidden(); ok {
		_spec.SetField(rpgitemconfig.FieldIsHidden, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIsHidden(); ok {
		_spec.AddField(rpgitemconfig.FieldIsHidden, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpgitemconfig.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpgitemconfig.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(rpgitemconfig.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rpgitemconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(rpgitemconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(rpgitemconfig.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rpgitemconfig.FieldRarity, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpgitemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RpgItemConfigUpdateOne is the builder for updating a single RpgItemConfig entity.
type RpgItemConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RpgItemConfigMutation
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgItemConfigUpdateOne) SetUpdateTime(v time.Time) *RpgItemConfigUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgItemConfigUpdateOne) SetIsDelete(v bool) *RpgItemConfigUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableIsDelete(v *bool) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgItemConfigUpdateOne) SetVersion(v int) *RpgItemConfigUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableVersion(v *int) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgItemConfigUpdateOne) AddVersion(v int) *RpgItemConfigUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *RpgItemConfigUpdateOne) SetCode(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableCode(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RpgItemConfigUpdateOne) SetName(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableName(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *RpgItemConfigUpdateOne) SetSort(v int) *RpgItemConfigUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableSort(v *int) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *RpgItemConfigUpdateOne) AddSort(v int) *RpgItemConfigUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *RpgItemConfigUpdateOne) SetActive(v int) *RpgItemConfigUpdateOne {
	_u.mutation.ResetActive()
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableActive(v *int) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddActive adds value to the "active" field.
func (_u *RpgItemConfigUpdateOne) AddActive(v int) *RpgItemConfigUpdateOne {
	_u.mutation.AddActive(v)
	return _u
}

// SetIsHidden sets the "isHidden" field.
func (_u *RpgItemConfigUpdateOne) SetIsHidden(v int) *RpgItemConfigUpdateOne {
	_u.mutation.ResetIsHidden()
	_u.mutation.SetIsHidden(v)
	return _u
}

// SetNillableIsHidden sets the "isHidden" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableIsHidden(v *int) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetIsHidden(*v)
	}
	return _u
}

// AddIsHidden adds value to the "isHidden" field.
func (_u *RpgItemConfigUpdateOne) AddIsHidden(v int) *RpgItemConfigUpdateOne {
	_u.mutation.AddIsHidden(v)
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgItemConfigUpdateOne) SetEffectJson(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableEffectJson(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgItemConfigUpdateOne) ClearEffectJson() *RpgItemConfigUpdateOne {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetItemType sets the "itemType" field.
func (_u *RpgItemConfigUpdateOne) SetItemType(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetItemType(v)
	return _u
}

// SetNillableItemType sets the "itemType" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableItemType(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetItemType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RpgItemConfigUpdateOne) SetDescription(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableDescription(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *RpgItemConfigUpdateOne) SetCategory(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableCategory(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetIcon sets the "icon" field.
func (_u *RpgItemConfigUpdateOne) SetIcon(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableIcon(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RpgItemConfigUpdateOne) SetRarity(v string) *RpgItemConfigUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RpgItemConfigUpdateOne) SetNillableRarity(v *string) *RpgItemConfigUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// Mutation returns the RpgItemConfigMutation object of the builder.
func (_u *RpgItemConfigUpdateOne) Mutation() *RpgItemConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the RpgItemConfigUpdate builder.
func (_u *RpgItemConfigUpdateOne) Where(ps ...predicate.RpgItemConfig) *RpgItemConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RpgItemConfigUpdateOne) Select(field string, fields ...string) *RpgItemConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RpgItemConfig entity.
func (_u *RpgItemConfigUpdateOne) Save(ctx context.Context) (*RpgItemConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgItemConfigUpdateOne) SaveX(ctx context.Context) *RpgItemConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RpgItemConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgItemConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgItemConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpgitemconfig.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgItemConfigUpdateOne) sqlSave(ctx context.Context) (_node *RpgItemConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpgitemconfig.Table, rpgitemconfig.Columns, sqlgraph.NewFieldSpec(rpgitemconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RpgItemConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rpgitemconfig.FieldID)
		for _, f := range fields {
			if !rpgitemconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rpgitemconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpgitemconfig.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpgitemconfig.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpgitemconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpgitemconfig.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(rpgitemconfig.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rpgitemconfig.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(rpgitemconfig.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(rpgitemconfig.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(rpgitemconfig.FieldActive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActive(); ok {
		_spec.AddField(rpgitemconfig.FieldActive, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHidden(); ok {
		_spec.SetField(rpgitemconfig.FieldIsHidden, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIsHidden(); ok {
		_spec.AddField(rpgitemconfig.FieldIsHidden, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpgitemconfig.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpgitemconfig.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.ItemType(); ok {
		_spec.SetField(rpgitemconfig.FieldItemType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rpgitemconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(rpgitemconfig.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(rpgitemconfig.FieldIcon, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rpgitemconfig.FieldRarity, field.TypeString, value)
	}
	_node = &RpgItemConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpgitemconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
