// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpgquest"
)

// RpgQuestDelete is the builder for deleting a RpgQuest entity.
type RpgQuestDelete struct {
	config
	hooks    []Hook
	mutation *RpgQuestMutation
}

// Where appends a list predicates to the RpgQuestDelete builder.
func (rqd *RpgQuestDelete) Where(ps ...predicate.RpgQuest) *RpgQuestDelete {
	rqd.mutation.Where(ps...)
	return rqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rqd *RpgQuestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rqd.sqlExec, rqd.mutation, rqd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rqd *RpgQuestDelete) ExecX(ctx context.Context) int {
	n, err := rqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rqd *RpgQuestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rpgquest.Table, sqlgraph.NewFieldSpec(rpgquest.FieldID, field.TypeInt))
	if ps := rqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rqd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rqd.mutation.done = true
	return affected, err
}

// RpgQuestDeleteOne is the builder for deleting a single RpgQuest entity.
type RpgQuestDeleteOne struct {
	rqd *RpgQuestDelete
}

// Where appends a list predicates to the RpgQuestDelete builder.
func (rqdo *RpgQuestDeleteOne) Where(ps ...predicate.RpgQuest) *RpgQuestDeleteOne {
	rqdo.rqd.mutation.Where(ps...)
	return rqdo
}

// Exec executes the deletion query.
func (rqdo *RpgQuestDeleteOne) Exec(ctx context.Context) error {
	n, err := rqdo.rqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rpgquest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rqdo *RpgQuestDeleteOne) ExecX(ctx context.Context) {
	if err := rqdo.Exec(ctx); err != nil {
		panic(err)
	}
}
