// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpgquest"
)

// RpgQuest is the model entity for the RpgQuest schema.
type RpgQuest struct {
	config `json:"-"`
	// ID of the ent.
	// 自身id
	ID int `json:"id,omitempty"`
	// 任务编码
	Code string `json:"code,omitempty"`
	// 任务名称
	Name string `json:"name,omitempty"`
	// 任务描述
	Description string `json:"description,omitempty"`
	// 类型: daily/weekly
	Type string `json:"type,omitempty"`
	// 目标行为: sign_in/comment/article/like/collect/msgboard
	TargetAction string `json:"targetAction,omitempty"`
	// 目标次数
	TargetCount int `json:"targetCount,omitempty"`
	// 经验奖励
	ExpReward int `json:"expReward,omitempty"`
	// 完成恢复HP
	HpReward int `json:"hpReward,omitempty"`
	// 完成奖励通用货币(钻石)
	CurrencyReward int `json:"currencyReward,omitempty"`
	// 是否启用
	Active int `json:"active,omitempty"`
	// 排序权重
	Sort int `json:"sort,omitempty"`
	// 任务编码
	EffectJson *string `json:"effectJson,omitempty"`
	// daily/bounty/special
	QuestSubtype string `json:"questSubtype,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RpgQuest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rpgquest.FieldID, rpgquest.FieldTargetCount, rpgquest.FieldExpReward, rpgquest.FieldHpReward, rpgquest.FieldCurrencyReward, rpgquest.FieldActive, rpgquest.FieldSort:
			values[i] = new(sql.NullInt64)
		case rpgquest.FieldCode, rpgquest.FieldName, rpgquest.FieldDescription, rpgquest.FieldType, rpgquest.FieldTargetAction, rpgquest.FieldEffectJson, rpgquest.FieldQuestSubtype:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RpgQuest fields.
func (rq *RpgQuest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rpgquest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rq.ID = int(value.Int64)
		case rpgquest.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				rq.Code = value.String
			}
		case rpgquest.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				rq.Name = value.String
			}
		case rpgquest.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				rq.Description = value.String
			}
		case rpgquest.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				rq.Type = value.String
			}
		case rpgquest.FieldTargetAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field targetAction", values[i])
			} else if value.Valid {
				rq.TargetAction = value.String
			}
		case rpgquest.FieldTargetCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field targetCount", values[i])
			} else if value.Valid {
				rq.TargetCount = int(value.Int64)
			}
		case rpgquest.FieldExpReward:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expReward", values[i])
			} else if value.Valid {
				rq.ExpReward = int(value.Int64)
			}
		case rpgquest.FieldHpReward:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hpReward", values[i])
			} else if value.Valid {
				rq.HpReward = int(value.Int64)
			}
		case rpgquest.FieldCurrencyReward:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field currencyReward", values[i])
			} else if value.Valid {
				rq.CurrencyReward = int(value.Int64)
			}
		case rpgquest.FieldActive:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				rq.Active = int(value.Int64)
			}
		case rpgquest.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				rq.Sort = int(value.Int64)
			}
		case rpgquest.FieldEffectJson:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field effectJson", values[i])
			} else if value.Valid {
				rq.EffectJson = new(string)
				*rq.EffectJson = value.String
			}
		case rpgquest.FieldQuestSubtype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field questSubtype", values[i])
			} else if value.Valid {
				rq.QuestSubtype = value.String
			}
		default:
			rq.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RpgQuest.
// This includes values selected through modifiers, order, etc.
func (rq *RpgQuest) Value(name string) (ent.Value, error) {
	return rq.selectValues.Get(name)
}

// Update returns a builder for updating this RpgQuest.
// Note that you need to call RpgQuest.Unwrap() before calling this method if this RpgQuest
// was returned from a transaction, and the transaction was committed or rolled back.
func (rq *RpgQuest) Update() *RpgQuestUpdateOne {
	return NewRpgQuestClient(rq.config).UpdateOne(rq)
}

// Unwrap unwraps the RpgQuest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rq *RpgQuest) Unwrap() *RpgQuest {
	_tx, ok := rq.config.driver.(*txDriver)
	if !ok {
		panic("ent: RpgQuest is not a transactional entity")
	}
	rq.config.driver = _tx.drv
	return rq
}

// String implements the fmt.Stringer.
func (rq *RpgQuest) String() string {
	var builder strings.Builder
	builder.WriteString("RpgQuest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rq.ID))
	builder.WriteString("code=")
	builder.WriteString(rq.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(rq.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(rq.Description)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(rq.Type)
	builder.WriteString(", ")
	builder.WriteString("targetAction=")
	builder.WriteString(rq.TargetAction)
	builder.WriteString(", ")
	builder.WriteString("targetCount=")
	builder.WriteString(fmt.Sprintf("%v", rq.TargetCount))
	builder.WriteString(", ")
	builder.WriteString("expReward=")
	builder.WriteString(fmt.Sprintf("%v", rq.ExpReward))
	builder.WriteString(", ")
	builder.WriteString("hpReward=")
	builder.WriteString(fmt.Sprintf("%v", rq.HpReward))
	builder.WriteString(", ")
	builder.WriteString("currencyReward=")
	builder.WriteString(fmt.Sprintf("%v", rq.CurrencyReward))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", rq.Active))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", rq.Sort))
	builder.WriteString(", ")
	if v := rq.EffectJson; v != nil {
		builder.WriteString("effectJson=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("questSubtype=")
	builder.WriteString(rq.QuestSubtype)
	builder.WriteByte(')')
	return builder.String()
}

// RpgQuests is a parsable slice of RpgQuest.
type RpgQuests []*RpgQuest
