// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpguserlotteryrecord"
)

// RpgUserLotteryRecordUpdate is the builder for updating RpgUserLotteryRecord entities.
type RpgUserLotteryRecordUpdate struct {
	config
	hooks    []Hook
	mutation *RpgUserLotteryRecordMutation
}

// Where appends a list predicates to the RpgUserLotteryRecordUpdate builder.
func (_u *RpgUserLotteryRecordUpdate) Where(ps ...predicate.RpgUserLotteryRecord) *RpgUserLotteryRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgUserLotteryRecordUpdate) SetUpdateTime(v time.Time) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgUserLotteryRecordUpdate) SetIsDelete(v bool) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableIsDelete(v *bool) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgUserLotteryRecordUpdate) SetVersion(v int) *RpgUserLotteryRecordUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableVersion(v *int) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgUserLotteryRecordUpdate) AddVersion(v int) *RpgUserLotteryRecordUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUID sets the "uid" field.
func (_u *RpgUserLotteryRecordUpdate) SetUID(v int) *RpgUserLotteryRecordUpdate {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableUID(v *int) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *RpgUserLotteryRecordUpdate) AddUID(v int) *RpgUserLotteryRecordUpdate {
	_u.mutation.AddUID(v)
	return _u
}

// SetPoolItemCode sets the "poolItemCode" field.
func (_u *RpgUserLotteryRecordUpdate) SetPoolItemCode(v string) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetPoolItemCode(v)
	return _u
}

// SetNillablePoolItemCode sets the "poolItemCode" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillablePoolItemCode(v *string) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetPoolItemCode(*v)
	}
	return _u
}

// SetItemName sets the "itemName" field.
func (_u *RpgUserLotteryRecordUpdate) SetItemName(v string) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "itemName" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableItemName(v *string) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgUserLotteryRecordUpdate) SetEffectJson(v string) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableEffectJson(v *string) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgUserLotteryRecordUpdate) ClearEffectJson() *RpgUserLotteryRecordUpdate {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RpgUserLotteryRecordUpdate) SetRarity(v string) *RpgUserLotteryRecordUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdate) SetNillableRarity(v *string) *RpgUserLotteryRecordUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// Mutation returns the RpgUserLotteryRecordMutation object of the builder.
func (_u *RpgUserLotteryRecordUpdate) Mutation() *RpgUserLotteryRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RpgUserLotteryRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgUserLotteryRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RpgUserLotteryRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgUserLotteryRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgUserLotteryRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpguserlotteryrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgUserLotteryRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpguserlotteryrecord.Table, rpguserlotteryrecord.Columns, sqlgraph.NewFieldSpec(rpguserlotteryrecord.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpguserlotteryrecord.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(rpguserlotteryrecord.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PoolItemCode(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldPoolItemCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldItemName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpguserlotteryrecord.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldRarity, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpguserlotteryrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RpgUserLotteryRecordUpdateOne is the builder for updating a single RpgUserLotteryRecord entity.
type RpgUserLotteryRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RpgUserLotteryRecordMutation
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetUpdateTime(v time.Time) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetIsDelete(v bool) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableIsDelete(v *bool) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetVersion(v int) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableVersion(v *int) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgUserLotteryRecordUpdateOne) AddVersion(v int) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUID sets the "uid" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetUID(v int) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableUID(v *int) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *RpgUserLotteryRecordUpdateOne) AddUID(v int) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.AddUID(v)
	return _u
}

// SetPoolItemCode sets the "poolItemCode" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetPoolItemCode(v string) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetPoolItemCode(v)
	return _u
}

// SetNillablePoolItemCode sets the "poolItemCode" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillablePoolItemCode(v *string) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetPoolItemCode(*v)
	}
	return _u
}

// SetItemName sets the "itemName" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetItemName(v string) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetItemName(v)
	return _u
}

// SetNillableItemName sets the "itemName" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableItemName(v *string) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetItemName(*v)
	}
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetEffectJson(v string) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableEffectJson(v *string) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgUserLotteryRecordUpdateOne) ClearEffectJson() *RpgUserLotteryRecordUpdateOne {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *RpgUserLotteryRecordUpdateOne) SetRarity(v string) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *RpgUserLotteryRecordUpdateOne) SetNillableRarity(v *string) *RpgUserLotteryRecordUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// Mutation returns the RpgUserLotteryRecordMutation object of the builder.
func (_u *RpgUserLotteryRecordUpdateOne) Mutation() *RpgUserLotteryRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the RpgUserLotteryRecordUpdate builder.
func (_u *RpgUserLotteryRecordUpdateOne) Where(ps ...predicate.RpgUserLotteryRecord) *RpgUserLotteryRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RpgUserLotteryRecordUpdateOne) Select(field string, fields ...string) *RpgUserLotteryRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RpgUserLotteryRecord entity.
func (_u *RpgUserLotteryRecordUpdateOne) Save(ctx context.Context) (*RpgUserLotteryRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgUserLotteryRecordUpdateOne) SaveX(ctx context.Context) *RpgUserLotteryRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RpgUserLotteryRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgUserLotteryRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgUserLotteryRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpguserlotteryrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgUserLotteryRecordUpdateOne) sqlSave(ctx context.Context) (_node *RpgUserLotteryRecord, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpguserlotteryrecord.Table, rpguserlotteryrecord.Columns, sqlgraph.NewFieldSpec(rpguserlotteryrecord.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RpgUserLotteryRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rpguserlotteryrecord.FieldID)
		for _, f := range fields {
			if !rpguserlotteryrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rpguserlotteryrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpguserlotteryrecord.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(rpguserlotteryrecord.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PoolItemCode(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldPoolItemCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ItemName(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldItemName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpguserlotteryrecord.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(rpguserlotteryrecord.FieldRarity, field.TypeString, value)
	}
	_node = &RpgUserLotteryRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpguserlotteryrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
