// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpguserquestprogress"
)

// RpgUserQuestProgressDelete is the builder for deleting a RpgUserQuestProgress entity.
type RpgUserQuestProgressDelete struct {
	config
	hooks    []Hook
	mutation *RpgUserQuestProgressMutation
}

// Where appends a list predicates to the RpgUserQuestProgressDelete builder.
func (_d *RpgUserQuestProgressDelete) Where(ps ...predicate.RpgUserQuestProgress) *RpgUserQuestProgressDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RpgUserQuestProgressDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RpgUserQuestProgressDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RpgUserQuestProgressDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rpguserquestprogress.Table, sqlgraph.NewFieldSpec(rpguserquestprogress.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RpgUserQuestProgressDeleteOne is the builder for deleting a single RpgUserQuestProgress entity.
type RpgUserQuestProgressDeleteOne struct {
	_d *RpgUserQuestProgressDelete
}

// Where appends a list predicates to the RpgUserQuestProgressDelete builder.
func (_d *RpgUserQuestProgressDeleteOne) Where(ps ...predicate.RpgUserQuestProgress) *RpgUserQuestProgressDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RpgUserQuestProgressDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rpguserquestprogress.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RpgUserQuestProgressDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
