// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/rpguserpet"
)

// RpgUserPetUpdate is the builder for updating RpgUserPet entities.
type RpgUserPetUpdate struct {
	config
	hooks    []Hook
	mutation *RpgUserPetMutation
}

// Where appends a list predicates to the RpgUserPetUpdate builder.
func (_u *RpgUserPetUpdate) Where(ps ...predicate.RpgUserPet) *RpgUserPetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgUserPetUpdate) SetUpdateTime(v time.Time) *RpgUserPetUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgUserPetUpdate) SetIsDelete(v bool) *RpgUserPetUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableIsDelete(v *bool) *RpgUserPetUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgUserPetUpdate) SetVersion(v int) *RpgUserPetUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableVersion(v *int) *RpgUserPetUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgUserPetUpdate) AddVersion(v int) *RpgUserPetUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUID sets the "uid" field.
func (_u *RpgUserPetUpdate) SetUID(v int) *RpgUserPetUpdate {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableUID(v *int) *RpgUserPetUpdate {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *RpgUserPetUpdate) AddUID(v int) *RpgUserPetUpdate {
	_u.mutation.AddUID(v)
	return _u
}

// SetPetCode sets the "petCode" field.
func (_u *RpgUserPetUpdate) SetPetCode(v string) *RpgUserPetUpdate {
	_u.mutation.SetPetCode(v)
	return _u
}

// SetNillablePetCode sets the "petCode" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillablePetCode(v *string) *RpgUserPetUpdate {
	if v != nil {
		_u.SetPetCode(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *RpgUserPetUpdate) SetLevel(v int) *RpgUserPetUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableLevel(v *int) *RpgUserPetUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *RpgUserPetUpdate) AddLevel(v int) *RpgUserPetUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *RpgUserPetUpdate) SetExp(v int) *RpgUserPetUpdate {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableExp(v *int) *RpgUserPetUpdate {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *RpgUserPetUpdate) AddExp(v int) *RpgUserPetUpdate {
	_u.mutation.AddExp(v)
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgUserPetUpdate) SetEffectJson(v string) *RpgUserPetUpdate {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableEffectJson(v *string) *RpgUserPetUpdate {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgUserPetUpdate) ClearEffectJson() *RpgUserPetUpdate {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *RpgUserPetUpdate) SetNickname(v string) *RpgUserPetUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *RpgUserPetUpdate) SetNillableNickname(v *string) *RpgUserPetUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// Mutation returns the RpgUserPetMutation object of the builder.
func (_u *RpgUserPetUpdate) Mutation() *RpgUserPetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RpgUserPetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgUserPetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RpgUserPetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgUserPetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgUserPetUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpguserpet.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgUserPetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpguserpet.Table, rpguserpet.Columns, sqlgraph.NewFieldSpec(rpguserpet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpguserpet.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpguserpet.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpguserpet.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpguserpet.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(rpguserpet.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(rpguserpet.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PetCode(); ok {
		_spec.SetField(rpguserpet.FieldPetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(rpguserpet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(rpguserpet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(rpguserpet.FieldExp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(rpguserpet.FieldExp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpguserpet.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpguserpet.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(rpguserpet.FieldNickname, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpguserpet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RpgUserPetUpdateOne is the builder for updating a single RpgUserPet entity.
type RpgUserPetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RpgUserPetMutation
}

// SetUpdateTime sets the "updateTime" field.
func (_u *RpgUserPetUpdateOne) SetUpdateTime(v time.Time) *RpgUserPetUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *RpgUserPetUpdateOne) SetIsDelete(v bool) *RpgUserPetUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableIsDelete(v *bool) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *RpgUserPetUpdateOne) SetVersion(v int) *RpgUserPetUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableVersion(v *int) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *RpgUserPetUpdateOne) AddVersion(v int) *RpgUserPetUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUID sets the "uid" field.
func (_u *RpgUserPetUpdateOne) SetUID(v int) *RpgUserPetUpdateOne {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableUID(v *int) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *RpgUserPetUpdateOne) AddUID(v int) *RpgUserPetUpdateOne {
	_u.mutation.AddUID(v)
	return _u
}

// SetPetCode sets the "petCode" field.
func (_u *RpgUserPetUpdateOne) SetPetCode(v string) *RpgUserPetUpdateOne {
	_u.mutation.SetPetCode(v)
	return _u
}

// SetNillablePetCode sets the "petCode" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillablePetCode(v *string) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetPetCode(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *RpgUserPetUpdateOne) SetLevel(v int) *RpgUserPetUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableLevel(v *int) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *RpgUserPetUpdateOne) AddLevel(v int) *RpgUserPetUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetExp sets the "exp" field.
func (_u *RpgUserPetUpdateOne) SetExp(v int) *RpgUserPetUpdateOne {
	_u.mutation.ResetExp()
	_u.mutation.SetExp(v)
	return _u
}

// SetNillableExp sets the "exp" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableExp(v *int) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetExp(*v)
	}
	return _u
}

// AddExp adds value to the "exp" field.
func (_u *RpgUserPetUpdateOne) AddExp(v int) *RpgUserPetUpdateOne {
	_u.mutation.AddExp(v)
	return _u
}

// SetEffectJson sets the "effectJson" field.
func (_u *RpgUserPetUpdateOne) SetEffectJson(v string) *RpgUserPetUpdateOne {
	_u.mutation.SetEffectJson(v)
	return _u
}

// SetNillableEffectJson sets the "effectJson" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableEffectJson(v *string) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetEffectJson(*v)
	}
	return _u
}

// ClearEffectJson clears the value of the "effectJson" field.
func (_u *RpgUserPetUpdateOne) ClearEffectJson() *RpgUserPetUpdateOne {
	_u.mutation.ClearEffectJson()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *RpgUserPetUpdateOne) SetNickname(v string) *RpgUserPetUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *RpgUserPetUpdateOne) SetNillableNickname(v *string) *RpgUserPetUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// Mutation returns the RpgUserPetMutation object of the builder.
func (_u *RpgUserPetUpdateOne) Mutation() *RpgUserPetMutation {
	return _u.mutation
}

// Where appends a list predicates to the RpgUserPetUpdate builder.
func (_u *RpgUserPetUpdateOne) Where(ps ...predicate.RpgUserPet) *RpgUserPetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RpgUserPetUpdateOne) Select(field string, fields ...string) *RpgUserPetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RpgUserPet entity.
func (_u *RpgUserPetUpdateOne) Save(ctx context.Context) (*RpgUserPet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RpgUserPetUpdateOne) SaveX(ctx context.Context) *RpgUserPet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RpgUserPetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RpgUserPetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RpgUserPetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := rpguserpet.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *RpgUserPetUpdateOne) sqlSave(ctx context.Context) (_node *RpgUserPet, err error) {
	_spec := sqlgraph.NewUpdateSpec(rpguserpet.Table, rpguserpet.Columns, sqlgraph.NewFieldSpec(rpguserpet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RpgUserPet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rpguserpet.FieldID)
		for _, f := range fields {
			if !rpguserpet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rpguserpet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(rpguserpet.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(rpguserpet.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(rpguserpet.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(rpguserpet.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(rpguserpet.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(rpguserpet.FieldUID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PetCode(); ok {
		_spec.SetField(rpguserpet.FieldPetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(rpguserpet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(rpguserpet.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Exp(); ok {
		_spec.SetField(rpguserpet.FieldExp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExp(); ok {
		_spec.AddField(rpguserpet.FieldExp, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EffectJson(); ok {
		_spec.SetField(rpguserpet.FieldEffectJson, field.TypeString, value)
	}
	if _u.mutation.EffectJsonCleared() {
		_spec.ClearField(rpguserpet.FieldEffectJson, field.TypeString)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(rpguserpet.FieldNickname, field.TypeString, value)
	}
	_node = &RpgUserPet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rpguserpet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
