// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/scheduledtasklog"
)

// ScheduledTaskLogCreate is the builder for creating a ScheduledTaskLog entity.
type ScheduledTaskLogCreate struct {
	config
	mutation *ScheduledTaskLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "createTime" field.
func (_c *ScheduledTaskLogCreate) SetCreateTime(v time.Time) *ScheduledTaskLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableCreateTime(v *time.Time) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "updateTime" field.
func (_c *ScheduledTaskLogCreate) SetUpdateTime(v time.Time) *ScheduledTaskLogCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableUpdateTime(v *time.Time) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "isDelete" field.
func (_c *ScheduledTaskLogCreate) SetIsDelete(v bool) *ScheduledTaskLogCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableIsDelete(v *bool) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ScheduledTaskLogCreate) SetVersion(v int) *ScheduledTaskLogCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableVersion(v *int) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetTaskName sets the "taskName" field.
func (_c *ScheduledTaskLogCreate) SetTaskName(v string) *ScheduledTaskLogCreate {
	_c.mutation.SetTaskName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ScheduledTaskLogCreate) SetStatus(v string) *ScheduledTaskLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStartTime sets the "startTime" field.
func (_c *ScheduledTaskLogCreate) SetStartTime(v time.Time) *ScheduledTaskLogCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "endTime" field.
func (_c *ScheduledTaskLogCreate) SetEndTime(v time.Time) *ScheduledTaskLogCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "endTime" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableEndTime(v *time.Time) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *ScheduledTaskLogCreate) SetResult(v string) *ScheduledTaskLogCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableResult(v *string) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetResult(*v)
	}
	return _c
}

// SetErrorMessage sets the "errorMessage" field.
func (_c *ScheduledTaskLogCreate) SetErrorMessage(v string) *ScheduledTaskLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "errorMessage" field if the given value is not nil.
func (_c *ScheduledTaskLogCreate) SetNillableErrorMessage(v *string) *ScheduledTaskLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScheduledTaskLogCreate) SetID(v int) *ScheduledTaskLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScheduledTaskLogMutation object of the builder.
func (_c *ScheduledTaskLogCreate) Mutation() *ScheduledTaskLogMutation {
	return _c.mutation
}

// Save creates the ScheduledTaskLog in the database.
func (_c *ScheduledTaskLogCreate) Save(ctx context.Context) (*ScheduledTaskLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScheduledTaskLogCreate) SaveX(ctx context.Context) *ScheduledTaskLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledTaskLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledTaskLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScheduledTaskLogCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := scheduledtasklog.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := scheduledtasklog.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := scheduledtasklog.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := scheduledtasklog.DefaultVersion
		_c.mutation.SetVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScheduledTaskLogCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "ScheduledTaskLog.createTime"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "ScheduledTaskLog.updateTime"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "isDelete", err: errors.New(`ent: missing required field "ScheduledTaskLog.isDelete"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ScheduledTaskLog.version"`)}
	}
	if _, ok := _c.mutation.TaskName(); !ok {
		return &ValidationError{Name: "taskName", err: errors.New(`ent: missing required field "ScheduledTaskLog.taskName"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ScheduledTaskLog.status"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "startTime", err: errors.New(`ent: missing required field "ScheduledTaskLog.startTime"`)}
	}
	return nil
}

func (_c *ScheduledTaskLogCreate) sqlSave(ctx context.Context) (*ScheduledTaskLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScheduledTaskLogCreate) createSpec() (*ScheduledTaskLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ScheduledTaskLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scheduledtasklog.Table, sqlgraph.NewFieldSpec(scheduledtasklog.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(scheduledtasklog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(scheduledtasklog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(scheduledtasklog.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(scheduledtasklog.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.TaskName(); ok {
		_spec.SetField(scheduledtasklog.FieldTaskName, field.TypeString, value)
		_node.TaskName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(scheduledtasklog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(scheduledtasklog.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(scheduledtasklog.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(scheduledtasklog.FieldResult, field.TypeString, value)
		_node.Result = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(scheduledtasklog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScheduledTaskLog.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduledTaskLogUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduledTaskLogCreate) OnConflict(opts ...sql.ConflictOption) *ScheduledTaskLogUpsertOne {
	_c.conflict = opts
	return &ScheduledTaskLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduledTaskLogCreate) OnConflictColumns(columns ...string) *ScheduledTaskLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduledTaskLogUpsertOne{
		create: _c,
	}
}

type (
	// ScheduledTaskLogUpsertOne is the builder for "upsert"-ing
	//  one ScheduledTaskLog node.
	ScheduledTaskLogUpsertOne struct {
		create *ScheduledTaskLogCreate
	}

	// ScheduledTaskLogUpsert is the "OnConflict" setter.
	ScheduledTaskLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "updateTime" field.
func (u *ScheduledTaskLogUpsert) SetUpdateTime(v time.Time) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateUpdateTime() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldUpdateTime)
	return u
}

// SetIsDelete sets the "isDelete" field.
func (u *ScheduledTaskLogUpsert) SetIsDelete(v bool) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldIsDelete, v)
	return u
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateIsDelete() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldIsDelete)
	return u
}

// SetVersion sets the "version" field.
func (u *ScheduledTaskLogUpsert) SetVersion(v int) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateVersion() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ScheduledTaskLogUpsert) AddVersion(v int) *ScheduledTaskLogUpsert {
	u.Add(scheduledtasklog.FieldVersion, v)
	return u
}

// SetTaskName sets the "taskName" field.
func (u *ScheduledTaskLogUpsert) SetTaskName(v string) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldTaskName, v)
	return u
}

// UpdateTaskName sets the "taskName" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateTaskName() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldTaskName)
	return u
}

// SetStatus sets the "status" field.
func (u *ScheduledTaskLogUpsert) SetStatus(v string) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateStatus() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldStatus)
	return u
}

// SetStartTime sets the "startTime" field.
func (u *ScheduledTaskLogUpsert) SetStartTime(v time.Time) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateStartTime() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldStartTime)
	return u
}

// SetEndTime sets the "endTime" field.
func (u *ScheduledTaskLogUpsert) SetEndTime(v time.Time) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateEndTime() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "endTime" field.
func (u *ScheduledTaskLogUpsert) ClearEndTime() *ScheduledTaskLogUpsert {
	u.SetNull(scheduledtasklog.FieldEndTime)
	return u
}

// SetResult sets the "result" field.
func (u *ScheduledTaskLogUpsert) SetResult(v string) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateResult() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldResult)
	return u
}

// ClearResult clears the value of the "result" field.
func (u *ScheduledTaskLogUpsert) ClearResult() *ScheduledTaskLogUpsert {
	u.SetNull(scheduledtasklog.FieldResult)
	return u
}

// SetErrorMessage sets the "errorMessage" field.
func (u *ScheduledTaskLogUpsert) SetErrorMessage(v string) *ScheduledTaskLogUpsert {
	u.Set(scheduledtasklog.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "errorMessage" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsert) UpdateErrorMessage() *ScheduledTaskLogUpsert {
	u.SetExcluded(scheduledtasklog.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "errorMessage" field.
func (u *ScheduledTaskLogUpsert) ClearErrorMessage() *ScheduledTaskLogUpsert {
	u.SetNull(scheduledtasklog.FieldErrorMessage)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scheduledtasklog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduledTaskLogUpsertOne) UpdateNewValues() *ScheduledTaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(scheduledtasklog.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(scheduledtasklog.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScheduledTaskLogUpsertOne) Ignore() *ScheduledTaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduledTaskLogUpsertOne) DoNothing() *ScheduledTaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduledTaskLogCreate.OnConflict
// documentation for more info.
func (u *ScheduledTaskLogUpsertOne) Update(set func(*ScheduledTaskLogUpsert)) *ScheduledTaskLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduledTaskLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *ScheduledTaskLogUpsertOne) SetUpdateTime(v time.Time) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateUpdateTime() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *ScheduledTaskLogUpsertOne) SetIsDelete(v bool) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateIsDelete() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *ScheduledTaskLogUpsertOne) SetVersion(v int) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ScheduledTaskLogUpsertOne) AddVersion(v int) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateVersion() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateVersion()
	})
}

// SetTaskName sets the "taskName" field.
func (u *ScheduledTaskLogUpsertOne) SetTaskName(v string) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetTaskName(v)
	})
}

// UpdateTaskName sets the "taskName" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateTaskName() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateTaskName()
	})
}

// SetStatus sets the "status" field.
func (u *ScheduledTaskLogUpsertOne) SetStatus(v string) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateStatus() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateStatus()
	})
}

// SetStartTime sets the "startTime" field.
func (u *ScheduledTaskLogUpsertOne) SetStartTime(v time.Time) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateStartTime() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "endTime" field.
func (u *ScheduledTaskLogUpsertOne) SetEndTime(v time.Time) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateEndTime() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "endTime" field.
func (u *ScheduledTaskLogUpsertOne) ClearEndTime() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearEndTime()
	})
}

// SetResult sets the "result" field.
func (u *ScheduledTaskLogUpsertOne) SetResult(v string) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateResult() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *ScheduledTaskLogUpsertOne) ClearResult() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearResult()
	})
}

// SetErrorMessage sets the "errorMessage" field.
func (u *ScheduledTaskLogUpsertOne) SetErrorMessage(v string) *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "errorMessage" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertOne) UpdateErrorMessage() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "errorMessage" field.
func (u *ScheduledTaskLogUpsertOne) ClearErrorMessage() *ScheduledTaskLogUpsertOne {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *ScheduledTaskLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduledTaskLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduledTaskLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScheduledTaskLogUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScheduledTaskLogUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScheduledTaskLogCreateBulk is the builder for creating many ScheduledTaskLog entities in bulk.
type ScheduledTaskLogCreateBulk struct {
	config
	err      error
	builders []*ScheduledTaskLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ScheduledTaskLog entities in the database.
func (_c *ScheduledTaskLogCreateBulk) Save(ctx context.Context) ([]*ScheduledTaskLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScheduledTaskLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScheduledTaskLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScheduledTaskLogCreateBulk) SaveX(ctx context.Context) []*ScheduledTaskLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScheduledTaskLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScheduledTaskLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScheduledTaskLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScheduledTaskLogUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (_c *ScheduledTaskLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScheduledTaskLogUpsertBulk {
	_c.conflict = opts
	return &ScheduledTaskLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScheduledTaskLogCreateBulk) OnConflictColumns(columns ...string) *ScheduledTaskLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScheduledTaskLogUpsertBulk{
		create: _c,
	}
}

// ScheduledTaskLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ScheduledTaskLog nodes.
type ScheduledTaskLogUpsertBulk struct {
	create *ScheduledTaskLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scheduledtasklog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScheduledTaskLogUpsertBulk) UpdateNewValues() *ScheduledTaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(scheduledtasklog.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(scheduledtasklog.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScheduledTaskLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScheduledTaskLogUpsertBulk) Ignore() *ScheduledTaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScheduledTaskLogUpsertBulk) DoNothing() *ScheduledTaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScheduledTaskLogCreateBulk.OnConflict
// documentation for more info.
func (u *ScheduledTaskLogUpsertBulk) Update(set func(*ScheduledTaskLogUpsert)) *ScheduledTaskLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScheduledTaskLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *ScheduledTaskLogUpsertBulk) SetUpdateTime(v time.Time) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateUpdateTime() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetIsDelete sets the "isDelete" field.
func (u *ScheduledTaskLogUpsertBulk) SetIsDelete(v bool) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetIsDelete(v)
	})
}

// UpdateIsDelete sets the "isDelete" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateIsDelete() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateIsDelete()
	})
}

// SetVersion sets the "version" field.
func (u *ScheduledTaskLogUpsertBulk) SetVersion(v int) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ScheduledTaskLogUpsertBulk) AddVersion(v int) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateVersion() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateVersion()
	})
}

// SetTaskName sets the "taskName" field.
func (u *ScheduledTaskLogUpsertBulk) SetTaskName(v string) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetTaskName(v)
	})
}

// UpdateTaskName sets the "taskName" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateTaskName() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateTaskName()
	})
}

// SetStatus sets the "status" field.
func (u *ScheduledTaskLogUpsertBulk) SetStatus(v string) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateStatus() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateStatus()
	})
}

// SetStartTime sets the "startTime" field.
func (u *ScheduledTaskLogUpsertBulk) SetStartTime(v time.Time) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "startTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateStartTime() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateStartTime()
	})
}

// SetEndTime sets the "endTime" field.
func (u *ScheduledTaskLogUpsertBulk) SetEndTime(v time.Time) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "endTime" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateEndTime() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "endTime" field.
func (u *ScheduledTaskLogUpsertBulk) ClearEndTime() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearEndTime()
	})
}

// SetResult sets the "result" field.
func (u *ScheduledTaskLogUpsertBulk) SetResult(v string) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateResult() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *ScheduledTaskLogUpsertBulk) ClearResult() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearResult()
	})
}

// SetErrorMessage sets the "errorMessage" field.
func (u *ScheduledTaskLogUpsertBulk) SetErrorMessage(v string) *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "errorMessage" field to the value that was provided on create.
func (u *ScheduledTaskLogUpsertBulk) UpdateErrorMessage() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "errorMessage" field.
func (u *ScheduledTaskLogUpsertBulk) ClearErrorMessage() *ScheduledTaskLogUpsertBulk {
	return u.Update(func(s *ScheduledTaskLogUpsert) {
		s.ClearErrorMessage()
	})
}

// Exec executes the query.
func (u *ScheduledTaskLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScheduledTaskLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScheduledTaskLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScheduledTaskLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
