// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/scheduledtasklog"
)

// ScheduledTaskLogDelete is the builder for deleting a ScheduledTaskLog entity.
type ScheduledTaskLogDelete struct {
	config
	hooks    []Hook
	mutation *ScheduledTaskLogMutation
}

// Where appends a list predicates to the ScheduledTaskLogDelete builder.
func (stld *ScheduledTaskLogDelete) Where(ps ...predicate.ScheduledTaskLog) *ScheduledTaskLogDelete {
	stld.mutation.Where(ps...)
	return stld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (stld *ScheduledTaskLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, stld.sqlExec, stld.mutation, stld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (stld *ScheduledTaskLogDelete) ExecX(ctx context.Context) int {
	n, err := stld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (stld *ScheduledTaskLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(scheduledtasklog.Table, sqlgraph.NewFieldSpec(scheduledtasklog.FieldID, field.TypeInt))
	if ps := stld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, stld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	stld.mutation.done = true
	return affected, err
}

// ScheduledTaskLogDeleteOne is the builder for deleting a single ScheduledTaskLog entity.
type ScheduledTaskLogDeleteOne struct {
	stld *ScheduledTaskLogDelete
}

// Where appends a list predicates to the ScheduledTaskLogDelete builder.
func (stldo *ScheduledTaskLogDeleteOne) Where(ps ...predicate.ScheduledTaskLog) *ScheduledTaskLogDeleteOne {
	stldo.stld.mutation.Where(ps...)
	return stldo
}

// Exec executes the deletion query.
func (stldo *ScheduledTaskLogDeleteOne) Exec(ctx context.Context) error {
	n, err := stldo.stld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{scheduledtasklog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stldo *ScheduledTaskLogDeleteOne) ExecX(ctx context.Context) {
	if err := stldo.Exec(ctx); err != nil {
		panic(err)
	}
}
