// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/sensitiveword"
)

// SensitiveWord is the model entity for the SensitiveWord schema.
type SensitiveWord struct {
	config `json:"-"`
	// ID of the ent.
	// 敏感词ID
	ID int `json:"id,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"createTime,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"updateTime,omitempty"`
	// 软删除标记
	IsDelete bool `json:"isDelete,omitempty"`
	// 乐观锁版本号
	Version int `json:"version,omitempty"`
	// 敏感词
	Word string `json:"word,omitempty"`
	// 分类：广告/色情/赌博/自定义等
	Category string `json:"category,omitempty"`
	// 状态：1=启用 0=禁用
	Status int `json:"status,omitempty"`
	// 等级：1重/2中/3轻
	Level int `json:"level,omitempty"`
	// 扣血量
	HpPenalty int `json:"hpPenalty,omitempty"`
	// 是否进审核：1是0否
	NeedReview int `json:"needReview,omitempty"`
	// 1替换/2拒绝/3仅记录
	Action       int `json:"action,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SensitiveWord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sensitiveword.FieldIsDelete:
			values[i] = new(sql.NullBool)
		case sensitiveword.FieldID, sensitiveword.FieldVersion, sensitiveword.FieldStatus, sensitiveword.FieldLevel, sensitiveword.FieldHpPenalty, sensitiveword.FieldNeedReview, sensitiveword.FieldAction:
			values[i] = new(sql.NullInt64)
		case sensitiveword.FieldWord, sensitiveword.FieldCategory:
			values[i] = new(sql.NullString)
		case sensitiveword.FieldCreateTime, sensitiveword.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SensitiveWord fields.
func (_m *SensitiveWord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sensitiveword.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case sensitiveword.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createTime", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case sensitiveword.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updateTime", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case sensitiveword.FieldIsDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isDelete", values[i])
			} else if value.Valid {
				_m.IsDelete = value.Bool
			}
		case sensitiveword.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case sensitiveword.FieldWord:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field word", values[i])
			} else if value.Valid {
				_m.Word = value.String
			}
		case sensitiveword.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case sensitiveword.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case sensitiveword.FieldLevel:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				_m.Level = int(value.Int64)
			}
		case sensitiveword.FieldHpPenalty:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hpPenalty", values[i])
			} else if value.Valid {
				_m.HpPenalty = int(value.Int64)
			}
		case sensitiveword.FieldNeedReview:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field needReview", values[i])
			} else if value.Valid {
				_m.NeedReview = int(value.Int64)
			}
		case sensitiveword.FieldAction:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SensitiveWord.
// This includes values selected through modifiers, order, etc.
func (_m *SensitiveWord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SensitiveWord.
// Note that you need to call SensitiveWord.Unwrap() before calling this method if this SensitiveWord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SensitiveWord) Update() *SensitiveWordUpdateOne {
	return NewSensitiveWordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SensitiveWord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SensitiveWord) Unwrap() *SensitiveWord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SensitiveWord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SensitiveWord) String() string {
	var builder strings.Builder
	builder.WriteString("SensitiveWord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("createTime=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updateTime=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("isDelete=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDelete))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("word=")
	builder.WriteString(_m.Word)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", _m.Level))
	builder.WriteString(", ")
	builder.WriteString("hpPenalty=")
	builder.WriteString(fmt.Sprintf("%v", _m.HpPenalty))
	builder.WriteString(", ")
	builder.WriteString("needReview=")
	builder.WriteString(fmt.Sprintf("%v", _m.NeedReview))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteByte(')')
	return builder.String()
}

// SensitiveWords is a parsable slice of SensitiveWord.
type SensitiveWords []*SensitiveWord
