// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "updateTime" field.
func (_u *UserUpdate) SetUpdateTime(v time.Time) *UserUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *UserUpdate) SetIsDelete(v bool) *UserUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsDelete(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserUpdate) SetVersion(v int) *UserUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserUpdate) SetNillableVersion(v *int) *UserUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserUpdate) AddVersion(v int) *UserUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdate) SetStatus(v string) *UserUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStatus(v *string) *UserUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdate) SetPassword(v string) *UserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *UserUpdate) SetSalt(v string) *UserUpdate {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSalt(v *string) *UserUpdate {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetIntro sets the "intro" field.
func (_u *UserUpdate) SetIntro(v string) *UserUpdate {
	_u.mutation.SetIntro(v)
	return _u
}

// SetNillableIntro sets the "intro" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIntro(v *string) *UserUpdate {
	if v != nil {
		_u.SetIntro(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *UserUpdate) SetAvatar(v string) *UserUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatar(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetHomepage sets the "homepage" field.
func (_u *UserUpdate) SetHomepage(v string) *UserUpdate {
	_u.mutation.SetHomepage(v)
	return _u
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (_u *UserUpdate) SetNillableHomepage(v *string) *UserUpdate {
	if v != nil {
		_u.SetHomepage(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetGithubId sets the "githubId" field.
func (_u *UserUpdate) SetGithubId(v string) *UserUpdate {
	_u.mutation.SetGithubId(v)
	return _u
}

// SetNillableGithubId sets the "githubId" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGithubId(v *string) *UserUpdate {
	if v != nil {
		_u.SetGithubId(*v)
	}
	return _u
}

// ClearGithubId clears the value of the "githubId" field.
func (_u *UserUpdate) ClearGithubId() *UserUpdate {
	_u.mutation.ClearGithubId()
	return _u
}

// SetWechatOpenId sets the "wechatOpenId" field.
func (_u *UserUpdate) SetWechatOpenId(v string) *UserUpdate {
	_u.mutation.SetWechatOpenId(v)
	return _u
}

// SetNillableWechatOpenId sets the "wechatOpenId" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWechatOpenId(v *string) *UserUpdate {
	if v != nil {
		_u.SetWechatOpenId(*v)
	}
	return _u
}

// ClearWechatOpenId clears the value of the "wechatOpenId" field.
func (_u *UserUpdate) ClearWechatOpenId() *UserUpdate {
	_u.mutation.ClearWechatOpenId()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdate) ClearUsername() *UserUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetDeptId sets the "deptId" field.
func (_u *UserUpdate) SetDeptId(v int) *UserUpdate {
	_u.mutation.ResetDeptId()
	_u.mutation.SetDeptId(v)
	return _u
}

// SetNillableDeptId sets the "deptId" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDeptId(v *int) *UserUpdate {
	if v != nil {
		_u.SetDeptId(*v)
	}
	return _u
}

// AddDeptId adds value to the "deptId" field.
func (_u *UserUpdate) AddDeptId(v int) *UserUpdate {
	_u.mutation.AddDeptId(v)
	return _u
}

// ClearDeptId clears the value of the "deptId" field.
func (_u *UserUpdate) ClearDeptId() *UserUpdate {
	_u.mutation.ClearDeptId()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdate) SetNickname(v string) *UserUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNickname(v *string) *UserUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(user.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(user.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(user.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Intro(); ok {
		_spec.SetField(user.FieldIntro, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.Homepage(); ok {
		_spec.SetField(user.FieldHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.GithubId(); ok {
		_spec.SetField(user.FieldGithubId, field.TypeString, value)
	}
	if _u.mutation.GithubIdCleared() {
		_spec.ClearField(user.FieldGithubId, field.TypeString)
	}
	if value, ok := _u.mutation.WechatOpenId(); ok {
		_spec.SetField(user.FieldWechatOpenId, field.TypeString, value)
	}
	if _u.mutation.WechatOpenIdCleared() {
		_spec.ClearField(user.FieldWechatOpenId, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.DeptId(); ok {
		_spec.SetField(user.FieldDeptId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeptId(); ok {
		_spec.AddField(user.FieldDeptId, field.TypeInt, value)
	}
	if _u.mutation.DeptIdCleared() {
		_spec.ClearField(user.FieldDeptId, field.TypeInt)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdateTime sets the "updateTime" field.
func (_u *UserUpdateOne) SetUpdateTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "isDelete" field.
func (_u *UserUpdateOne) SetIsDelete(v bool) *UserUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "isDelete" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsDelete(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *UserUpdateOne) SetVersion(v int) *UserUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableVersion(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *UserUpdateOne) AddVersion(v int) *UserUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdateOne) SetStatus(v string) *UserUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStatus(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *UserUpdateOne) SetPassword(v string) *UserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *UserUpdateOne) SetSalt(v string) *UserUpdateOne {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSalt(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetIntro sets the "intro" field.
func (_u *UserUpdateOne) SetIntro(v string) *UserUpdateOne {
	_u.mutation.SetIntro(v)
	return _u
}

// SetNillableIntro sets the "intro" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIntro(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetIntro(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *UserUpdateOne) SetAvatar(v string) *UserUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatar(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetHomepage sets the "homepage" field.
func (_u *UserUpdateOne) SetHomepage(v string) *UserUpdateOne {
	_u.mutation.SetHomepage(v)
	return _u
}

// SetNillableHomepage sets the "homepage" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableHomepage(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetHomepage(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetGithubId sets the "githubId" field.
func (_u *UserUpdateOne) SetGithubId(v string) *UserUpdateOne {
	_u.mutation.SetGithubId(v)
	return _u
}

// SetNillableGithubId sets the "githubId" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGithubId(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGithubId(*v)
	}
	return _u
}

// ClearGithubId clears the value of the "githubId" field.
func (_u *UserUpdateOne) ClearGithubId() *UserUpdateOne {
	_u.mutation.ClearGithubId()
	return _u
}

// SetWechatOpenId sets the "wechatOpenId" field.
func (_u *UserUpdateOne) SetWechatOpenId(v string) *UserUpdateOne {
	_u.mutation.SetWechatOpenId(v)
	return _u
}

// SetNillableWechatOpenId sets the "wechatOpenId" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWechatOpenId(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetWechatOpenId(*v)
	}
	return _u
}

// ClearWechatOpenId clears the value of the "wechatOpenId" field.
func (_u *UserUpdateOne) ClearWechatOpenId() *UserUpdateOne {
	_u.mutation.ClearWechatOpenId()
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdateOne) ClearUsername() *UserUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetDeptId sets the "deptId" field.
func (_u *UserUpdateOne) SetDeptId(v int) *UserUpdateOne {
	_u.mutation.ResetDeptId()
	_u.mutation.SetDeptId(v)
	return _u
}

// SetNillableDeptId sets the "deptId" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDeptId(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetDeptId(*v)
	}
	return _u
}

// AddDeptId adds value to the "deptId" field.
func (_u *UserUpdateOne) AddDeptId(v int) *UserUpdateOne {
	_u.mutation.AddDeptId(v)
	return _u
}

// ClearDeptId clears the value of the "deptId" field.
func (_u *UserUpdateOne) ClearDeptId() *UserUpdateOne {
	_u.mutation.ClearDeptId()
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdateOne) SetNickname(v string) *UserUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNickname(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(user.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(user.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(user.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Intro(); ok {
		_spec.SetField(user.FieldIntro, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.Homepage(); ok {
		_spec.SetField(user.FieldHomepage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.GithubId(); ok {
		_spec.SetField(user.FieldGithubId, field.TypeString, value)
	}
	if _u.mutation.GithubIdCleared() {
		_spec.ClearField(user.FieldGithubId, field.TypeString)
	}
	if value, ok := _u.mutation.WechatOpenId(); ok {
		_spec.SetField(user.FieldWechatOpenId, field.TypeString, value)
	}
	if _u.mutation.WechatOpenIdCleared() {
		_spec.ClearField(user.FieldWechatOpenId, field.TypeString)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.DeptId(); ok {
		_spec.SetField(user.FieldDeptId, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeptId(); ok {
		_spec.AddField(user.FieldDeptId, field.TypeInt, value)
	}
	if _u.mutation.DeptIdCleared() {
		_spec.ClearField(user.FieldDeptId, field.TypeInt)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
