// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Jiang-Xia/blog-server-go/pkg/config"
	"github.com/Jiang-Xia/blog-server-go/pkg/logger"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/data"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/handler"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/operationlog"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/server"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/admin"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/auth"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/captcha"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/email"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/profile"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/repo"
	"github.com/Jiang-Xia/blog-server-go/services/user/internal/user/sensitive"
)

// Injectors from wire.go:

// InitializeApp 装配 user-service 全部依赖。
func InitializeApp(cfgPath string) (*App, error) {
	configConfig, err := config.MustLoad(cfgPath)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.New(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := data.NewEntClient(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	rueidisClient, err := data.NewRedisClient(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	healthHandler := handler.NewHealthHandler(client, rueidisClient)
	userRepo := repo.NewUserRepo(client)
	roleRepo, err := provideRoleRepo(configConfig)
	if err != nil {
		return nil, err
	}
	passwordChecker := providePasswordChecker(configConfig, userRepo)
	v := auth.NewJWTService(configConfig)
	store := provideRedisStore(rueidisClient)
	service := email.NewService(configConfig, store)
	authService := auth.NewAuthService(userRepo, roleRepo, passwordChecker, v, store, configConfig, service)
	profileService := profile.NewService(userRepo, roleRepo)
	gitHubOAuth := auth.NewGitHubOAuth(configConfig, authService, userRepo)
	userAppAdapter := handler.NewUserAppAdapter(configConfig, authService, profileService, gitHubOAuth)
	captchaService := captcha.NewService(store)
	userHandler := provideUserHandler(configConfig, userAppAdapter, captchaService)
	adminRepo, err := provideAdminRepo(configConfig)
	if err != nil {
		return nil, err
	}
	adminService := admin.NewService(adminRepo, roleRepo, userRepo)
	adminHandler := handler.NewAdminHandler(adminService, v)
	captchaHandler := provideCaptchaHandler(configConfig, captchaService)
	contentModerationSyncer, err := provideBlogModerationSyncer(configConfig)
	if err != nil {
		return nil, err
	}
	sensitiveService := sensitive.NewService(client, zapLogger, contentModerationSyncer)
	sensitiveWordHandler := handler.NewSensitiveWordHandler(sensitiveService, v)
	operationlogService := operationlog.NewService(client)
	operationLogHandler := handler.NewOperationLogHandler(operationlogService)
	registerDeps := provideRegisterDeps(healthHandler, userHandler, adminHandler, captchaHandler, sensitiveWordHandler, operationLogHandler, v, userRepo, configConfig, store, roleRepo, operationlogService, zapLogger)
	hertz := server.NewHTTPServer(configConfig, zapLogger, registerDeps)
	grpcserverServer := provideUserGRPCServer(profileService, v, service)
	app := NewApp(configConfig, hertz, zapLogger, client, rueidisClient, grpcserverServer)
	return app, nil
}
