// Code generated by ent, DO NOT EDIT.

package menu

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Jiang-Xia/blog-server-go/services/monolith/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldID, id))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldPid, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldPath, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldName, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldOrder, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldIcon, v))
}

// Locale applies equality check predicate on the "locale" field. It's identical to LocaleEQ.
func Locale(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldLocale, v))
}

// RequiresAuth applies equality check predicate on the "requiresAuth" field. It's identical to RequiresAuthEQ.
func RequiresAuth(v int) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldRequiresAuth, v))
}

// FilePath applies equality check predicate on the "filePath" field. It's identical to FilePathEQ.
func FilePath(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldFilePath, v))
}

// MenuCnName applies equality check predicate on the "menuCnName" field. It's identical to MenuCnNameEQ.
func MenuCnName(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldMenuCnName, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldPid, v))
}

// PidContains applies the Contains predicate on the "pid" field.
func PidContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldPid, v))
}

// PidHasPrefix applies the HasPrefix predicate on the "pid" field.
func PidHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldPid, v))
}

// PidHasSuffix applies the HasSuffix predicate on the "pid" field.
func PidHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldPid, v))
}

// PidEqualFold applies the EqualFold predicate on the "pid" field.
func PidEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldPid, v))
}

// PidContainsFold applies the ContainsFold predicate on the "pid" field.
func PidContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldPid, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldPath, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldName, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldOrder, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldIcon, v))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldIcon, v))
}

// LocaleEQ applies the EQ predicate on the "locale" field.
func LocaleEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldLocale, v))
}

// LocaleNEQ applies the NEQ predicate on the "locale" field.
func LocaleNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldLocale, v))
}

// LocaleIn applies the In predicate on the "locale" field.
func LocaleIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldLocale, vs...))
}

// LocaleNotIn applies the NotIn predicate on the "locale" field.
func LocaleNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldLocale, vs...))
}

// LocaleGT applies the GT predicate on the "locale" field.
func LocaleGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldLocale, v))
}

// LocaleGTE applies the GTE predicate on the "locale" field.
func LocaleGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldLocale, v))
}

// LocaleLT applies the LT predicate on the "locale" field.
func LocaleLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldLocale, v))
}

// LocaleLTE applies the LTE predicate on the "locale" field.
func LocaleLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldLocale, v))
}

// LocaleContains applies the Contains predicate on the "locale" field.
func LocaleContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldLocale, v))
}

// LocaleHasPrefix applies the HasPrefix predicate on the "locale" field.
func LocaleHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldLocale, v))
}

// LocaleHasSuffix applies the HasSuffix predicate on the "locale" field.
func LocaleHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldLocale, v))
}

// LocaleEqualFold applies the EqualFold predicate on the "locale" field.
func LocaleEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldLocale, v))
}

// LocaleContainsFold applies the ContainsFold predicate on the "locale" field.
func LocaleContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldLocale, v))
}

// RequiresAuthEQ applies the EQ predicate on the "requiresAuth" field.
func RequiresAuthEQ(v int) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldRequiresAuth, v))
}

// RequiresAuthNEQ applies the NEQ predicate on the "requiresAuth" field.
func RequiresAuthNEQ(v int) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldRequiresAuth, v))
}

// RequiresAuthIn applies the In predicate on the "requiresAuth" field.
func RequiresAuthIn(vs ...int) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldRequiresAuth, vs...))
}

// RequiresAuthNotIn applies the NotIn predicate on the "requiresAuth" field.
func RequiresAuthNotIn(vs ...int) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldRequiresAuth, vs...))
}

// RequiresAuthGT applies the GT predicate on the "requiresAuth" field.
func RequiresAuthGT(v int) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldRequiresAuth, v))
}

// RequiresAuthGTE applies the GTE predicate on the "requiresAuth" field.
func RequiresAuthGTE(v int) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldRequiresAuth, v))
}

// RequiresAuthLT applies the LT predicate on the "requiresAuth" field.
func RequiresAuthLT(v int) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldRequiresAuth, v))
}

// RequiresAuthLTE applies the LTE predicate on the "requiresAuth" field.
func RequiresAuthLTE(v int) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldRequiresAuth, v))
}

// FilePathEQ applies the EQ predicate on the "filePath" field.
func FilePathEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldFilePath, v))
}

// FilePathNEQ applies the NEQ predicate on the "filePath" field.
func FilePathNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldFilePath, v))
}

// FilePathIn applies the In predicate on the "filePath" field.
func FilePathIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldFilePath, vs...))
}

// FilePathNotIn applies the NotIn predicate on the "filePath" field.
func FilePathNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldFilePath, vs...))
}

// FilePathGT applies the GT predicate on the "filePath" field.
func FilePathGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldFilePath, v))
}

// FilePathGTE applies the GTE predicate on the "filePath" field.
func FilePathGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldFilePath, v))
}

// FilePathLT applies the LT predicate on the "filePath" field.
func FilePathLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldFilePath, v))
}

// FilePathLTE applies the LTE predicate on the "filePath" field.
func FilePathLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldFilePath, v))
}

// FilePathContains applies the Contains predicate on the "filePath" field.
func FilePathContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldFilePath, v))
}

// FilePathHasPrefix applies the HasPrefix predicate on the "filePath" field.
func FilePathHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldFilePath, v))
}

// FilePathHasSuffix applies the HasSuffix predicate on the "filePath" field.
func FilePathHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldFilePath, v))
}

// FilePathEqualFold applies the EqualFold predicate on the "filePath" field.
func FilePathEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldFilePath, v))
}

// FilePathContainsFold applies the ContainsFold predicate on the "filePath" field.
func FilePathContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldFilePath, v))
}

// MenuCnNameEQ applies the EQ predicate on the "menuCnName" field.
func MenuCnNameEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEQ(FieldMenuCnName, v))
}

// MenuCnNameNEQ applies the NEQ predicate on the "menuCnName" field.
func MenuCnNameNEQ(v string) predicate.Menu {
	return predicate.Menu(sql.FieldNEQ(FieldMenuCnName, v))
}

// MenuCnNameIn applies the In predicate on the "menuCnName" field.
func MenuCnNameIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldIn(FieldMenuCnName, vs...))
}

// MenuCnNameNotIn applies the NotIn predicate on the "menuCnName" field.
func MenuCnNameNotIn(vs ...string) predicate.Menu {
	return predicate.Menu(sql.FieldNotIn(FieldMenuCnName, vs...))
}

// MenuCnNameGT applies the GT predicate on the "menuCnName" field.
func MenuCnNameGT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGT(FieldMenuCnName, v))
}

// MenuCnNameGTE applies the GTE predicate on the "menuCnName" field.
func MenuCnNameGTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldGTE(FieldMenuCnName, v))
}

// MenuCnNameLT applies the LT predicate on the "menuCnName" field.
func MenuCnNameLT(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLT(FieldMenuCnName, v))
}

// MenuCnNameLTE applies the LTE predicate on the "menuCnName" field.
func MenuCnNameLTE(v string) predicate.Menu {
	return predicate.Menu(sql.FieldLTE(FieldMenuCnName, v))
}

// MenuCnNameContains applies the Contains predicate on the "menuCnName" field.
func MenuCnNameContains(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContains(FieldMenuCnName, v))
}

// MenuCnNameHasPrefix applies the HasPrefix predicate on the "menuCnName" field.
func MenuCnNameHasPrefix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasPrefix(FieldMenuCnName, v))
}

// MenuCnNameHasSuffix applies the HasSuffix predicate on the "menuCnName" field.
func MenuCnNameHasSuffix(v string) predicate.Menu {
	return predicate.Menu(sql.FieldHasSuffix(FieldMenuCnName, v))
}

// MenuCnNameIsNil applies the IsNil predicate on the "menuCnName" field.
func MenuCnNameIsNil() predicate.Menu {
	return predicate.Menu(sql.FieldIsNull(FieldMenuCnName))
}

// MenuCnNameNotNil applies the NotNil predicate on the "menuCnName" field.
func MenuCnNameNotNil() predicate.Menu {
	return predicate.Menu(sql.FieldNotNull(FieldMenuCnName))
}

// MenuCnNameEqualFold applies the EqualFold predicate on the "menuCnName" field.
func MenuCnNameEqualFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldEqualFold(FieldMenuCnName, v))
}

// MenuCnNameContainsFold applies the ContainsFold predicate on the "menuCnName" field.
func MenuCnNameContainsFold(v string) predicate.Menu {
	return predicate.Menu(sql.FieldContainsFold(FieldMenuCnName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Menu) predicate.Menu {
	return predicate.Menu(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Menu) predicate.Menu {
	return predicate.Menu(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Menu) predicate.Menu {
	return predicate.Menu(sql.NotPredicates(p))
}
