// Code generated by ent, DO NOT EDIT.

package rolemenusmenu

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rolemenusmenu type in the database.
	Label = "role_menus_menu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleId holds the string denoting the roleid field in the database.
	FieldRoleId = "roleId"
	// FieldMenuId holds the string denoting the menuid field in the database.
	FieldMenuId = "menuId"
	// Table holds the table name of the rolemenusmenu in the database.
	Table = "x_role_menus_menu"
)

// Columns holds all SQL columns for rolemenusmenu fields.
var Columns = []string{
	FieldID,
	FieldRoleId,
	FieldMenuId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RoleMenusMenu queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRoleId orders the results by the roleId field.
func ByRoleId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleId, opts...).ToFunc()
}

// ByMenuId orders the results by the menuId field.
func ByMenuId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMenuId, opts...).ToFunc()
}
