// Code generated by ent, DO NOT EDIT.

package rpguserpet

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rpguserpet type in the database.
	Label = "rpg_user_pet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the createtime field in the database.
	FieldCreateTime = "createTime"
	// FieldUpdateTime holds the string denoting the updatetime field in the database.
	FieldUpdateTime = "updateTime"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldPetCode holds the string denoting the petcode field in the database.
	FieldPetCode = "petCode"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldExp holds the string denoting the exp field in the database.
	FieldExp = "exp"
	// FieldEffectJson holds the string denoting the effectjson field in the database.
	FieldEffectJson = "effectJson"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// Table holds the table name of the rpguserpet in the database.
	Table = "x_rpg_user_pet"
)

// Columns holds all SQL columns for rpguserpet fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUID,
	FieldPetCode,
	FieldLevel,
	FieldExp,
	FieldEffectJson,
	FieldNickname,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "createTime" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "updateTime" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "updateTime" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int
	// DefaultExp holds the default value on creation for the "exp" field.
	DefaultExp int
	// DefaultNickname holds the default value on creation for the "nickname" field.
	DefaultNickname string
)

// OrderOption defines the ordering options for the RpgUserPet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the createTime field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the updateTime field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByPetCode orders the results by the petCode field.
func ByPetCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPetCode, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByExp orders the results by the exp field.
func ByExp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExp, opts...).ToFunc()
}

// ByEffectJson orders the results by the effectJson field.
func ByEffectJson(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectJson, opts...).ToFunc()
}

// ByNickname orders the results by the nickname field.
func ByNickname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNickname, opts...).ToFunc()
}
