// Code generated by ent, DO NOT EDIT.

package like

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the like type in the database.
	Label = "like"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldArticleId holds the string denoting the articleid field in the database.
	FieldArticleId = "articleId"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the like in the database.
	Table = "x_like"
)

// Columns holds all SQL columns for like fields.
var Columns = []string{
	FieldID,
	FieldArticleId,
	FieldUID,
	FieldIP,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUID holds the default value on creation for the "uid" field.
	DefaultUID int
	// DefaultIP holds the default value on creation for the "ip" field.
	DefaultIP string
)

// OrderOption defines the ordering options for the Like queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByArticleId orders the results by the articleId field.
func ByArticleId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArticleId, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
