// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/rpg/ent/predicate"
	"github.com/Jiang-Xia/blog-server-go/services/rpg/ent/rpgarticletip"
)

// RpgArticleTipQuery is the builder for querying RpgArticleTip entities.
type RpgArticleTipQuery struct {
	config
	ctx        *QueryContext
	order      []rpgarticletip.OrderOption
	inters     []Interceptor
	predicates []predicate.RpgArticleTip
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RpgArticleTipQuery builder.
func (ratq *RpgArticleTipQuery) Where(ps ...predicate.RpgArticleTip) *RpgArticleTipQuery {
	ratq.predicates = append(ratq.predicates, ps...)
	return ratq
}

// Limit the number of records to be returned by this query.
func (ratq *RpgArticleTipQuery) Limit(limit int) *RpgArticleTipQuery {
	ratq.ctx.Limit = &limit
	return ratq
}

// Offset to start from.
func (ratq *RpgArticleTipQuery) Offset(offset int) *RpgArticleTipQuery {
	ratq.ctx.Offset = &offset
	return ratq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ratq *RpgArticleTipQuery) Unique(unique bool) *RpgArticleTipQuery {
	ratq.ctx.Unique = &unique
	return ratq
}

// Order specifies how the records should be ordered.
func (ratq *RpgArticleTipQuery) Order(o ...rpgarticletip.OrderOption) *RpgArticleTipQuery {
	ratq.order = append(ratq.order, o...)
	return ratq
}

// First returns the first RpgArticleTip entity from the query.
// Returns a *NotFoundError when no RpgArticleTip was found.
func (ratq *RpgArticleTipQuery) First(ctx context.Context) (*RpgArticleTip, error) {
	nodes, err := ratq.Limit(1).All(setContextOp(ctx, ratq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rpgarticletip.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) FirstX(ctx context.Context) *RpgArticleTip {
	node, err := ratq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RpgArticleTip ID from the query.
// Returns a *NotFoundError when no RpgArticleTip ID was found.
func (ratq *RpgArticleTipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ratq.Limit(1).IDs(setContextOp(ctx, ratq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rpgarticletip.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) FirstIDX(ctx context.Context) int {
	id, err := ratq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RpgArticleTip entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RpgArticleTip entity is found.
// Returns a *NotFoundError when no RpgArticleTip entities are found.
func (ratq *RpgArticleTipQuery) Only(ctx context.Context) (*RpgArticleTip, error) {
	nodes, err := ratq.Limit(2).All(setContextOp(ctx, ratq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rpgarticletip.Label}
	default:
		return nil, &NotSingularError{rpgarticletip.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) OnlyX(ctx context.Context) *RpgArticleTip {
	node, err := ratq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RpgArticleTip ID in the query.
// Returns a *NotSingularError when more than one RpgArticleTip ID is found.
// Returns a *NotFoundError when no entities are found.
func (ratq *RpgArticleTipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ratq.Limit(2).IDs(setContextOp(ctx, ratq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rpgarticletip.Label}
	default:
		err = &NotSingularError{rpgarticletip.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) OnlyIDX(ctx context.Context) int {
	id, err := ratq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RpgArticleTips.
func (ratq *RpgArticleTipQuery) All(ctx context.Context) ([]*RpgArticleTip, error) {
	ctx = setContextOp(ctx, ratq.ctx, ent.OpQueryAll)
	if err := ratq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RpgArticleTip, *RpgArticleTipQuery]()
	return withInterceptors[[]*RpgArticleTip](ctx, ratq, qr, ratq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) AllX(ctx context.Context) []*RpgArticleTip {
	nodes, err := ratq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RpgArticleTip IDs.
func (ratq *RpgArticleTipQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ratq.ctx.Unique == nil && ratq.path != nil {
		ratq.Unique(true)
	}
	ctx = setContextOp(ctx, ratq.ctx, ent.OpQueryIDs)
	if err = ratq.Select(rpgarticletip.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) IDsX(ctx context.Context) []int {
	ids, err := ratq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ratq *RpgArticleTipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ratq.ctx, ent.OpQueryCount)
	if err := ratq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ratq, querierCount[*RpgArticleTipQuery](), ratq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) CountX(ctx context.Context) int {
	count, err := ratq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ratq *RpgArticleTipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ratq.ctx, ent.OpQueryExist)
	switch _, err := ratq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ratq *RpgArticleTipQuery) ExistX(ctx context.Context) bool {
	exist, err := ratq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RpgArticleTipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ratq *RpgArticleTipQuery) Clone() *RpgArticleTipQuery {
	if ratq == nil {
		return nil
	}
	return &RpgArticleTipQuery{
		config:     ratq.config,
		ctx:        ratq.ctx.Clone(),
		order:      append([]rpgarticletip.OrderOption{}, ratq.order...),
		inters:     append([]Interceptor{}, ratq.inters...),
		predicates: append([]predicate.RpgArticleTip{}, ratq.predicates...),
		// clone intermediate query.
		sql:  ratq.sql.Clone(),
		path: ratq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"createTime,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RpgArticleTip.Query().
//		GroupBy(rpgarticletip.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ratq *RpgArticleTipQuery) GroupBy(field string, fields ...string) *RpgArticleTipGroupBy {
	ratq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RpgArticleTipGroupBy{build: ratq}
	grbuild.flds = &ratq.ctx.Fields
	grbuild.label = rpgarticletip.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"createTime,omitempty"`
//	}
//
//	client.RpgArticleTip.Query().
//		Select(rpgarticletip.FieldCreateTime).
//		Scan(ctx, &v)
func (ratq *RpgArticleTipQuery) Select(fields ...string) *RpgArticleTipSelect {
	ratq.ctx.Fields = append(ratq.ctx.Fields, fields...)
	sbuild := &RpgArticleTipSelect{RpgArticleTipQuery: ratq}
	sbuild.label = rpgarticletip.Label
	sbuild.flds, sbuild.scan = &ratq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RpgArticleTipSelect configured with the given aggregations.
func (ratq *RpgArticleTipQuery) Aggregate(fns ...AggregateFunc) *RpgArticleTipSelect {
	return ratq.Select().Aggregate(fns...)
}

func (ratq *RpgArticleTipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ratq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ratq); err != nil {
				return err
			}
		}
	}
	for _, f := range ratq.ctx.Fields {
		if !rpgarticletip.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ratq.path != nil {
		prev, err := ratq.path(ctx)
		if err != nil {
			return err
		}
		ratq.sql = prev
	}
	return nil
}

func (ratq *RpgArticleTipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RpgArticleTip, error) {
	var (
		nodes = []*RpgArticleTip{}
		_spec = ratq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RpgArticleTip).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RpgArticleTip{config: ratq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ratq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ratq *RpgArticleTipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ratq.querySpec()
	_spec.Node.Columns = ratq.ctx.Fields
	if len(ratq.ctx.Fields) > 0 {
		_spec.Unique = ratq.ctx.Unique != nil && *ratq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ratq.driver, _spec)
}

func (ratq *RpgArticleTipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rpgarticletip.Table, rpgarticletip.Columns, sqlgraph.NewFieldSpec(rpgarticletip.FieldID, field.TypeInt))
	_spec.From = ratq.sql
	if unique := ratq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ratq.path != nil {
		_spec.Unique = true
	}
	if fields := ratq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rpgarticletip.FieldID)
		for i := range fields {
			if fields[i] != rpgarticletip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ratq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ratq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ratq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ratq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ratq *RpgArticleTipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ratq.driver.Dialect())
	t1 := builder.Table(rpgarticletip.Table)
	columns := ratq.ctx.Fields
	if len(columns) == 0 {
		columns = rpgarticletip.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ratq.sql != nil {
		selector = ratq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ratq.ctx.Unique != nil && *ratq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ratq.predicates {
		p(selector)
	}
	for _, p := range ratq.order {
		p(selector)
	}
	if offset := ratq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ratq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RpgArticleTipGroupBy is the group-by builder for RpgArticleTip entities.
type RpgArticleTipGroupBy struct {
	selector
	build *RpgArticleTipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ratgb *RpgArticleTipGroupBy) Aggregate(fns ...AggregateFunc) *RpgArticleTipGroupBy {
	ratgb.fns = append(ratgb.fns, fns...)
	return ratgb
}

// Scan applies the selector query and scans the result into the given value.
func (ratgb *RpgArticleTipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ratgb.build.ctx, ent.OpQueryGroupBy)
	if err := ratgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RpgArticleTipQuery, *RpgArticleTipGroupBy](ctx, ratgb.build, ratgb, ratgb.build.inters, v)
}

func (ratgb *RpgArticleTipGroupBy) sqlScan(ctx context.Context, root *RpgArticleTipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ratgb.fns))
	for _, fn := range ratgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ratgb.flds)+len(ratgb.fns))
		for _, f := range *ratgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ratgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ratgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RpgArticleTipSelect is the builder for selecting fields of RpgArticleTip entities.
type RpgArticleTipSelect struct {
	*RpgArticleTipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rats *RpgArticleTipSelect) Aggregate(fns ...AggregateFunc) *RpgArticleTipSelect {
	rats.fns = append(rats.fns, fns...)
	return rats
}

// Scan applies the selector query and scans the result into the given value.
func (rats *RpgArticleTipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rats.ctx, ent.OpQuerySelect)
	if err := rats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RpgArticleTipQuery, *RpgArticleTipSelect](ctx, rats.RpgArticleTipQuery, rats, rats.inters, v)
}

func (rats *RpgArticleTipSelect) sqlScan(ctx context.Context, root *RpgArticleTipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rats.fns))
	for _, fn := range rats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
