// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Jiang-Xia/blog-server-go/services/rpg/ent/rpgleaderboardsnapshot"
)

// RpgLeaderboardSnapshotCreate is the builder for creating a RpgLeaderboardSnapshot entity.
type RpgLeaderboardSnapshotCreate struct {
	config
	mutation *RpgLeaderboardSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateTime sets the "createTime" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetCreateTime(t time.Time) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetCreateTime(t)
	return rlsc
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (rlsc *RpgLeaderboardSnapshotCreate) SetNillableCreateTime(t *time.Time) *RpgLeaderboardSnapshotCreate {
	if t != nil {
		rlsc.SetCreateTime(*t)
	}
	return rlsc
}

// SetUpdateTime sets the "updateTime" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetUpdateTime(t time.Time) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetUpdateTime(t)
	return rlsc
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (rlsc *RpgLeaderboardSnapshotCreate) SetNillableUpdateTime(t *time.Time) *RpgLeaderboardSnapshotCreate {
	if t != nil {
		rlsc.SetUpdateTime(*t)
	}
	return rlsc
}

// SetUID sets the "uid" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetUID(i int) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetUID(i)
	return rlsc
}

// SetScore sets the "score" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetScore(i int) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetScore(i)
	return rlsc
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (rlsc *RpgLeaderboardSnapshotCreate) SetNillableScore(i *int) *RpgLeaderboardSnapshotCreate {
	if i != nil {
		rlsc.SetScore(*i)
	}
	return rlsc
}

// SetRank sets the "rank" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetRank(i int) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetRank(i)
	return rlsc
}

// SetNillableRank sets the "rank" field if the given value is not nil.
func (rlsc *RpgLeaderboardSnapshotCreate) SetNillableRank(i *int) *RpgLeaderboardSnapshotCreate {
	if i != nil {
		rlsc.SetRank(*i)
	}
	return rlsc
}

// SetPeriodType sets the "periodType" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetPeriodType(s string) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetPeriodType(s)
	return rlsc
}

// SetPeriodKey sets the "periodKey" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetPeriodKey(s string) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetPeriodKey(s)
	return rlsc
}

// SetScoreType sets the "scoreType" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetScoreType(s string) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetScoreType(s)
	return rlsc
}

// SetID sets the "id" field.
func (rlsc *RpgLeaderboardSnapshotCreate) SetID(i int) *RpgLeaderboardSnapshotCreate {
	rlsc.mutation.SetID(i)
	return rlsc
}

// Mutation returns the RpgLeaderboardSnapshotMutation object of the builder.
func (rlsc *RpgLeaderboardSnapshotCreate) Mutation() *RpgLeaderboardSnapshotMutation {
	return rlsc.mutation
}

// Save creates the RpgLeaderboardSnapshot in the database.
func (rlsc *RpgLeaderboardSnapshotCreate) Save(ctx context.Context) (*RpgLeaderboardSnapshot, error) {
	rlsc.defaults()
	return withHooks(ctx, rlsc.sqlSave, rlsc.mutation, rlsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rlsc *RpgLeaderboardSnapshotCreate) SaveX(ctx context.Context) *RpgLeaderboardSnapshot {
	v, err := rlsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rlsc *RpgLeaderboardSnapshotCreate) Exec(ctx context.Context) error {
	_, err := rlsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rlsc *RpgLeaderboardSnapshotCreate) ExecX(ctx context.Context) {
	if err := rlsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rlsc *RpgLeaderboardSnapshotCreate) defaults() {
	if _, ok := rlsc.mutation.CreateTime(); !ok {
		v := rpgleaderboardsnapshot.DefaultCreateTime()
		rlsc.mutation.SetCreateTime(v)
	}
	if _, ok := rlsc.mutation.UpdateTime(); !ok {
		v := rpgleaderboardsnapshot.DefaultUpdateTime()
		rlsc.mutation.SetUpdateTime(v)
	}
	if _, ok := rlsc.mutation.Score(); !ok {
		v := rpgleaderboardsnapshot.DefaultScore
		rlsc.mutation.SetScore(v)
	}
	if _, ok := rlsc.mutation.Rank(); !ok {
		v := rpgleaderboardsnapshot.DefaultRank
		rlsc.mutation.SetRank(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rlsc *RpgLeaderboardSnapshotCreate) check() error {
	if _, ok := rlsc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "createTime", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.createTime"`)}
	}
	if _, ok := rlsc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "updateTime", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.updateTime"`)}
	}
	if _, ok := rlsc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.uid"`)}
	}
	if _, ok := rlsc.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.score"`)}
	}
	if _, ok := rlsc.mutation.Rank(); !ok {
		return &ValidationError{Name: "rank", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.rank"`)}
	}
	if _, ok := rlsc.mutation.PeriodType(); !ok {
		return &ValidationError{Name: "periodType", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.periodType"`)}
	}
	if _, ok := rlsc.mutation.PeriodKey(); !ok {
		return &ValidationError{Name: "periodKey", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.periodKey"`)}
	}
	if _, ok := rlsc.mutation.ScoreType(); !ok {
		return &ValidationError{Name: "scoreType", err: errors.New(`ent: missing required field "RpgLeaderboardSnapshot.scoreType"`)}
	}
	return nil
}

func (rlsc *RpgLeaderboardSnapshotCreate) sqlSave(ctx context.Context) (*RpgLeaderboardSnapshot, error) {
	if err := rlsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rlsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rlsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	rlsc.mutation.id = &_node.ID
	rlsc.mutation.done = true
	return _node, nil
}

func (rlsc *RpgLeaderboardSnapshotCreate) createSpec() (*RpgLeaderboardSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &RpgLeaderboardSnapshot{config: rlsc.config}
		_spec = sqlgraph.NewCreateSpec(rpgleaderboardsnapshot.Table, sqlgraph.NewFieldSpec(rpgleaderboardsnapshot.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rlsc.conflict
	if id, ok := rlsc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rlsc.mutation.CreateTime(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := rlsc.mutation.UpdateTime(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := rlsc.mutation.UID(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldUID, field.TypeInt, value)
		_node.UID = value
	}
	if value, ok := rlsc.mutation.Score(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := rlsc.mutation.Rank(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldRank, field.TypeInt, value)
		_node.Rank = value
	}
	if value, ok := rlsc.mutation.PeriodType(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldPeriodType, field.TypeString, value)
		_node.PeriodType = value
	}
	if value, ok := rlsc.mutation.PeriodKey(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldPeriodKey, field.TypeString, value)
		_node.PeriodKey = value
	}
	if value, ok := rlsc.mutation.ScoreType(); ok {
		_spec.SetField(rpgleaderboardsnapshot.FieldScoreType, field.TypeString, value)
		_node.ScoreType = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgLeaderboardSnapshot.Create().
//		SetCreateTime(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgLeaderboardSnapshotUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (rlsc *RpgLeaderboardSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *RpgLeaderboardSnapshotUpsertOne {
	rlsc.conflict = opts
	return &RpgLeaderboardSnapshotUpsertOne{
		create: rlsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rlsc *RpgLeaderboardSnapshotCreate) OnConflictColumns(columns ...string) *RpgLeaderboardSnapshotUpsertOne {
	rlsc.conflict = append(rlsc.conflict, sql.ConflictColumns(columns...))
	return &RpgLeaderboardSnapshotUpsertOne{
		create: rlsc,
	}
}

type (
	// RpgLeaderboardSnapshotUpsertOne is the builder for "upsert"-ing
	//  one RpgLeaderboardSnapshot node.
	RpgLeaderboardSnapshotUpsertOne struct {
		create *RpgLeaderboardSnapshotCreate
	}

	// RpgLeaderboardSnapshotUpsert is the "OnConflict" setter.
	RpgLeaderboardSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdateTime sets the "updateTime" field.
func (u *RpgLeaderboardSnapshotUpsert) SetUpdateTime(v time.Time) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdateUpdateTime() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldUpdateTime)
	return u
}

// SetUID sets the "uid" field.
func (u *RpgLeaderboardSnapshotUpsert) SetUID(v int) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldUID, v)
	return u
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdateUID() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldUID)
	return u
}

// AddUID adds v to the "uid" field.
func (u *RpgLeaderboardSnapshotUpsert) AddUID(v int) *RpgLeaderboardSnapshotUpsert {
	u.Add(rpgleaderboardsnapshot.FieldUID, v)
	return u
}

// SetScore sets the "score" field.
func (u *RpgLeaderboardSnapshotUpsert) SetScore(v int) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldScore, v)
	return u
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdateScore() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldScore)
	return u
}

// AddScore adds v to the "score" field.
func (u *RpgLeaderboardSnapshotUpsert) AddScore(v int) *RpgLeaderboardSnapshotUpsert {
	u.Add(rpgleaderboardsnapshot.FieldScore, v)
	return u
}

// SetRank sets the "rank" field.
func (u *RpgLeaderboardSnapshotUpsert) SetRank(v int) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldRank, v)
	return u
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdateRank() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldRank)
	return u
}

// AddRank adds v to the "rank" field.
func (u *RpgLeaderboardSnapshotUpsert) AddRank(v int) *RpgLeaderboardSnapshotUpsert {
	u.Add(rpgleaderboardsnapshot.FieldRank, v)
	return u
}

// SetPeriodType sets the "periodType" field.
func (u *RpgLeaderboardSnapshotUpsert) SetPeriodType(v string) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldPeriodType, v)
	return u
}

// UpdatePeriodType sets the "periodType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdatePeriodType() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldPeriodType)
	return u
}

// SetPeriodKey sets the "periodKey" field.
func (u *RpgLeaderboardSnapshotUpsert) SetPeriodKey(v string) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldPeriodKey, v)
	return u
}

// UpdatePeriodKey sets the "periodKey" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdatePeriodKey() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldPeriodKey)
	return u
}

// SetScoreType sets the "scoreType" field.
func (u *RpgLeaderboardSnapshotUpsert) SetScoreType(v string) *RpgLeaderboardSnapshotUpsert {
	u.Set(rpgleaderboardsnapshot.FieldScoreType, v)
	return u
}

// UpdateScoreType sets the "scoreType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsert) UpdateScoreType() *RpgLeaderboardSnapshotUpsert {
	u.SetExcluded(rpgleaderboardsnapshot.FieldScoreType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgleaderboardsnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateNewValues() *RpgLeaderboardSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rpgleaderboardsnapshot.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(rpgleaderboardsnapshot.FieldCreateTime)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RpgLeaderboardSnapshotUpsertOne) Ignore() *RpgLeaderboardSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgLeaderboardSnapshotUpsertOne) DoNothing() *RpgLeaderboardSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgLeaderboardSnapshotCreate.OnConflict
// documentation for more info.
func (u *RpgLeaderboardSnapshotUpsertOne) Update(set func(*RpgLeaderboardSnapshotUpsert)) *RpgLeaderboardSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgLeaderboardSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetUpdateTime(v time.Time) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateUpdateTime() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetUID sets the "uid" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetUID(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *RpgLeaderboardSnapshotUpsertOne) AddUID(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateUID() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateUID()
	})
}

// SetScore sets the "score" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetScore(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *RpgLeaderboardSnapshotUpsertOne) AddScore(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateScore() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateScore()
	})
}

// SetRank sets the "rank" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetRank(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *RpgLeaderboardSnapshotUpsertOne) AddRank(v int) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateRank() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateRank()
	})
}

// SetPeriodType sets the "periodType" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetPeriodType(v string) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetPeriodType(v)
	})
}

// UpdatePeriodType sets the "periodType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdatePeriodType() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdatePeriodType()
	})
}

// SetPeriodKey sets the "periodKey" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetPeriodKey(v string) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetPeriodKey(v)
	})
}

// UpdatePeriodKey sets the "periodKey" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdatePeriodKey() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdatePeriodKey()
	})
}

// SetScoreType sets the "scoreType" field.
func (u *RpgLeaderboardSnapshotUpsertOne) SetScoreType(v string) *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetScoreType(v)
	})
}

// UpdateScoreType sets the "scoreType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertOne) UpdateScoreType() *RpgLeaderboardSnapshotUpsertOne {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateScoreType()
	})
}

// Exec executes the query.
func (u *RpgLeaderboardSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgLeaderboardSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgLeaderboardSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RpgLeaderboardSnapshotUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RpgLeaderboardSnapshotUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RpgLeaderboardSnapshotCreateBulk is the builder for creating many RpgLeaderboardSnapshot entities in bulk.
type RpgLeaderboardSnapshotCreateBulk struct {
	config
	err      error
	builders []*RpgLeaderboardSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the RpgLeaderboardSnapshot entities in the database.
func (rlscb *RpgLeaderboardSnapshotCreateBulk) Save(ctx context.Context) ([]*RpgLeaderboardSnapshot, error) {
	if rlscb.err != nil {
		return nil, rlscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rlscb.builders))
	nodes := make([]*RpgLeaderboardSnapshot, len(rlscb.builders))
	mutators := make([]Mutator, len(rlscb.builders))
	for i := range rlscb.builders {
		func(i int, root context.Context) {
			builder := rlscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RpgLeaderboardSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rlscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rlscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rlscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rlscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rlscb *RpgLeaderboardSnapshotCreateBulk) SaveX(ctx context.Context) []*RpgLeaderboardSnapshot {
	v, err := rlscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rlscb *RpgLeaderboardSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := rlscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rlscb *RpgLeaderboardSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := rlscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RpgLeaderboardSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RpgLeaderboardSnapshotUpsert) {
//			SetCreateTime(v+v).
//		}).
//		Exec(ctx)
func (rlscb *RpgLeaderboardSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *RpgLeaderboardSnapshotUpsertBulk {
	rlscb.conflict = opts
	return &RpgLeaderboardSnapshotUpsertBulk{
		create: rlscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rlscb *RpgLeaderboardSnapshotCreateBulk) OnConflictColumns(columns ...string) *RpgLeaderboardSnapshotUpsertBulk {
	rlscb.conflict = append(rlscb.conflict, sql.ConflictColumns(columns...))
	return &RpgLeaderboardSnapshotUpsertBulk{
		create: rlscb,
	}
}

// RpgLeaderboardSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of RpgLeaderboardSnapshot nodes.
type RpgLeaderboardSnapshotUpsertBulk struct {
	create *RpgLeaderboardSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rpgleaderboardsnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateNewValues() *RpgLeaderboardSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rpgleaderboardsnapshot.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(rpgleaderboardsnapshot.FieldCreateTime)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RpgLeaderboardSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RpgLeaderboardSnapshotUpsertBulk) Ignore() *RpgLeaderboardSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RpgLeaderboardSnapshotUpsertBulk) DoNothing() *RpgLeaderboardSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RpgLeaderboardSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *RpgLeaderboardSnapshotUpsertBulk) Update(set func(*RpgLeaderboardSnapshotUpsert)) *RpgLeaderboardSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RpgLeaderboardSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdateTime sets the "updateTime" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetUpdateTime(v time.Time) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "updateTime" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateUpdateTime() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetUID sets the "uid" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetUID(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) AddUID(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateUID() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateUID()
	})
}

// SetScore sets the "score" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetScore(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetScore(v)
	})
}

// AddScore adds v to the "score" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) AddScore(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddScore(v)
	})
}

// UpdateScore sets the "score" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateScore() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateScore()
	})
}

// SetRank sets the "rank" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetRank(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetRank(v)
	})
}

// AddRank adds v to the "rank" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) AddRank(v int) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.AddRank(v)
	})
}

// UpdateRank sets the "rank" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateRank() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateRank()
	})
}

// SetPeriodType sets the "periodType" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetPeriodType(v string) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetPeriodType(v)
	})
}

// UpdatePeriodType sets the "periodType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdatePeriodType() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdatePeriodType()
	})
}

// SetPeriodKey sets the "periodKey" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetPeriodKey(v string) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetPeriodKey(v)
	})
}

// UpdatePeriodKey sets the "periodKey" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdatePeriodKey() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdatePeriodKey()
	})
}

// SetScoreType sets the "scoreType" field.
func (u *RpgLeaderboardSnapshotUpsertBulk) SetScoreType(v string) *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.SetScoreType(v)
	})
}

// UpdateScoreType sets the "scoreType" field to the value that was provided on create.
func (u *RpgLeaderboardSnapshotUpsertBulk) UpdateScoreType() *RpgLeaderboardSnapshotUpsertBulk {
	return u.Update(func(s *RpgLeaderboardSnapshotUpsert) {
		s.UpdateScoreType()
	})
}

// Exec executes the query.
func (u *RpgLeaderboardSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RpgLeaderboardSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RpgLeaderboardSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RpgLeaderboardSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
